# World Cup Experience

## Objective

Add 2026 World Cup experience features to each qualified team. This follows the same leakage-safe methods as the manager and player experience notebooks: only World Cup appearances before the 2026 tournament count as prior experience.

The final dataset keeps the 2026 distance and ELO features, then adds manager previous World Cups coached, player multiple previous World Cups played, and average squad age.

## Inputs

- `worldcup::manager_appearances`
- `worldcup::player_appearances`
- `worldcup::squads`
- `1.DataCleaning-R/Data/RDS/CoachTeamMatchesBeforeWC.rds`
- `1.DataCleaning-R/Data/RDS/WC2026DistanceELO.rds`
- `1.DataCleaning-R/Data/CSV/WC2026_squads_source.html`

## Outputs

- `1.DataCleaning-R/Data/RDS/WC2026Experience.rds`
- `1.DataCleaning-R/Data/CSV/WC2026Experience.csv`

## Packages

In [1]:
library(worldcup)
library(tidyverse)
library(lubridate)
library(rvest)
library(here)

Warning message:
"package 'ggplot2' was built under R version 4.4.3"
Warning message:
"package 'purrr' was built under R version 4.4.3"
-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
v dplyr     1.1.4     v readr     2.1.5
v forcats   1.0.0     v stringr   1.6.0
v ggplot2   4.0.1     v tibble    3.2.1
v lubridate 1.9.4     v tidyr     1.3.1
v purrr     1.2.1
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: 'rvest'


The following object is masked from 'package:readr':

    guess_encoding


here() starts at /Users/eialnisman/Desktop/WC2026Forecast

## Base 2026 Features

Start from the 2026 team-level file created in this folder.

In [2]:
wc_2026_base <- readRDS(here("1.DataCleaning-R", "Data", "RDS", "WC2026DistanceELO.rds"))

if (!"tournament_id" %in% names(wc_2026_base)) {
    wc_2026_base <- wc_2026_base %>%
        mutate(tournament_id = "WC-2026", .before = team_name)
}

wc_2026_base %>%
    count()

  n
1 48

## Helper Names

Use simple normalized names for matching 2026 squads and managers to the historical World Cup package data.

In [3]:
clean_name <- function(x) {
    x %>%
        str_remove_all("[[:space:]]*[(][^)]*[)]") %>%
        iconv(from = "UTF-8", to = "ASCII//TRANSLIT") %>%
        tolower() %>%
        str_replace_all("[^a-z ]", " ") %>%
        str_squish()
}

nft_to_full_name <- function(x) {
    if_else(
        str_detect(x, ","),
        str_squish(paste(
            str_trim(str_replace(x, "^[^,]+,", "")),
            str_trim(str_replace(x, ",.*$", ""))
        )),
        x
    )
}

wc_2026_team_name <- function(team) {
    case_when(
        team == "Cape Verde" ~ "Cabo Verde",
        team == "Cura\u00e7ao" ~ "Curacao",
        team == "Czech Republic" ~ "Czechia",
        team == "DR Congo" ~ "Congo DR",
        TRUE ~ team
    )
}

## Manager Experience

Summarize prior World Cup manager appearances before 2026 and match those records to the 2026 coach names.

In [4]:
manager_games <- worldcup::manager_appearances

manager_history_2026 <- manager_games %>%
    filter(tournament_id < "WC-2026") %>%
    mutate(
        manager_full_name = str_squish(paste(given_name, family_name)),
        coach_match_name = clean_name(manager_full_name)
    ) %>%
    group_by(coach_match_name) %>%
    summarize(
        prior_wc_matches_coached = n(),
        prior_world_cups_coached = n_distinct(tournament_id),
        matched_manager_name_worldcup = paste(unique(manager_full_name), collapse = "; "),
        .groups = "drop"
    )

coach_team_matches <- readRDS(here("1.DataCleaning-R", "Data", "RDS", "CoachTeamMatchesBeforeWC.rds"))

manager_experience_2026 <- coach_team_matches %>%
    filter(tournament_id == "WC-2026") %>%
    mutate(
        coach_full_name = nft_to_full_name(coach_name_nft),
        coach_match_name = clean_name(coach_full_name)
    ) %>%
    left_join(manager_history_2026, by = "coach_match_name") %>%
    mutate(
        prior_wc_matches_coached = replace_na(prior_wc_matches_coached, 0L),
        prior_world_cups_coached = replace_na(prior_world_cups_coached, 0L)
    ) %>%
    select(
        tournament_id,
        team_name,
        team_code,
        coach_name_nft,
        coach_full_name,
        matched_manager_name_worldcup,
        pre_wc_team_matches_coached = coach_team_matches_before_wc,
        prior_wc_matches_coached,
        prior_world_cups_coached
    )

manager_experience_2026 %>%
    arrange(desc(prior_world_cups_coached), team_name) %>%
    print(n = 10)

# A tibble: 48 x 9
   tournament_id team_name    team_code coach_name_nft           coach_full_name
   <chr>         <chr>        <chr>     <chr>                    <chr>
 1 WC-2026       France       FRA       "Deschamps, Didier"      "Didier Descha~
 2 WC-2026       Croatia      HRV       "Dali\u0107, Zlatko"     "Zlatko Dali\u~
 3 WC-2026       Mexico       MEX       "Aguirre, Javier"        "Javier Aguirr~
 4 WC-2026       Portugal     PRT       "Mart\u00ednez, Roberto" "Roberto Mart\~
 5 WC-2026       Saudi Arabia SAU       "Renard, Herv\u00e9"     "Herv\u00e9 Re~
 6 WC-2026       Uruguay      URY       "Bielsa, Marcelo"        "Marcelo Biels~
 7 WC-2026       Algeria      DZA       "Petkovi\u0107, Vladimi~ "Vladimir Petk~
 8 WC-2026       Argentina    ARG       "Scaloni, Lionel"        "Lionel Scalon~
 9 WC-2026       Ghana        GHA       "Addo, Otto"             "Otto Addo"
10 WC-2026       Iraq         IRQ       "Arnold, Graham"         "Graham Arnold"
# i 38 more rows
# i 4 more variables: matched_manager_name_worldcup <chr>,
#   pre_wc_team_matches_coached <int>, prior_wc_matches_coached <int>,
#   prior_world_cups_coached <int>

## 2026 Squads

Read the 2026 squad tables and build the same kind of player roster structure used in the player experience notebook.

In [5]:
squad_url <- "https://episteme.tllm.fr/wiki/2026_FIFA_World_Cup_squads"
squad_cache <- here("1.DataCleaning-R", "Data", "CSV", "WC2026_squads_source.html")

squad_html <- if (file.exists(squad_cache)) {
    read_html(squad_cache)
} else {
    read_html(squad_url)
}

squad_nodes <- squad_html %>%
    html_elements("h2, h3, table")

current_team <- NA_character_
squad_tables <- list()

for (node in squad_nodes) {
    node_name <- xml2::xml_name(node)

    if (node_name == "h3") {
        current_team <- html_text2(node)
    }

    if (node_name == "table" && !is.na(current_team)) {
        table <- html_table(node, fill = TRUE)

        if (ncol(table) == 7 && "Player" %in% names(table)) {
            squad_tables[[length(squad_tables) + 1]] <- table %>%
                mutate(wiki_team_name = current_team)
        }

        current_team <- NA_character_
    }
}

squads_2026 <- bind_rows(squad_tables) %>%
    transmute(
        tournament_id = "WC-2026",
        team_name = wc_2026_team_name(wiki_team_name),
        player_name = Player,
        birth_date = ymd(str_extract(`Date of birth (age)`, "[0-9]{4}-[0-9]{2}-[0-9]{2}")),
        player_match_name = clean_name(Player)
    )

squads_2026 %>%
    count(team_name, name = "squad_players") %>%
    arrange(squad_players, team_name) %>%
    print(n = 10)

# A tibble: 48 x 2
   team_name              squad_players
   <chr>                          <int>
 1 Austria                           25
 2 Canada                            25
 3 Algeria                           26
 4 Argentina                         26
 5 Australia                         26
 6 Belgium                           26
 7 Bosnia and Herzegovina            26
 8 Brazil                            26
 9 Cabo Verde                        26
10 Colombia                          26
# i 38 more rows

## Player Experience

Use World Cup appearances before 2026 to count each squad player's prior World Cup experience, then aggregate to team level.

In [6]:
historical_player_names <- worldcup::squads %>%
    filter(tournament_id %in% c("WC-2010", "WC-2014", "WC-2018", "WC-2022")) %>%
    transmute(
        player_id,
        historical_player_name = str_squish(paste(given_name, family_name)),
        player_match_name = clean_name(historical_player_name)
    ) %>%
    distinct()

player_history_2026 <- worldcup::player_appearances %>%
    filter(tournament_id < "WC-2026") %>%
    group_by(player_id) %>%
    summarize(
        prior_wc_matches_played = n(),
        prior_world_cups_played = n_distinct(tournament_id),
        .groups = "drop"
    )

player_roster_experience_2026 <- squads_2026 %>%
    mutate(current_player_row = row_number()) %>%
    left_join(
        historical_player_names,
        by = "player_match_name",
        relationship = "many-to-many"
    ) %>%
    left_join(player_history_2026, by = "player_id") %>%
    mutate(
        prior_wc_matches_played = replace_na(prior_wc_matches_played, 0L),
        prior_world_cups_played = replace_na(prior_world_cups_played, 0L)
    ) %>%
    group_by(current_player_row, tournament_id, team_name, player_name, birth_date) %>%
    summarize(
        prior_wc_matches_played = max(prior_wc_matches_played),
        prior_world_cups_played = max(prior_world_cups_played),
        .groups = "drop"
    )

player_experience_2026 <- player_roster_experience_2026 %>%
    group_by(tournament_id, team_name) %>%
    summarize(
        squad_players = n_distinct(current_player_row),
        avg_age = mean(as.numeric(as.Date("2026-06-11") - birth_date) / 365.25, na.rm = TRUE),
        missing_player_birth_dates = sum(is.na(birth_date)),
        players_with_prior_wc = sum(prior_wc_matches_played > 0),
        players_with_multiple_prior_wcs = sum(prior_world_cups_played > 1),
        .groups = "drop"
    )

player_experience_2026 %>%
    arrange(desc(players_with_multiple_prior_wcs), team_name) %>%
    print(n = 10)

# A tibble: 48 x 7
   tournament_id team_name   squad_players avg_age missing_player_birth_dates
   <chr>         <chr>               <int>   <dbl>                      <int>
 1 WC-2026       Iran                   26    30.3                          0
 2 WC-2026       Belgium                26    27.6                          0
 3 WC-2026       Colombia               26    30.1                          0
 4 WC-2026       England                26    27.1                          0
 5 WC-2026       Australia              26    27.4                          0
 6 WC-2026       Croatia                26    28.3                          0
 7 WC-2026       Germany                26    28.0                          0
 8 WC-2026       Mexico                 26    27.9                          0
 9 WC-2026       Switzerland            26    28.3                          0
10 WC-2026       Uruguay                26    28.7                          0
# i 38 more rows
# i 2 more variables: players_with_prior_wc <int>,
#   players_with_multiple_prior_wcs <int>

## Combine Experience

Join the manager and player experience features onto the 2026 distance and ELO data.

In [7]:
wc_2026_experience <- wc_2026_base %>%
    left_join(
        manager_experience_2026 %>%
            select(team_name, coach_name_nft, coach_full_name, pre_wc_team_matches_coached, prior_world_cups_coached),
        by = "team_name"
    ) %>%
    left_join(
        player_experience_2026 %>%
            select(team_name, squad_players, avg_age, missing_player_birth_dates, players_with_prior_wc, players_with_multiple_prior_wcs),
        by = "team_name"
    ) %>%
    arrange(team_name)

wc_2026_experience %>%
    summarize(
        teams = n(),
        missing_prior_world_cups_coached = sum(is.na(prior_world_cups_coached)),
        missing_players_with_multiple_prior_wcs = sum(is.na(players_with_multiple_prior_wcs)),
        missing_avg_age = sum(is.na(avg_age)),
        .groups = "drop"
    )

  teams missing_prior_world_cups_coached
1 48    0
  missing_players_with_multiple_prior_wcs missing_avg_age
1 0                                       0

Inspect

In [8]:
wc_2026_experience

   tournament_id team_name              team_id team_code distance_from_host_km
1  WC-2026       Algeria                T-01    DZA        8467.886
2  WC-2026       Argentina              T-03    ARG        9076.351
3  WC-2026       Australia              T-04    AUS       14653.989
4  WC-2026       Austria                T-05    AUT        8351.637
5  WC-2026       Belgium                T-06    BEL        7608.706
6  WC-2026       Bosnia and Herzegovina T-08    BIH        8799.915
7  WC-2026       Brazil                 T-09    BRA        7396.652
8  WC-2026       Cabo Verde             NA      CPV        7732.128
9  WC-2026       Canada                 T-12    CAN           0.000
10 WC-2026       Colombia               T-16    COL        4836.620
11 WC-2026       Congo DR               NA      COD       13091.614
12 WC-2026       Croatia                T-18    HRV        8608.749
13 WC-2026       Curacao                NA      CUW        4359.810
14 WC-2026       Czechia                T-20    CZE        8250.287
15 WC-2026       Ecuador                T-25    ECU        5050.644
16 WC-2026       Egypt                  T-26    EGY       11013.883
17 WC-2026       England                T-28    ENG        7152.496
18 WC-2026       France                 T-30    FRA        7714.673
19 WC-2026       Germany                T-31    DEU        7888.052
20 WC-2026       Ghana                  T-32    GHA       10227.033
21 WC-2026       Haiti                  T-34    HTI        3531.271
22 WC-2026       Iran                   T-38    IRN       11560.024
23 WC-2026       Iraq                   T-39    IRQ       11131.489
24 WC-2026       Ivory Coast            T-42    CIV        9853.150
25 WC-2026       Japan                  T-44    JPN        9562.527
26 WC-2026       Jordan                 NA      JOR       10984.602
27 WC-2026       Mexico                 T-46    MEX           0.000
28 WC-2026       Morocco                T-47    MAR        8047.458
29 WC-2026       Netherlands            T-48    NLD        7554.561
30 WC-2026       New Zealand            T-49    NZL       12567.390
31 WC-2026       Norway                 T-53    NOR        7116.619
32 WC-2026       Panama                 T-54    PAN        3966.490
33 WC-2026       Paraguay               T-55    PRY        8273.165
34 WC-2026       Portugal               T-58    PRT        7492.663
35 WC-2026       Qatar                  T-59    QAT       12201.517
36 WC-2026       Saudi Arabia           T-63    SAU       11783.518
37 WC-2026       Scotland               T-64    SCO        6752.840
38 WC-2026       Senegal                T-65    SEN        8646.943
39 WC-2026       South Africa           T-70    ZAF       14937.121
40 WC-2026       South Korea            T-71    KOR       10196.189
41 WC-2026       Spain                  T-73    ESP        7746.923
42 WC-2026       Sweden                 T-74    SWE        7465.038
43 WC-2026       Switzerland            T-75    CHE        8079.838
44 WC-2026       Tunisia                T-79    TUN        9114.638
45 WC-2026       Turkey                 T-80    TUR       10136.437
46 WC-2026       United States          T-83    USA           0.000
47 WC-2026       Uruguay                T-84    URY        9282.411
48 WC-2026       Uzbekistan             NA      UZB       10859.455
   elo_2026 coach_name_nft                 coach_full_name
1  1757     Petkovi<U+0107>, Vladimir      Vladimir Petkovi<U+0107>
2  2113     Scaloni, Lionel                Lionel Scaloni
3  1774     Popovi<U+0107>, Tony           Tony Popovi<U+0107>
4  1818     Rangnick, Ralf                 Ralf Rangnick
5  1850     Garcia, Rudi                   Rudi Garcia
6  1572     Barbarez, Sergej               Sergej Barbarez
7  1978     Ancelotti, Carlo               Carlo Ancelotti
8  1561     Bubista,                       Bubista
9  1802     Marsch, Jesse                  Jesse Marsch
10 1998     Lorenzo, N<U+00E9>stor         N<U+00E9>stor Lorenzo
11 1657     Desabre, S<U+00E9>bastien      S<U+00E9>bastien Desabre
12 1932     Dali<U+0107>, Zlatko           Zlatko Dali<U+0107>
13 1466     Rutten, Fred                   Fred Rutten
14 1731     Koubek, Miroslav               Miroslav Koubek
15 1933     Beccacece, Sebasti<U+00E1>n    Sebasti<U+00E1>n Beccacece
16 1622     Hassan, Hossam                 Hossam Hassan
17 2042     Tuchel, Thomas                 Thomas Tuchel
18 2062     Deschamps, Didier              Didier Deschamps
19 1910     Nagelsmann, Julian             Julian Nagelsmann
20 1509     Addo, Otto                     Otto Addo
21 1542     Mign<U+00E9>, S<U+00E9>bastien S<U+00E9>bastien Mign<U+00E9>
22 1755     Ghalenoei, Amir                Amir Ghalenoei
23 1582     Arnold, Graham                 Graham Arnold
24 1627     Fa<U+00E9>, Emerse             Emerse Fa<U+00E9>
25 1878     Moriyasu, Hajime               Hajime Moriyasu
26 1689     Sellami, Jamel                 Jamel Sellami
27 1835     Aguirre, Javier                Javier Aguirre
28 1840     Regragui, Walid                Walid Regragui
29 1959     Koeman, Ronald                 Ronald Koeman
30 1585     Bazeley, Darren                Darren Bazeley
31 1922     Solbakken, St<U+00E5>le        St<U+00E5>le Solbakken
32 1742     Christiansen, Thomas           Thomas Christiansen
33 1833     Alfaro, Gustavo                Gustavo Alfaro
34 1976     Mart<U+00ED>nez, Roberto       Roberto Mart<U+00ED>nez
35 1425     NA                             NA
36 1592     Renard, Herv<U+00E9>           Herv<U+00E9> Renard
37 1790     Clarke, Stevie                 Stevie Clarke
38 1807     Thiaw, Pape                    Pape Thiaw
39 1550     Broos, Hugo                    Hugo Broos
40 1784     Hong, Myung-Bo                 Myung-Bo Hong
41 2172     de La Fuente, Luis             Luis de La Fuente
42 1660     Potter, Graham                 Graham Potter
43 1897     Yak<U+0131>n, Murat            Murat Yak<U+0131>n
44 1615     Trabelsi, Sami                 Sami Trabelsi
45 1880     Montella, Vincenzo             Vincenzo Montella
46 1747     Pochettino, Mauricio           Mauricio Pochettino
47 1890     Bielsa, Marcelo                Marcelo Bielsa
48 1735     Cannavaro, Fabio               Fabio Cannavaro
   pre_wc_team_matches_coached prior_world_cups_coached squad_players avg_age
1   27                         1                        26            26.85410
2   94                         1                        26            29.05228
3   16                         0                        26            27.35945
4   44                         0                        25            28.60901
5   12                         0                        26            27.61449
6   20                         0                        26            26.42247
7   10                         0                        26            29.20276
8   59                         0                        26            29.67641
9   30                         0                        25            27.10330
10  44                         0                        26            30.08930
11  46                         0                        26            29.06871
12 105                         2                        26            28.32875
13   2                         0                        26            28.02096
14   2                         0                        26            27.62081
15  18                         0                        26            26.07761
16  28                         0                        26            29.05892
17  12                         0                        26            27.14411
18 174                         3                        26            27.00100
19  31                         0                        26            27.97789
20  34                         1                        26            26.97520
21  22                         0                        26            27.57784
22  43                         0                        26            30.33254
23  12                         1                        26            27.15453
24  31                         0                        26            25.84900
25 103                         1                        26            27.75043
26  29                         0                        26            28.44416
27  26                         2                        26            27.90070
28  49                         1                        26            26.39457
29  38                         0                        26            27.73927
30  32                         0                        26            28.11794
31  54                         0                        26            26.80419
32  89                         0                        26            30.42658
33  19                         1                        26            29.03101
34  38                         2                        26            28.03528
35  NA                         0                        26            29.50771
36  71                         2                        26            28.51608
37  76                         0                        26            29.20244
38  37                         0                        26            27.08724
39  55                         0                        26            26.80840
40  21                         1                        26            28.06571
41  40                         0                        26            26.74743
42   4                         0                        26            27.55710
43  57                         1                        26            28.30706
44  19                         0                        26            26.64466
45  31                         0                        26            27.67220
46  24                         0                        26            26.90496
47  34                         2                        26            28.74227
48   6                         0                        26            28.51166
   missing_player_birth_dates players_with_prior_wc
1  0                           3
2  0                          16
3  0                           8
4  0                           0
5  0                          11
6  0                           2
7  0                           5
8  0                           0
9  0                          10
10 0                           9
11 0                           0
12 0                          13
13 0                           0
14 0                           0
15 0                          11
16 0                           2
17 0                           8
18 0                          13
19 0                           9
20 0                           8
21 0                           0
22 0                          12
23 0                           0
24 0                           0
25 0                          13
26 0                           0
27 0                          10
28 0                           9
29 0                          11
30 0                           2
31 0                           0
32 0                           5
33 0                           0
34 0                          14
35 0                          12
36 0                           9
37 0                           0
38 0                          13
39 0                           0
40 0                           6
41 0                           6
42 0                           1
43 0                          15
44 0                           7
45 0                           0
46 0                          11
47 0                          13
48 0                           0
   players_with_multiple_prior_wcs
1  0
2  3
3  4
4  0
5  6
6  0
7  0
8  0
9  0
10 5
11 0
12 4
13 0
14 0
15 1
16 0
17 5
18 3
19 4
20 1
21 0
22 9
23 0
24 0
25 1
26 0
27 4
28 3
29 1
30 0
31 0
32 0
33 0
34 3
35 0
36 3
37 0
38 3
39 0
40 0
41 0
42 0
43 4
44 2
45 0
46 0
47 4
48 0

In [11]:
wc_2026_experience <- wc_2026_experience %>%
    select(team_name,team_id,team_code,prior_world_cups_coached,avg_age, players_with_multiple_prior_wcs)

## Save

Save RDS

In [12]:
saveRDS(wc_2026_experience, here("1.DataCleaning-R", "Data", "RDS", "WC2026Experience.rds"))