# Player Data Kaggle-Fjelstul

## Objectives

Develop a dataset with Kaggle dataset ID's, Fjestul Dataset IDs, and Player Names.

This will serve as a mathcing tool to assign season data (from the kaggle dataset) to world cup data (from the Fjestul dataset)

## Inputs

- `1.DataCleaning-R/Data/RDS/FullRoster.rds`
- `1.DataCleaning-R/kaggle_data/players.csv`

## Output

- `1.DataCleaning-R/Data/RDS/Matching.rds`

## Acknowledgments

Data in this notebook is taken from Kaggle using Kaggle's API. The dataset in Kaggle is made from data originally from Transfermarket.com.

## Libraries

In [2]:
library(dplyr)
library(here)
library(stringr)
library(stringi)

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


here() starts at /Users/eialnisman/Desktop/WC2026Forecast

## Player data (Kaggle)

### Call Data with our Kaggle API

In [3]:
system("kaggle datasets download davidcariboo/player-scores -p kaggle_data")

unzip("kaggle_data/player-scores.zip",exdir = "kaggle_data")

Warning message in unzip("kaggle_data/player-scores.zip", exdir = "kaggle_data"):
"zip file is corrupt"

In [4]:
player_data <- read.csv(here("1.DataCleaning-R", "kaggle_data", "players.csv"), stringsAsFactors = FALSE, encoding = "UTF-8")

colnames(player_data)

 [1] "player_id"
 [2] "first_name"
 [3] "last_name"
 [4] "name"
 [5] "last_season"
 [6] "current_club_id"
 [7] "player_code"
 [8] "country_of_birth"
 [9] "city_of_birth"
[10] "country_of_citizenship"
[11] "date_of_birth"
[12] "sub_position"
[13] "position"
[14] "foot"
[15] "height_in_cm"
[16] "contract_expiration_date"
[17] "agent_name"
[18] "image_url"
[19] "international_caps"
[20] "international_goals"
[21] "current_national_team_id"
[22] "url"
[23] "current_club_domestic_competition_id"
[24] "current_club_name"
[25] "market_value_in_eur"
[26] "highest_market_value_in_eur"

In [5]:
player_names <- player_data %>%
    select(player_id, name, last_season)

## Clean Data

### Lets get the player names and IDs from Fjestul

In [6]:
worldcup_players <- readRDS(here("1.DataCleaning-R", "Data", "RDS", "FullRoster.rds"))

worldcup_players <- worldcup_players %>%
    select(player_id, full_name, tournament_id) %>%
        arrange(desc(tournament_id)) %>%
        distinct(player_id, .keep_all = TRUE)

Since the dataset for worldcup_players and player_namess come from sepearate orders their player_id system is different. It is also likely that some names may not match exaclty, lets investigate this possibility.

In [7]:
length(setdiff(worldcup_players$full_name, player_names$name))
length(worldcup_players$full_name)
setdiff(worldcup_players$full_name, player_names$name)

[1] 856

[1] 2379

  [1] "Juli<U+00E1>n <U+00C1>lvarez" "Milo<U+0161> Degenek"
  [3] "Fran Kara<U+010D>i<U+0107>" "Bailey Wright"
  [5] "Cameron Devlin"             "not applicable Alisson"
  [7] "not applicable Danilo"      "not applicable Marquinhos"
  [9] "not applicable Casemiro"    "not applicable Fred"
 [11] "not applicable Richarlison" "not applicable Neymar"
 [13] "not applicable Raphinha"    "not applicable Weverton"
 [15] "not applicable Fabinho"     "not applicable Antony"
 [17] "Vin<U+00ED>cius J<U+00FA>nior" "not applicable Rodrygo"
 [19] "<U+00C9>verton Ribeiro"     "not applicable Ederson"
 [21] "not applicable Bremer"      "not applicable Pedro"
 [23] "Jerome Ngom Mbekeli"        "Nicolas Nkoulou"
 [25] "Moumi Ngamaleu"             "Georges-K<U+00E9>vin Nkoudou"
 [27] "Andr<U+00E9>-Frank Zambo Anguissa" "Eric Maxim Choupo-Moting"
 [29] "Samuel Gouet"               "Nouhou Tolo"
 [31] "Souaibou Marou"             "Stephen Eust<U+00E1>quio"
 [33] "Liam Fraser"                "Lucas Cavallini"
 [35] "Daniel Chac<U+00F3>n"       "Keysher Fuller"
 [37] "Johan Venegas"              "Gerson Torres"
 [39] "Douglas L<U+00F3>pez"       "R<U+00F3>nald Matarrita"
 [41] "Dominik Livakovi<U+0107>"   "Josip Stani<U+0161>i<U+0107>"
 [43] "Borna Bari<U+0161>i<U+0107>" "Mateo Kova<U+010D>i<U+0107>"
 [45] "Andrej Kramari<U+0107>"     "Ivo Grbi<U+0107>"
 [47] "Bruno Petkovi<U+0107>"      "Mislav Or<U+0161>i<U+0107>"
 [49] "Jo<U+0161>ko Gvardiol"      "Josip Juranovi<U+0107>"
 [51] "Ivica Ivu<U+0161>i<U+0107>" "Josip <U+0160>utalo"
 [53] "Luka Su<U+010D>i<U+0107>"   "Kristijan Jaki<U+0107>"
 [55] "Joakim M<U+00E6>hle"        "Jens Stryger Larsen"
 [57] "Frederik R<U+00F8>nnow"     "William Pacho"
 [59] "Romario Ibarra"             "Michael Estrada"
 [61] "Xavier Arreaga"             "<U+00C1>ngelo Preciado"
 [63] "Sebas M<U+00E9>ndez"        "Alexander Dom<U+00ED>nguez"
 [65] "Djorkaeff Reasco"           "Matteo Guendouzi"
 [67] "Lucas Hernandez"            "Th<U+00E9>o Hernandez"
 [69] "Lawrence Ati-Zigi"          "Abdul Fatawu Issahaku"
 [71] "Ibrahim Danlad"             "Abdul Manaf Nurudeen"
 [73] "Baba Rahman"                "Shojae Khalilzadeh"
 [75] "Hossein Kanaanizadegan"     "Rouzbeh Cheshmi"
 [77] "Mehdi Torabi"               "Ahmad Nourollahi"
 [79] "Hossein Hosseini"           "Abolfazl Jalali"
 [81] "Ritsu D<U+014D>an"          "Sh<U+016B>ichi Gonda"
 [83] "Alfredo Talavera"           "N<U+00E9>stor Araujo"
 [85] "Henry Mart<U+00ED>n"        "Munir Mohamedi"
 [87] "Ilias Chair"                "Ahmed Reda Tagnaouti"
 [89] "Bilal El Khannous"          "Badr Benoun"
 [91] "Yahya Jabrane"              "Wojciech Szcz<U+0119>sny"
 [93] "<U+0141>ukasz Skorupski"    "Jakub Kami<U+0144>ski"
 [95] "Sebastian Szyma<U+0144>ski" "Piotr Zieli<U+0144>ski"
 [97] "Krzysztof Pi<U+0105>tek"    "Przemys<U+0142>aw Frankowski"
 [99] "Micha<U+0142> Sk<U+00F3>ra<U+015B>" "not applicable Pepe"
[101] "not applicable Vitinha"     "not applicable Ot<U+00E1>vio"
[103] "Saad Al-Sheeb"              "not applicable R<U+00F3>-R<U+00F3>"
[105] "Abdulaziz Hatem"            "Ali Assadalla"
[107] "Hassan Al-Haydos"           "Musab Kheder"
[109] "Homam Ahmed"                "Ismaeel Mohammad"
[111] "Khalid Muneer"              "Salem Al-Hajri"
[113] "Yousef Hassan"              "Naif Al-Hadhrami"
[115] "Mostafa Meshaal"            "Mohammed Al-Rubaie"
[117] "Ali Al-Bulaihi"             "Mohammed Al-Breik"
[119] "Abdulellah Al-Malki"        "Hassan Al-Tambakti"
[121] "Abdulrahman Al-Aboud"       "Moussa N'Diaye"
[123] "<U+00C9>douard Mendy"       "Moustapha Name"
[125] "Marko Dmitrovi<U+0107>"     "Strahinja Erakovi<U+0107>"
[127] "Milo<U+0161> Veljkovi<U+0107>" "Nemanja Maksimovi<U+0107>"
[129] "Nemanja Radonji<U+0107>"    "Andrija <U+017D>ivkovi<U+0107>"
[131] "Sr<U+0111>an Babi<U+0107>"  "Uro<U+0161> Ra<U+010D>i<U+0107>"
[133] "Filip <U+0110>uri<U+010D>i<U+0107>" "Filip Mladenovi<U+0107>"
[135] "Yoon Jong-gyu"              "Kim Jin-su"
[137] "Kim Min-jae"                "Hwang In-beom"
[139] "Paik Seung-ho"              "Cho Gue-sung"
[141] "Song Bum-keun"              "Son Jun-ho"
[143] "Kim Moon-hwan"              "Hwang Ui-jo"
[145] "Na Sang-ho"                 "Lee Kang-in"
[147] "Kwon Kyung-won"             "Kwon Chang-hoon"
[149] "Kim Tae-hwan"               "Cho Yu-min"
[151] "Jeong Woo-yeong"            "Song Min-kyu"
[153] "not applicable Koke"        "not applicable Gavi"
[155] "not applicable Rodri"       "Yeremy Pino"
[157] "Dani Carvajal"              "not applicable Pedri"
[159] "Ruben Vargas"               "Aymen Mathlouthi"
[161] "Bilel Ifa"                  "Hannibal Mejbri"
[163] "Taha Yassine Khenissi"      "Ali Ma<U+00E2>loul"
[165] "Mohamed Ali Ben Romdhane"   "Ghailene Chaalali"
[167] "Seifeddine Jaziri"          "Bechir Ben Sa<U+00EF>d"
[169] "Anis Ben Slimane"           "Cristian Roldan"
[171] "Jos<U+00E9> Gim<U+00E9>nez" "Ronald Ara<U+00FA>jo"
[173] "Giorgian De Arrascaeta"     "Sebasti<U+00E1>n Sosa"
[175] "Joe Morrell"                "Jonny Williams"
[177] "James Meredith"             "Tim Cahill"
[179] "Dimitri Petratos"           "not applicable Miranda"
[181] "not applicable Marcelo"     "not applicable Paulinho"
[183] "not applicable C<U+00E1>ssio" "not applicable Fernandinho"
[185] "not applicable Willian"     "not applicable Taison"
[187] "not applicable Fagner"      "Cristi<U+00E1>n Zapata"
[189] "<U+00D3>scar Murillo"       "Mateus Uribe"
[191] "Farid D<U+00ED>az"          "Jos<U+00E9> Fernando Cuadrado"
[193] "Jhonny Acosta"              "Daniel Colindres"
[195] "Patrick Pemberton"          "David Guzm<U+00E1>n"
[197] "Marco Ure<U+00F1>a"         "Kenner Guti<U+00E9>rrez"
[199] "Leonel Moreira"             "<U+0160>ime Vrsaljko"
[201] "Ivan Strini<U+0107>"        "Vedran <U+0106>orluka"
[203] "Ivan Rakiti<U+0107>"        "Lovre Kalini<U+0107>"
[205] "Filip Bradari<U+0107>"      "Duje <U+0106>aleta-Car"
[207] "Nikola Kalini<U+0107>"      "Mario Mand<U+017E>uki<U+0107>"
[209] "Josip Pivari<U+0107>"       "Danijel Suba<U+0161>i<U+0107>"
[211] "Nicolai J<U+00F8>rgensen"   "Essam El Hadary"
[213] "Omar Gaber"                 "Ahmed Hegazi"
[215] "Ahmed Fathy"                "not applicable Kahraba"
[217] "Ayman Ashraf"               "Mohamed Abdel Shafy"
[219] "Mahmoud Hamdy"              "Sherif Ekramy"
[221] "not applicable Shikabala"   "Abdallah El Said"
[223] "Saad Samir"                 "not applicable Tr<U+00E9>z<U+00E9>guet"
[225] "Hannes <U+00DE><U+00F3>r Halld<U+00F3>rsson" "Birkir M<U+00E1>r S<U+00E6>varsson"
[227] "Sam<U+00FA>el Fri<U+00F0>j<U+00F3>nsson" "Albert Gu<U+00F0>mundsson"
[229] "Ragnar Sigur<U+00F0>sson"   "J<U+00F3>hann Berg Gu<U+00F0>mundsson"
[231] "Bj<U+00F6>rn Bergmann Sigur<U+00F0>arson" "Gylfi Sigur<U+00F0>sson"
[233] "Alfre<U+00F0> Finnbogason"  "H<U+00F3>lmar <U+00D6>rn Eyj<U+00F3>lfsson"
[235] "H<U+00F6>r<U+00F0>ur Bj<U+00F6>rgvin Magn<U+00FA>sson" "Emil Hallfre<U+00F0>sson"
[237] "J<U+00F3>n Da<U+00F0>i B<U+00F6><U+00F0>varsson" "Mohammad Rashid Mazaheri"
[239] "Mohammad Reza Khanzadeh"    "Pejman Montazeri"
[241] "Tomoaki Makino"             "G<U+014D>toku Sakai"
[243] "Jos<U+00E9> de Jes<U+00FA>s Corona" "Hugo Ayala"
[245] "Rafael M<U+00E1>rquez"      "Javier Hern<U+00E1>ndez"
[247] "Jes<U+00FA>s Manuel Corona" "Oribe Peralta"
[249] "Mbark Boussoufa"            "Aziz Bouhaddouz"
[251] "Mehdi Carcela"              "Ikechukwu Ezenwa"
[253] "Brian Idowu"                "Elderson Echi<U+00E9>jil<U+00E9>"
[255] "John Obi Mikel"             "Shehu Abdullahi"
[257] "Simeon Nwankwo"             "Daniel Akpeyi"
[259] "Jaime Penedo"               "Michael Amir Murillo"
[261] "Harold Cummings"            "Gabriel G<U+00F3>mez"
[263] "Blas P<U+00E9>rez"          "<U+00C9>dgar B<U+00E1>rcenas"
[265] "Gabriel Torres"             "Armando Cooper"
[267] "Adolfo Machado"             "Valent<U+00ED>n Pimentel"
[269] "Erick Davis"                "Luis Ovalle"
[271] "Luis Tejada"                "Ricardo <U+00C1>vila"
[273] "<U+00C1>lex Rodr<U+00ED>guez" "Felipe Baloy"
[275] "Aldo Corzo"                 "Ra<U+00FA>l Ruid<U+00ED>az"
[277] "Christian Ramos"            "Jos<U+00E9> Carvallo"
[279] "Nilson Loyola"              "Micha<U+0142> Pazdan"
[281] "Jacek G<U+00F3>ralski"      "Bartosz Bia<U+0142>kowski"
[283] "<U+0141>ukasz Teodorczyk"   "Jakub B<U+0142>aszczykowski"
[285] "S<U+0142>awomir Peszko"     "<U+0141>ukasz Piszczek"
[287] "<U+0141>ukasz Fabia<U+0144>ski" "not applicable C<U+00E9>dric"
[289] "not applicable Beto"        "Sergei Ignashevich"
[291] "Andrei Semyonov"            "Daler Kuzyayev"
[293] "Yury Gazinsky"              "Fyodor Smolov"
[295] "Andrey Lunyov"              "Fyodor Kudryashov"
[297] "Aleksei Miranchuk"          "Yuri Zhirkov"
[299] "Aleksandr Yerokhin"         "Mansoor Al-Harbi"
[301] "Omar Hawsawi"               "Mohammad Al-Sahlawi"
[303] "Abdulmalek Al-Khaibri"      "Housain Al-Mogahwi"
[305] "Taisir Al-Jassim"           "Muhannad Assiri"
[307] "Yasser Al-Mosailem"         "Motaz Hawsawi"
[309] "Kara Mbodji"                "Mame Biram Diouf"
[311] "Khadim N'Diaye"             "Du<U+0161>ko To<U+0161>i<U+0107>"
[313] "Luka Milivojevi<U+0107>"    "Uro<U+0161> Spaji<U+0107>"
[315] "Branislav Ivanovi<U+0107>"  "Aleksandar Prijovi<U+0107>"
[317] "Milan Rodi<U+0107>"         "Adem Ljaji<U+0107>"
[319] "Ban-suk Oh"                 "Young-sun Yun"
[321] "Joo-ho Park"                "Shin-wook Kim"
[323] "Hyun-soo Jang"              "Yo-han Go"
[325] "not applicable Nacho"       "not applicable Sa<U+00FA>l"
[327] "not applicable Rodrigo"     "not applicable Thiago"
[329] "not applicable Isco"        "Blerim D<U+017E>emaili"
[331] "G<U+00E9>lson Fernandes"    "Mario Gavranovi<U+0107>"
[333] "Josip Drmi<U+0107>"         "Farouk Ben Mustapha"
[335] "Rami Bedoui"                "Mohamed Amine Ben Amor"
[337] "Ahmed Khalil"               "Hamdi Nagguez"
[339] "Mart<U+00ED>n Campa<U+00F1>a" "Maxi Pereira"
[341] "Mart<U+00ED>n Silva"        "C<U+00E9>dric Si Mohamed"
[343] "Madjid Bougherra"           "Hillal Soudani"
[345] "Mohamed Zemmamouche"        "Liassine Cadamuro-Benta<U+00EF>ba"
[347] "Abdelmoumene Djabou"        "Maxi Rodr<U+00ED>guez"
[349] "Agust<U+00ED>n Ori<U+00F3>n" "Ricky <U+00C1>lvarez"
[351] "Matthew Spiranovic"         "James Holland"
[353] "Matt McKay"                 "Eugene Galekovic"
[355] "Dario Vido<U+0161>i<U+0107>" "Alex Wilkinson"
[357] "Mark Bresciano"             "Asmir Begovi<U+0107>"
[359] "Avdija Vr<U+0161>ajevi<U+0107>" "Ermin Bi<U+010D>ak<U+010D>i<U+0107>"
[361] "Emir Spahi<U+0107>"         "Sead Kola<U+0161>inac"
[363] "Ognjen Vranje<U+0161>"      "Muhamed Be<U+0161>i<U+0107>"
[365] "Vedad Ibi<U+0161>evi<U+0107>" "Zvjezdan Misimovi<U+0107>"
[367] "Edin D<U+017E>eko"          "Jasmin Fejzi<U+0107>"
[369] "Mensur Mujd<U+017E>a"       "Tino-Sven Su<U+0161>i<U+0107>"
[371] "Toni <U+0160>unji<U+0107>"  "Senad Luli<U+0107>"
[373] "Senijad Ibri<U+010D>i<U+0107>" "Edin Vi<U+0161><U+0107>a"
[375] "Izet Hajrovi<U+0107>"       "Anel Had<U+017E>i<U+0107>"
[377] "Asmir Avduki<U+0107>"       "Sejad Salihovi<U+0107>"
[379] "not applicable Jefferson"   "not applicable Hulk"
[381] "not applicable Oscar"       "not applicable Dante"
[383] "not applicable Maxwell"     "not applicable Henrique"
[385] "not applicable Ramires"     "not applicable Hernanes"
[387] "not applicable Bernard"     "not applicable J<U+00F4>"
[389] "not applicable Victor"      "not applicable Maicon"
[391] "Lo<U+00EF>c Feudjou"        "C<U+00E9>dric Djeugou<U+00E9>"
[393] "Jo<U+00EB>l Matip"          "Eugenio Mena"
[395] "Jorge Valdivia"             "Cristopher Toselli"
[397] "Jos<U+00E9> Manuel Rojas"   "Jos<U+00E9> Pablo Fuenzalida"
[399] "Esteban Paredes"            "Johnny Herrera"
[401] "Alexander Mej<U+00ED>a"     "<U+00C9>der <U+00C1>lvarez Balanta"
[403] "Juan Camilo Z<U+00FA><U+00F1>iga" "Faryd Mondrag<U+00F3>n"
[405] "Carlos Vald<U+00E9>s"       "Michael Uma<U+00F1>a"
[407] "David Myrie"                "Michael Barrantes"
[409] "Waylon Francis"             "<U+00D3>scar Granados"
[411] "Randall Brenes"             "Roy Miller"
[413] "Diego Calvo"                "Jos<U+00E9> Miguel Cubero"
[415] "Daniel Cambronero"          "Danijel Pranji<U+0107>"
[417] "Ognjen Vukojevi<U+0107>"    "Nikica Jelavi<U+0107>"
[419] "Ivica Oli<U+0107>"          "not applicable Sammir"
[421] "not applicable Eduardo"     "M<U+00E1>ximo Banguera"
[423] "Jorge Guagua"               "Frickson Erazo"
[425] "<U+00C9>dison M<U+00E9>ndez" "Joao Rojas"
[427] "Walter Ayov<U+00ED>"        "Adri<U+00E1>n Bone"
[429] "Oswaldo Minda"              "Michael Arroyo"
[431] "Jaime Ayov<U+00ED>"         "<U+00D3>scar Bag<U+00FC><U+00ED>"
[433] "Luis Saritama"              "Fidel Mart<U+00ED>nez"
[435] "Gabriel Achilier"           "Stephen Adams"
[437] "Emmanuel Agyemang-Badu"     "Adam Larsen Kwarasey"
[439] "Rashid Sumaila"             "Fatau Dauda"
[441] "Abdul Majeed Waris"         "Harrison Afful"
[443] "Giorgos Tzavellas"          "Kostas Manolas"
[445] "Kostas Mitroglou"           "Giorgos Karagounis"
[447] "Dimitris Salpingidis"       "Vasilis Torosidis"
[449] "Jos<U+00E9> Holebas"        "Kostas Katsouranis"
[451] "Osman Ch<U+00E1>vez"        "Juan Pablo Montes"
[453] "V<U+00ED>ctor Bern<U+00E1>rdez" "Juan Carlos Garc<U+00ED>a"
[455] "Jerry Palacios"             "Jerry Bengtson"
[457] "Edder Delgado"              "Boniek Garc<U+00ED>a"
[459] "Roger Espinoza"             "Rony Mart<U+00ED>nez"
[461] "Andy Najar"                 "Noel Valladares"
[463] "Luis Garrido"               "Donis Escober"
[465] "Marvin Ch<U+00E1>vez"       "Rahman Ahmadi"
[467] "Khosro Heydari"             "Jalal Hosseini"
[469] "Amir Hossein Sadeghi"       "Javad Nekounam"
[471] "Reza Haghighi"              "Ghasem Haddadifar"
[473] "Hossein Mahini"             "Andranik Teymourian"
[475] "Ahmad Alenemeh"             "Bakhtiar Rahmani"
[477] "Hashem Beikzadeh"           "Steven Beitashour"
[479] "Mehrdad Pooladi"            "Boubacar Barry"
[481] "Cheick Tiot<U+00E9>"        "not applicable Gervinho"
[483] "Isma<U+00EB>l Diomand<U+00E9>" "Sylvain Gbohouo"
[485] "Serey Di<U+00E9>"           "Sayouba Mand<U+00E9>"
[487] "Yasuhito End<U+014D>"       "Yoichiro Kakitani"
[489] "Yoshito <U+014C>kubo"       "Yasuyuki Konno"
[491] "Masahiko Inoha"             "Manabu Sait<U+014D>"
[493] "Francisco Javier Rodr<U+00ED>guez" "Carlos Salcido"
[495] "Miguel <U+00C1>ngel Ponce"  "Isa<U+00E1>c Brizuela"
[497] "Paul Aguilar"               "Jos<U+00E9> Juan V<U+00E1>zquez"
[499] "Azubuike Egwuekwe"          "Kunle Odunlami"
[501] "Austin Ejide"               "Michael Babatunde"
[503] "Chigozie Agbim"             "not applicable Vieirinha"
[505] "not applicable Eder"        "Raul Meireles"
[507] "not applicable Nani"        "Aleksei Kozlov"
[509] "Georgi Shchennikov"         "Yuri Lodygin"
[511] "Vasili Berezutski"          "Viktor Fayzulin"
[513] "Aleksei Ionov"              "Andrey Yeshchenko"
[515] "Dmitri Kombarov"            "Chang-soo Kim"
[517] "Suk-young Yun"              "Tae-hwi Kwak"
[519] "Dae-sung Ha"                "Keun-ho Lee"
[521] "Kook-young Han"             "Jong-woo Park"
[523] "Bum-young Lee"              "not applicable Juanfran"
[525] "not applicable Xavi"        "Omar Gonzalez"
[527] "Matt Besler"                "DaMarcus Beasley"
[529] "Brad Davis"                 "Kyle Beckerman"
[531] "Chris Wondolowski"          "Graham Zusi"
[533] "Nick Rimando"               "Diego Forl<U+00E1>n"
[535] "Rodrigo Mu<U+00F1>oz"       "Loun<U+00E8>s Gaouaoui"
[537] "Nadir Belhadj"              "Antar Yahia"
[539] "Yazid Mansouri"             "Rafik Sa<U+00EF>fi"
[541] "Habib Bella<U+00EF>d"       "Abdelkader La<U+00EF>faoui"
[543] "Karim Ziani"                "Faouzi Chaouchi"
[545] "Adl<U+00E8>ne Guedioura"    "Diego Pozo"
[547] "Clemente Rodr<U+00ED>guez"  "Mario Bolatti"
[549] "Gabriel Heinze"             "Juan Sebasti<U+00E1>n Ver<U+00F3>n"
[551] "Ariel Garc<U+00E9>"         "Mart<U+00ED>n Palermo"
[553] "Lucas Neill"                "Jason Culina"
[555] "Michael Beauchamp"          "Brett Emerton"
[557] "Joshua Kennedy"             "Harry Kewell"
[559] "Scott Chipperfield"         "Vince Grella"
[561] "Richard Garcia"             "David Carney"
[563] "not applicable L<U+00FA>cio" "not applicable Juan"
[565] "not applicable Elano"       "Gilberto Silva"
[567] "Lu<U+00ED>s Fabiano"        "not applicable Kak<U+00E1>"
[569] "not applicable Robinho"     "not applicable Luis<U+00E3>o"
[571] "not applicable Gilberto"    "not applicable Josu<U+00E9>"
[573] "not applicable Kl<U+00E9>berson" "not applicable Nilmar"
[575] "not applicable Doni"        "not applicable Grafite"
[577] "Rigobert Song"              "not applicable Geremi"
[579] "Achille Eman<U+00E1>"       "Souleymanou Hamidou"
[581] "Mohammadou Idrissou"        "Guy N'dy Assemb<U+00E9>"
[583] "Ismael Fuentes"             "Waldo Ponce"
[585] "Humberto Suazo"             "Miguel Pinto"
[587] "Gonzalo Fierro"             "Rodrigo Millar"
[589] "Luis Mar<U+00ED>n"          "Thomas S<U+00F8>rensen"
[591] "Jesper Gr<U+00F8>nkj<U+00E6>r" "Jon Dahl Tomasson"
[593] "Martin J<U+00F8>rgensen"    "Per Kr<U+00F8>ldrup"
[595] "S<U+00F8>ren Larsen"        "David James"
[597] "Robert Green"               "Stephen Warnock"
[599] "Ledley King"                "Emile Heskey"
[601] "Eric Abidal"                "Thierry Henry"
[603] "Arne Friedrich"             "not applicable Cacau"
[605] "Hans-J<U+00F6>rg Butt"      "Daniel Agyei"
[607] "Hans Sarpei"                "John Paintsil"
[609] "Stephen Appiah"             "Prince Tagoe"
[611] "Isaac Vorsah"               "Stephen Ahorlu"
[613] "Lee Addy"                   "Richard Kingson"
[615] "Kostas Chalkias"            "Giourkas Seitaridis"
[617] "Nikos Spyropoulos"          "Angelos Charisteas"
[619] "Sotirios Kyrgiakos"         "Sakis Prittas"
[621] "Ricardo Canales"            "Johnny Palacios"
[623] "Hendry Thomas"              "Ram<U+00F3>n N<U+00FA><U+00F1>ez"
[625] "Carlos Pav<U+00F3>n"        "David Suazo"
[627] "Georgie Welcome"            "Walter Mart<U+00ED>nez"
[629] "Mauricio Sabill<U+00F3>n"   "<U+00C9>dgar <U+00C1>lvarez"
[631] "Danilo Turcios"             "Amado Guevara"
[633] "Sergio Mendoza"             "Fabio Cannavaro"
[635] "Gennaro Gattuso"            "Mauro Camoranesi"
[637] "Gianluca Zambrotta"         "not applicable Romaric"
[639] "Aruna Dindane"              "Aristide Zogbo"
[641] "Abdul Kader Ke<U+00EF>ta"   "Daniel Yeboah"
[643] "Seigo Narazaki"             "Yuki Abe"
[645] "Y<U+016B>ichi Komano"       "Marcus Tulio Tanaka"
[647] "Daisuke Matsui"             "Shunsuke Nakamura"
[649] "Keiji Tamada"               "Kisho Yano"
[651] "Daiki Iwamasa"              "Kengo Nakamura"
[653] "Junichi Inamoto"            "Yuji Nakazawa"
[655] "Yoshikatsu Kawaguchi"       "<U+00D3>scar P<U+00E9>rez"
[657] "Ricardo Osorio"             "Gerardo Torrado"
[659] "Israel Castro"              "Guillermo Franco"
[661] "Cuauht<U+00E9>moc Blanco"   "Efra<U+00ED>n Ju<U+00E1>rez"
[663] "Jonny Magall<U+00F3>n"      "Jorge Torres Nilo"
[665] "Adolfo Bautista"            "Alberto Medina"
[667] "Luis Ernesto Michel"        "John Heitinga"
[669] "Giovanni van Bronckhorst"   "Andr<U+00E9> Ooijer"
[671] "Mark Paston"                "Ben Sigmund"
[673] "Tony Lochhead"              "Ivan Vicelich"
[675] "Simon Elliott"              "Tim Brown"
[677] "Shane Smeltz"               "Chris Killen"
[679] "Leo Bertos"                 "Glen Moss"
[681] "Andy Barron"                "Michael McGlinchey"
[683] "Aaron Clapham"              "Dave Mulligan"
[685] "Andrew Boyens"              "Jeremy Christie"
[687] "Jeremy Brockie"             "James Bannatyne"
[689] "Nwankwo Kanu"               "Danny Shittu"
[691] "not applicable Yakubu"      "Sani Kaita"
[693] "Chidi Odiah"                "Dickson Etuhu"
[695] "Dele Aiyenugba"             "Myong-guk Ri"
[697] "Jong-hyok Cha"              "Jun-il Ri"
[699] "Nam-chol Pak"               "Kwang-chon Ri"

We can see a very significant amount of players have mismatched names.

In [8]:
set.seed(2026)

player_names %>%
    slice_sample(n = 20) %>%
        select(name)

   name
1  Volodymyr Bilotserkovets
2  Sam Lidington
3  Riccardo Montolivo
4  Dimitri Legbo
5  Luis Ortiz
6  Roman Khodunov
7  Morten Rasmussen
8  Colin McMenamin
9  Afonso Sousa
10 Konstantin Rausch
11 Andrigo
12 Callum Wilson
13 Du Queiroz
14 Steven Verheyen
15 Fary Faye
16 Mat<U+00ED>as Sep<U+00FA>lveda
17 Emam Ashour
18 Arian Kastrati
19 Artem Bondarenko
20 David Bicik

After manually inspecting I see some players are just spelled slightly differently in one dataset vs the other. For example Antar/Anthar Yahiya. Let's trouble shoot other issues first since this might require a lot of manual comparison which will be easier to do with less observations.

In [9]:
player_names %>%
  filter(grepl("Anthar Yahia", name)) %>%
    select(name)

worldcup_players %>%
  filter(grepl("Antar Yahia", full_name)) %>%
    select(full_name)

  name
1 Anthar Yahia

  full_name
1 Antar Yahia

Some of the player names also differ in the datasets because of accents. For example Ronald Araujo.

In [10]:
player_names %>%
  filter(grepl("Ronald Araujo", name)) %>%
    select(name)

worldcup_players %>%
  filter(grepl("Ronald Ara", full_name)) %>%
    select(full_name)

  name
1 Ronald Araujo

  full_name
1 Ronald Ara<U+00FA>jo

The accents seem to be a relevant issue across a lot of players. Let's write a function to normalize all text by removing accents. Also making sure to decode all text in the process.

In [11]:
# This was done with significant help from Codex AI
decode_unicode_tags <- function(x) {
  fix_one <- function(s) {
    matches <- regmatches(
      s,
      gregexpr("<U\\+[0-9A-Fa-f]{4,6}>", s, perl = TRUE)
    )[[1]]

    if (length(matches) == 1 && matches[1] == "") return(s)

    for (m in matches) {
      hex <- sub("<U\\+([0-9A-Fa-f]{4,6})>", "\\1", m, perl = TRUE)
      replacement <- intToUtf8(strtoi(hex, base = 16))
      s <- sub(m, replacement, s, fixed = TRUE)
    }

    s
  }

  vapply(x, fix_one, character(1))
}

remove_accents <- function(x) {
  x <- decode_unicode_tags(x)
  x <- enc2utf8(x)
  stringi::stri_trans_general(x, "Latin-ASCII")
}

#Test
remove_accents("Ronald Araújo")
remove_accents("Ángel Di María")
remove_accents("Cristiano Ronaldo")

[1] "Ronald Araujo"

[1] "Angel Di Maria"

[1] "Cristiano Ronaldo"

Seems to work pretty well, lets apply it to both of our datasets and then compare again

In [12]:
player_names <- player_names %>%
    mutate(name = remove_accents(name))

worldcup_players <- worldcup_players %>%
    mutate(full_name = remove_accents(full_name))

length(setdiff(worldcup_players$full_name, player_names$name))
length(worldcup_players$full_name)
setdiff(worldcup_players$full_name, player_names$name)

[1] 691

[1] 2379

  [1] "Bailey Wright"              "Cameron Devlin"
  [3] "not applicable Alisson"     "not applicable Danilo"
  [5] "not applicable Marquinhos"  "not applicable Casemiro"
  [7] "not applicable Fred"        "not applicable Richarlison"
  [9] "not applicable Neymar"      "not applicable Raphinha"
 [11] "not applicable Weverton"    "not applicable Fabinho"
 [13] "not applicable Antony"      "not applicable Rodrygo"
 [15] "not applicable Ederson"     "not applicable Bremer"
 [17] "not applicable Pedro"       "Jerome Ngom Mbekeli"
 [19] "Nicolas Nkoulou"            "Moumi Ngamaleu"
 [21] "Georges-Kevin Nkoudou"      "Andre-Frank Zambo Anguissa"
 [23] "Eric Maxim Choupo-Moting"   "Samuel Gouet"
 [25] "Nouhou Tolo"                "Souaibou Marou"
 [27] "Liam Fraser"                "Lucas Cavallini"
 [29] "Daniel Chacon"              "Keysher Fuller"
 [31] "Johan Venegas"              "Gerson Torres"
 [33] "Douglas Lopez"              "Jens Stryger Larsen"
 [35] "William Pacho"              "Romario Ibarra"
 [37] "Michael Estrada"            "Xavier Arreaga"
 [39] "Sebas Mendez"               "Alexander Dominguez"
 [41] "Djorkaeff Reasco"           "Lawrence Ati-Zigi"
 [43] "Abdul Fatawu Issahaku"      "Ibrahim Danlad"
 [45] "Abdul Manaf Nurudeen"       "Baba Rahman"
 [47] "Shojae Khalilzadeh"         "Hossein Kanaanizadegan"
 [49] "Rouzbeh Cheshmi"            "Mehdi Torabi"
 [51] "Ahmad Nourollahi"           "Hossein Hosseini"
 [53] "Abolfazl Jalali"            "Alfredo Talavera"
 [55] "Munir Mohamedi"             "Ilias Chair"
 [57] "Ahmed Reda Tagnaouti"       "Bilal El Khannous"
 [59] "Badr Benoun"                "Yahya Jabrane"
 [61] "not applicable Pepe"        "not applicable Vitinha"
 [63] "not applicable Otavio"      "Saad Al-Sheeb"
 [65] "not applicable Ro-Ro"       "Abdulaziz Hatem"
 [67] "Ali Assadalla"              "Hassan Al-Haydos"
 [69] "Musab Kheder"               "Homam Ahmed"
 [71] "Ismaeel Mohammad"           "Khalid Muneer"
 [73] "Salem Al-Hajri"             "Yousef Hassan"
 [75] "Naif Al-Hadhrami"           "Mostafa Meshaal"
 [77] "Mohammed Al-Rubaie"         "Ali Al-Bulaihi"
 [79] "Mohammed Al-Breik"          "Abdulellah Al-Malki"
 [81] "Hassan Al-Tambakti"         "Abdulrahman Al-Aboud"
 [83] "Moussa N'Diaye"             "Moustapha Name"
 [85] "Srdan Babic"                "Filip Duricic"
 [87] "Yoon Jong-gyu"              "Kim Jin-su"
 [89] "Kim Min-jae"                "Hwang In-beom"
 [91] "Paik Seung-ho"              "Cho Gue-sung"
 [93] "Song Bum-keun"              "Son Jun-ho"
 [95] "Kim Moon-hwan"              "Hwang Ui-jo"
 [97] "Na Sang-ho"                 "Lee Kang-in"
 [99] "Kwon Kyung-won"             "Kwon Chang-hoon"
[101] "Kim Tae-hwan"               "Cho Yu-min"
[103] "Jeong Woo-yeong"            "Song Min-kyu"
[105] "not applicable Koke"        "not applicable Gavi"
[107] "not applicable Rodri"       "Dani Carvajal"
[109] "not applicable Pedri"       "Aymen Mathlouthi"
[111] "Bilel Ifa"                  "Hannibal Mejbri"
[113] "Taha Yassine Khenissi"      "Ali Maaloul"
[115] "Mohamed Ali Ben Romdhane"   "Ghailene Chaalali"
[117] "Seifeddine Jaziri"          "Anis Ben Slimane"
[119] "Jose Gimenez"               "Giorgian De Arrascaeta"
[121] "Sebastian Sosa"             "Joe Morrell"
[123] "Jonny Williams"             "James Meredith"
[125] "Tim Cahill"                 "Dimitri Petratos"
[127] "not applicable Miranda"     "not applicable Marcelo"
[129] "not applicable Paulinho"    "not applicable Cassio"
[131] "not applicable Fernandinho" "not applicable Willian"
[133] "not applicable Taison"      "not applicable Fagner"
[135] "Oscar Murillo"              "Mateus Uribe"
[137] "Farid Diaz"                 "Jose Fernando Cuadrado"
[139] "Jhonny Acosta"              "Daniel Colindres"
[141] "Patrick Pemberton"          "David Guzman"
[143] "Marco Urena"                "Kenner Gutierrez"
[145] "Leonel Moreira"             "Essam El Hadary"
[147] "Omar Gaber"                 "Ahmed Hegazi"
[149] "Ahmed Fathy"                "not applicable Kahraba"
[151] "Ayman Ashraf"               "Mohamed Abdel Shafy"
[153] "Mahmoud Hamdy"              "Sherif Ekramy"
[155] "not applicable Shikabala"   "Abdallah El Said"
[157] "Saad Samir"                 "not applicable Trezeguet"
[159] "Hannes THor Halldorsson"    "Birkir Mar Saevarsson"
[161] "Bjorn Bergmann Sigurdarson" "Holmar Orn Eyjolfsson"
[163] "Hordur Bjorgvin Magnusson"  "Jon Dadi Bodvarsson"
[165] "Mohammad Rashid Mazaheri"   "Mohammad Reza Khanzadeh"
[167] "Pejman Montazeri"           "Tomoaki Makino"
[169] "Jose de Jesus Corona"       "Hugo Ayala"
[171] "Rafael Marquez"             "Javier Hernandez"
[173] "Jesus Manuel Corona"        "Oribe Peralta"
[175] "Mbark Boussoufa"            "Aziz Bouhaddouz"
[177] "Mehdi Carcela"              "Ikechukwu Ezenwa"
[179] "Brian Idowu"                "Elderson Echiejile"
[181] "John Obi Mikel"             "Shehu Abdullahi"
[183] "Simeon Nwankwo"             "Daniel Akpeyi"
[185] "Jaime Penedo"               "Michael Amir Murillo"
[187] "Harold Cummings"            "Gabriel Gomez"
[189] "Blas Perez"                 "Edgar Barcenas"
[191] "Gabriel Torres"             "Armando Cooper"
[193] "Adolfo Machado"             "Valentin Pimentel"
[195] "Erick Davis"                "Luis Ovalle"
[197] "Luis Tejada"                "Ricardo Avila"
[199] "Felipe Baloy"               "Aldo Corzo"
[201] "Raul Ruidiaz"               "Christian Ramos"
[203] "Jose Carvallo"              "Nilson Loyola"
[205] "Bartosz Bialkowski"         "not applicable Cedric"
[207] "not applicable Beto"        "Sergei Ignashevich"
[209] "Andrei Semyonov"            "Daler Kuzyayev"
[211] "Yury Gazinsky"              "Fyodor Smolov"
[213] "Andrey Lunyov"              "Fyodor Kudryashov"
[215] "Aleksei Miranchuk"          "Yuri Zhirkov"
[217] "Aleksandr Yerokhin"         "Mansoor Al-Harbi"
[219] "Omar Hawsawi"               "Mohammad Al-Sahlawi"
[221] "Abdulmalek Al-Khaibri"      "Housain Al-Mogahwi"
[223] "Taisir Al-Jassim"           "Muhannad Assiri"
[225] "Yasser Al-Mosailem"         "Motaz Hawsawi"
[227] "Kara Mbodji"                "Mame Biram Diouf"
[229] "Khadim N'Diaye"             "Ban-suk Oh"
[231] "Young-sun Yun"              "Joo-ho Park"
[233] "Shin-wook Kim"              "Hyun-soo Jang"
[235] "Yo-han Go"                  "not applicable Nacho"
[237] "not applicable Saul"        "not applicable Rodrigo"
[239] "not applicable Thiago"      "not applicable Isco"
[241] "Farouk Ben Mustapha"        "Rami Bedoui"
[243] "Mohamed Amine Ben Amor"     "Ahmed Khalil"
[245] "Hamdi Nagguez"              "Martin Campana"
[247] "Maxi Pereira"               "Martin Silva"
[249] "Cedric Si Mohamed"          "Madjid Bougherra"
[251] "Hillal Soudani"             "Mohamed Zemmamouche"
[253] "Liassine Cadamuro-Bentaiba" "Abdelmoumene Djabou"
[255] "Maxi Rodriguez"             "Agustin Orion"
[257] "Ricky Alvarez"              "Matthew Spiranovic"
[259] "James Holland"              "Matt McKay"
[261] "Eugene Galekovic"           "Dario Vidosic"
[263] "Alex Wilkinson"             "Mark Bresciano"
[265] "Jasmin Fejzic"              "Asmir Avdukic"
[267] "not applicable Jefferson"   "not applicable Hulk"
[269] "not applicable Oscar"       "not applicable Dante"
[271] "not applicable Maxwell"     "not applicable Henrique"
[273] "not applicable Ramires"     "not applicable Hernanes"
[275] "not applicable Bernard"     "not applicable Jo"
[277] "not applicable Victor"      "not applicable Maicon"
[279] "Loic Feudjou"               "Cedric Djeugoue"
[281] "Eugenio Mena"               "Jorge Valdivia"
[283] "Cristopher Toselli"         "Jose Manuel Rojas"
[285] "Jose Pablo Fuenzalida"      "Esteban Paredes"
[287] "Johnny Herrera"             "Alexander Mejia"
[289] "Eder Alvarez Balanta"       "Juan Camilo Zuniga"
[291] "Faryd Mondragon"            "Carlos Valdes"
[293] "Michael Umana"              "David Myrie"
[295] "Michael Barrantes"          "Waylon Francis"
[297] "Oscar Granados"             "Randall Brenes"
[299] "Roy Miller"                 "Diego Calvo"
[301] "Jose Miguel Cubero"         "Daniel Cambronero"
[303] "not applicable Sammir"      "not applicable Eduardo"
[305] "Maximo Banguera"            "Jorge Guagua"
[307] "Frickson Erazo"             "Edison Mendez"
[309] "Joao Rojas"                 "Walter Ayovi"
[311] "Adrian Bone"                "Oswaldo Minda"
[313] "Michael Arroyo"             "Jaime Ayovi"
[315] "Oscar Bagui"                "Luis Saritama"
[317] "Fidel Martinez"             "Gabriel Achilier"
[319] "Stephen Adams"              "Emmanuel Agyemang-Badu"
[321] "Adam Larsen Kwarasey"       "Rashid Sumaila"
[323] "Fatau Dauda"                "Abdul Majeed Waris"
[325] "Harrison Afful"             "Giorgos Tzavellas"
[327] "Kostas Manolas"             "Kostas Mitroglou"
[329] "Giorgos Karagounis"         "Dimitris Salpingidis"
[331] "Vasilis Torosidis"          "Jose Holebas"
[333] "Kostas Katsouranis"         "Osman Chavez"
[335] "Juan Pablo Montes"          "Victor Bernardez"
[337] "Juan Carlos Garcia"         "Jerry Palacios"
[339] "Jerry Bengtson"             "Edder Delgado"
[341] "Boniek Garcia"              "Rony Martinez"
[343] "Noel Valladares"            "Luis Garrido"
[345] "Donis Escober"              "Marvin Chavez"
[347] "Rahman Ahmadi"              "Khosro Heydari"
[349] "Jalal Hosseini"             "Amir Hossein Sadeghi"
[351] "Javad Nekounam"             "Reza Haghighi"
[353] "Ghasem Haddadifar"          "Hossein Mahini"
[355] "Andranik Teymourian"        "Ahmad Alenemeh"
[357] "Bakhtiar Rahmani"           "Hashem Beikzadeh"
[359] "Steven Beitashour"          "Mehrdad Pooladi"
[361] "Boubacar Barry"             "Cheick Tiote"
[363] "not applicable Gervinho"    "Sylvain Gbohouo"
[365] "Serey Die"                  "Sayouba Mande"
[367] "Yasuhito Endo"              "Yoichiro Kakitani"
[369] "Yoshito Okubo"              "Yasuyuki Konno"
[371] "Masahiko Inoha"             "Manabu Saito"
[373] "Francisco Javier Rodriguez" "Carlos Salcido"
[375] "Miguel Angel Ponce"         "Isaac Brizuela"
[377] "Paul Aguilar"               "Jose Juan Vazquez"
[379] "Azubuike Egwuekwe"          "Kunle Odunlami"
[381] "Austin Ejide"               "Michael Babatunde"
[383] "Chigozie Agbim"             "not applicable Vieirinha"
[385] "not applicable Eder"        "not applicable Nani"
[387] "Aleksei Kozlov"             "Georgi Shchennikov"
[389] "Yuri Lodygin"               "Vasili Berezutski"
[391] "Viktor Fayzulin"            "Aleksei Ionov"
[393] "Andrey Yeshchenko"          "Dmitri Kombarov"
[395] "Chang-soo Kim"              "Suk-young Yun"
[397] "Tae-hwi Kwak"               "Dae-sung Ha"
[399] "Keun-ho Lee"                "Kook-young Han"
[401] "Jong-woo Park"              "Bum-young Lee"
[403] "not applicable Juanfran"    "not applicable Xavi"
[405] "Matt Besler"                "DaMarcus Beasley"
[407] "Brad Davis"                 "Kyle Beckerman"
[409] "Chris Wondolowski"          "Graham Zusi"
[411] "Nick Rimando"               "Diego Forlan"
[413] "Rodrigo Munoz"              "Lounes Gaouaoui"
[415] "Nadir Belhadj"              "Antar Yahia"
[417] "Yazid Mansouri"             "Rafik Saifi"
[419] "Habib Bellaid"              "Abdelkader Laifaoui"
[421] "Karim Ziani"                "Faouzi Chaouchi"
[423] "Diego Pozo"                 "Clemente Rodriguez"
[425] "Mario Bolatti"              "Gabriel Heinze"
[427] "Juan Sebastian Veron"       "Ariel Garce"
[429] "Martin Palermo"             "Lucas Neill"
[431] "Jason Culina"               "Michael Beauchamp"
[433] "Brett Emerton"              "Joshua Kennedy"
[435] "Harry Kewell"               "Scott Chipperfield"
[437] "Vince Grella"               "Richard Garcia"
[439] "David Carney"               "not applicable Lucio"
[441] "not applicable Juan"        "not applicable Elano"
[443] "Gilberto Silva"             "Luis Fabiano"
[445] "not applicable Kaka"        "not applicable Robinho"
[447] "not applicable Luisao"      "not applicable Gilberto"
[449] "not applicable Josue"       "not applicable Kleberson"
[451] "not applicable Nilmar"      "not applicable Doni"
[453] "not applicable Grafite"     "Rigobert Song"
[455] "not applicable Geremi"      "Achille Emana"
[457] "Souleymanou Hamidou"        "Mohammadou Idrissou"
[459] "Guy N'dy Assembe"           "Ismael Fuentes"
[461] "Waldo Ponce"                "Humberto Suazo"
[463] "Miguel Pinto"               "Gonzalo Fierro"
[465] "Rodrigo Millar"             "Luis Marin"
[467] "Jesper Gronkjaer"           "Jon Dahl Tomasson"
[469] "David James"                "Robert Green"
[471] "Stephen Warnock"            "Ledley King"
[473] "Emile Heskey"               "Thierry Henry"
[475] "Arne Friedrich"             "not applicable Cacau"
[477] "Hans-Jorg Butt"             "Daniel Agyei"
[479] "Hans Sarpei"                "John Paintsil"
[481] "Stephen Appiah"             "Prince Tagoe"
[483] "Isaac Vorsah"               "Stephen Ahorlu"
[485] "Lee Addy"                   "Richard Kingson"
[487] "Kostas Chalkias"            "Giourkas Seitaridis"
[489] "Nikos Spyropoulos"          "Angelos Charisteas"
[491] "Sotirios Kyrgiakos"         "Sakis Prittas"
[493] "Ricardo Canales"            "Johnny Palacios"
[495] "Hendry Thomas"              "Ramon Nunez"
[497] "Carlos Pavon"               "David Suazo"
[499] "Georgie Welcome"            "Walter Martinez"
[501] "Mauricio Sabillon"          "Edgar Alvarez"
[503] "Danilo Turcios"             "Amado Guevara"
[505] "Sergio Mendoza"             "Fabio Cannavaro"
[507] "Gennaro Gattuso"            "Mauro Camoranesi"
[509] "Gianluca Zambrotta"         "not applicable Romaric"
[511] "Aruna Dindane"              "Aristide Zogbo"
[513] "Abdul Kader Keita"          "Daniel Yeboah"
[515] "Seigo Narazaki"             "Yuki Abe"
[517] "Yuichi Komano"              "Marcus Tulio Tanaka"
[519] "Daisuke Matsui"             "Shunsuke Nakamura"
[521] "Keiji Tamada"               "Kisho Yano"
[523] "Daiki Iwamasa"              "Kengo Nakamura"
[525] "Junichi Inamoto"            "Yuji Nakazawa"
[527] "Yoshikatsu Kawaguchi"       "Oscar Perez"
[529] "Ricardo Osorio"             "Gerardo Torrado"
[531] "Israel Castro"              "Guillermo Franco"
[533] "Cuauhtemoc Blanco"          "Efrain Juarez"
[535] "Jonny Magallon"             "Jorge Torres Nilo"
[537] "Adolfo Bautista"            "Alberto Medina"
[539] "Luis Ernesto Michel"        "John Heitinga"
[541] "Giovanni van Bronckhorst"   "Andre Ooijer"
[543] "Mark Paston"                "Ben Sigmund"
[545] "Tony Lochhead"              "Ivan Vicelich"
[547] "Simon Elliott"              "Tim Brown"
[549] "Shane Smeltz"               "Chris Killen"
[551] "Leo Bertos"                 "Glen Moss"
[553] "Andy Barron"                "Michael McGlinchey"
[555] "Aaron Clapham"              "Dave Mulligan"
[557] "Andrew Boyens"              "Jeremy Christie"
[559] "Jeremy Brockie"             "James Bannatyne"
[561] "Nwankwo Kanu"               "Danny Shittu"
[563] "not applicable Yakubu"      "Sani Kaita"
[565] "Chidi Odiah"                "Dickson Etuhu"
[567] "Dele Aiyenugba"             "Myong-guk Ri"
[569] "Jong-hyok Cha"              "Jun-il Ri"
[571] "Nam-chol Pak"               "Kwang-chon Ri"
[573] "Kum-il Kim"                 "Chol-hyok An"
[575] "Yun-nam Ji"                 "Tae-se Jong"
[577] "Yong-jo Hong"               "In-guk Mun"
[579] "Kum-chol Choe"              "Chol-jin Pak"
[581] "Nam-Chol Pak"               "Yong-jun Kim"
[583] "Song-chol Nam"              "Yong-hak An"
[585] "Myong-gil Kim"              "Chol-myong Ri"
[587] "Myong-won Kim"              "Kwang-hyok Ri"
[589] "Kyong-il Kim"               "Il-gwan Jong"
[591] "Justo Villar"               "Dario Veron"
[593] "Claudio Morel"              "Denis Caniza"
[595] "Julio Cesar Caceres"        "Carlos Bonet"
[597] "Edgar Benitez"              "Jonathan Santana"
[599] "Diego Barreto"              "Enrique Vera"
[601] "Paulo da Silva"             "Victor Caceres"
[603] "Aureliano Torres"           "Nestor Ortigoza"
[605] "Aldo Bobadilla"             "Rodolfo Gamarra"
[607] "not applicable Rolando"     "not applicable Duda"
[609] "not applicable Liedson"     "not applicable Danny"
[611] "not applicable Simao"       "not applicable Miguel"
[613] "not applicable Tiago"       "not applicable Deco"
[615] "Nemanja Vidic"              "Nenad Milijas"
[617] "Bojan Isailovic"            "Nikola Zigic"
[619] "Dragan Mrda"                "Andelko Duricic"
[621] "Zdeno Strba"                "Jan Kozak"
[623] "Kamil Kopunek"              "Martin Petras"
[625] "Marko Suler"                "Nejc Pecnik"
[627] "Zlatan Ljubijankic"         "Milivoje Novakovic"
[629] "Jasmin Handanovic"          "Zlatko Dedic"
[631] "Aleksander Seliga"          "Suad Filekovic"
[633] "Andrej Komac"               "Matej Mavric"
[635] "Moeneeb Josephs"            "Siboniso Gaxa"
[637] "Tsepo Masilela"             "Aaron Mokoena"
[639] "MacBeth Sibaya"             "Katlego Mphela"
[641] "Teko Modise"                "Reneilwe Letsholonyane"
[643] "Matthew Booth"              "Lucas Thwala"
[645] "Itumeleng Khune"            "Bernard Parker"
[647] "Siyabonga Nomvethe"         "Surprise Moriri"
[649] "Siyabonga Sangweni"         "Shu-Aib Walters"
[651] "Thanduyise Khuboni"         "Woon-jae Lee"
[653] "Beom-seok Oh"               "Hyung-il Kim"
[655] "Yong-hyung Cho"             "Nam-il Kim"
[657] "Jung-woo Kim"               "Jung-hwan Ahn"
[659] "Seung-yeoul Lee"            "Young-pyo Lee"
[661] "Jung-soo Lee"               "Ki-hun Yeom"
[663] "Dong-gook Lee"              "Young-kwang Kim"
[665] "Min-soo Kang"               "Ludovic Magnin"
[667] "Benjamin Huggel"            "Alexander Frei"
[669] "Blaise Nkufo"               "Marco Wolfli"
[671] "Stephane Grichting"         "Marco Padalino"
[673] "Hakan Yakin"                "Albert Bunjaku"
[675] "Carlos Bocanegra"           "Steve Cherundolo"
[677] "Herculez Gomez"             "Landon Donovan"
[679] "Stuart Holden"              "Jonathan Bornstein"
[681] "Ricardo Clark"              "Edson Buddle"
[683] "Jay DeMerit"                "Jose Francisco Torres"
[685] "Robbie Findley"             "Benny Feilhaber"
[687] "Marcus Hahnemann"           "Mauricio Victorino"
[689] "Sebastian Eguren"           "Sebastian Abreu"
[691] "Andres Scotti"

Our set difference went down 165 observations! Lets keep trouble shooting.

There seems to be a few players with "not applicable" as their first name. Let's explore this issue.

In [13]:
worldcup_players %>%
    filter(grepl("not applicable", full_name)) %>%
        print(n=5)

worldcup_players %>%
    filter(grepl("not applicable", full_name)) %>%
        distinct(full_name) %>%
            nrow()

# A tibble: 88 x 3
  player_id full_name                 tournament_id
  <chr>     <chr>                     <chr>
1 P-21531   not applicable Alisson    WC-2022
2 P-40137   not applicable Danilo     WC-2022
3 P-76060   not applicable Marquinhos WC-2022
4 P-02305   not applicable Casemiro   WC-2022
5 P-74941   not applicable Fred       WC-2022
# i 83 more rows

[1] 85

In [14]:
readRDS(here("1.DataCleaning-R", "Data", "RDS", "FullRoster.rds")) %>%
    filter(given_name== "not applicable") %>%
        print(n=10)

# A tibble: 113 x 9
   tournament_id team_name team_id team_code player_id family_name   given_name
   <chr>         <chr>     <chr>   <chr>     <chr>     <chr>         <chr>
 1 WC-2010       Brazil    T-09    BRA       P-94551   "Maicon"      not applic~
 2 WC-2010       Brazil    T-09    BRA       P-42918   "L\u00facio"  not applic~
 3 WC-2010       Brazil    T-09    BRA       P-98607   "Juan"        not applic~
 4 WC-2010       Brazil    T-09    BRA       P-78264   "Elano"       not applic~
 5 WC-2010       Brazil    T-09    BRA       P-58388   "Kak\u00e1"   not applic~
 6 WC-2010       Brazil    T-09    BRA       P-13354   "Robinho"     not applic~
 7 WC-2010       Brazil    T-09    BRA       P-32968   "Luis\u00e3o" not applic~
 8 WC-2010       Brazil    T-09    BRA       P-30363   "Gilberto"    not applic~
 9 WC-2010       Brazil    T-09    BRA       P-74066   "Josu\u00e9"  not applic~
10 WC-2010       Brazil    T-09    BRA       P-86499   "Ramires"     not applic~
# i 103 more rows
# i 2 more variables: position_code <chr>, full_name <chr>

In [15]:
#Let's check some of these players on the Kaggle dataset
set.seed(2026)

player_names %>% 
    select(name) %>%
        filter(grepl("Maicon|Elano", name)) %>%
            slice_sample(n=10)

  name
1 Elano Yegen
2 Maicon
3 Maicon Oliveira
4 Maicon
5 Maicon

Some of the players seem to be only reffered to by one name in both datasets. Lets take out the not applicable and see improvements.

In [16]:
remove_not_applicable <- function(x) {
  gsub("not applicable\\s+", "", x)
}

worldcup_players <- worldcup_players %>%
  mutate(full_name = remove_not_applicable(full_name))

length(setdiff(worldcup_players$full_name, player_names$name))
length(worldcup_players$full_name)
setdiff(worldcup_players$full_name, player_names$name)

[1] 617

[1] 2379

  [1] "Bailey Wright"              "Cameron Devlin"
  [3] "Jerome Ngom Mbekeli"        "Nicolas Nkoulou"
  [5] "Moumi Ngamaleu"             "Georges-Kevin Nkoudou"
  [7] "Andre-Frank Zambo Anguissa" "Eric Maxim Choupo-Moting"
  [9] "Samuel Gouet"               "Nouhou Tolo"
 [11] "Souaibou Marou"             "Liam Fraser"
 [13] "Lucas Cavallini"            "Daniel Chacon"
 [15] "Keysher Fuller"             "Johan Venegas"
 [17] "Gerson Torres"              "Douglas Lopez"
 [19] "Jens Stryger Larsen"        "William Pacho"
 [21] "Romario Ibarra"             "Michael Estrada"
 [23] "Xavier Arreaga"             "Sebas Mendez"
 [25] "Alexander Dominguez"        "Djorkaeff Reasco"
 [27] "Lawrence Ati-Zigi"          "Abdul Fatawu Issahaku"
 [29] "Ibrahim Danlad"             "Abdul Manaf Nurudeen"
 [31] "Baba Rahman"                "Shojae Khalilzadeh"
 [33] "Hossein Kanaanizadegan"     "Rouzbeh Cheshmi"
 [35] "Mehdi Torabi"               "Ahmad Nourollahi"
 [37] "Hossein Hosseini"           "Abolfazl Jalali"
 [39] "Alfredo Talavera"           "Munir Mohamedi"
 [41] "Ilias Chair"                "Ahmed Reda Tagnaouti"
 [43] "Bilal El Khannous"          "Badr Benoun"
 [45] "Yahya Jabrane"              "Saad Al-Sheeb"
 [47] "Ro-Ro"                      "Abdulaziz Hatem"
 [49] "Ali Assadalla"              "Hassan Al-Haydos"
 [51] "Musab Kheder"               "Homam Ahmed"
 [53] "Ismaeel Mohammad"           "Khalid Muneer"
 [55] "Salem Al-Hajri"             "Yousef Hassan"
 [57] "Naif Al-Hadhrami"           "Mostafa Meshaal"
 [59] "Mohammed Al-Rubaie"         "Ali Al-Bulaihi"
 [61] "Mohammed Al-Breik"          "Abdulellah Al-Malki"
 [63] "Hassan Al-Tambakti"         "Abdulrahman Al-Aboud"
 [65] "Moussa N'Diaye"             "Moustapha Name"
 [67] "Srdan Babic"                "Filip Duricic"
 [69] "Yoon Jong-gyu"              "Kim Jin-su"
 [71] "Kim Min-jae"                "Hwang In-beom"
 [73] "Paik Seung-ho"              "Cho Gue-sung"
 [75] "Song Bum-keun"              "Son Jun-ho"
 [77] "Kim Moon-hwan"              "Hwang Ui-jo"
 [79] "Na Sang-ho"                 "Lee Kang-in"
 [81] "Kwon Kyung-won"             "Kwon Chang-hoon"
 [83] "Kim Tae-hwan"               "Cho Yu-min"
 [85] "Jeong Woo-yeong"            "Song Min-kyu"
 [87] "Dani Carvajal"              "Aymen Mathlouthi"
 [89] "Bilel Ifa"                  "Hannibal Mejbri"
 [91] "Taha Yassine Khenissi"      "Ali Maaloul"
 [93] "Mohamed Ali Ben Romdhane"   "Ghailene Chaalali"
 [95] "Seifeddine Jaziri"          "Anis Ben Slimane"
 [97] "Jose Gimenez"               "Giorgian De Arrascaeta"
 [99] "Sebastian Sosa"             "Joe Morrell"
[101] "Jonny Williams"             "James Meredith"
[103] "Tim Cahill"                 "Dimitri Petratos"
[105] "Oscar Murillo"              "Mateus Uribe"
[107] "Farid Diaz"                 "Jose Fernando Cuadrado"
[109] "Jhonny Acosta"              "Daniel Colindres"
[111] "Patrick Pemberton"          "David Guzman"
[113] "Marco Urena"                "Kenner Gutierrez"
[115] "Leonel Moreira"             "Essam El Hadary"
[117] "Omar Gaber"                 "Ahmed Hegazi"
[119] "Ahmed Fathy"                "Ayman Ashraf"
[121] "Mohamed Abdel Shafy"        "Mahmoud Hamdy"
[123] "Sherif Ekramy"              "Abdallah El Said"
[125] "Saad Samir"                 "Hannes THor Halldorsson"
[127] "Birkir Mar Saevarsson"      "Bjorn Bergmann Sigurdarson"
[129] "Holmar Orn Eyjolfsson"      "Hordur Bjorgvin Magnusson"
[131] "Jon Dadi Bodvarsson"        "Mohammad Rashid Mazaheri"
[133] "Mohammad Reza Khanzadeh"    "Pejman Montazeri"
[135] "Tomoaki Makino"             "Jose de Jesus Corona"
[137] "Hugo Ayala"                 "Rafael Marquez"
[139] "Javier Hernandez"           "Jesus Manuel Corona"
[141] "Oribe Peralta"              "Mbark Boussoufa"
[143] "Aziz Bouhaddouz"            "Mehdi Carcela"
[145] "Ikechukwu Ezenwa"           "Brian Idowu"
[147] "Elderson Echiejile"         "John Obi Mikel"
[149] "Shehu Abdullahi"            "Simeon Nwankwo"
[151] "Daniel Akpeyi"              "Jaime Penedo"
[153] "Michael Amir Murillo"       "Harold Cummings"
[155] "Gabriel Gomez"              "Blas Perez"
[157] "Edgar Barcenas"             "Gabriel Torres"
[159] "Armando Cooper"             "Adolfo Machado"
[161] "Valentin Pimentel"          "Erick Davis"
[163] "Luis Ovalle"                "Luis Tejada"
[165] "Ricardo Avila"              "Felipe Baloy"
[167] "Aldo Corzo"                 "Raul Ruidiaz"
[169] "Christian Ramos"            "Jose Carvallo"
[171] "Nilson Loyola"              "Bartosz Bialkowski"
[173] "Cedric"                     "Sergei Ignashevich"
[175] "Andrei Semyonov"            "Daler Kuzyayev"
[177] "Yury Gazinsky"              "Fyodor Smolov"
[179] "Andrey Lunyov"              "Fyodor Kudryashov"
[181] "Aleksei Miranchuk"          "Yuri Zhirkov"
[183] "Aleksandr Yerokhin"         "Mansoor Al-Harbi"
[185] "Omar Hawsawi"               "Mohammad Al-Sahlawi"
[187] "Abdulmalek Al-Khaibri"      "Housain Al-Mogahwi"
[189] "Taisir Al-Jassim"           "Muhannad Assiri"
[191] "Yasser Al-Mosailem"         "Motaz Hawsawi"
[193] "Kara Mbodji"                "Mame Biram Diouf"
[195] "Khadim N'Diaye"             "Ban-suk Oh"
[197] "Young-sun Yun"              "Joo-ho Park"
[199] "Shin-wook Kim"              "Hyun-soo Jang"
[201] "Yo-han Go"                  "Farouk Ben Mustapha"
[203] "Rami Bedoui"                "Mohamed Amine Ben Amor"
[205] "Ahmed Khalil"               "Hamdi Nagguez"
[207] "Martin Campana"             "Maxi Pereira"
[209] "Martin Silva"               "Cedric Si Mohamed"
[211] "Madjid Bougherra"           "Hillal Soudani"
[213] "Mohamed Zemmamouche"        "Liassine Cadamuro-Bentaiba"
[215] "Abdelmoumene Djabou"        "Maxi Rodriguez"
[217] "Agustin Orion"              "Ricky Alvarez"
[219] "Matthew Spiranovic"         "James Holland"
[221] "Matt McKay"                 "Eugene Galekovic"
[223] "Dario Vidosic"              "Alex Wilkinson"
[225] "Mark Bresciano"             "Jasmin Fejzic"
[227] "Asmir Avdukic"              "Loic Feudjou"
[229] "Cedric Djeugoue"            "Eugenio Mena"
[231] "Jorge Valdivia"             "Cristopher Toselli"
[233] "Jose Manuel Rojas"          "Jose Pablo Fuenzalida"
[235] "Esteban Paredes"            "Johnny Herrera"
[237] "Alexander Mejia"            "Eder Alvarez Balanta"
[239] "Juan Camilo Zuniga"         "Faryd Mondragon"
[241] "Carlos Valdes"              "Michael Umana"
[243] "David Myrie"                "Michael Barrantes"
[245] "Waylon Francis"             "Oscar Granados"
[247] "Randall Brenes"             "Roy Miller"
[249] "Diego Calvo"                "Jose Miguel Cubero"
[251] "Daniel Cambronero"          "Maximo Banguera"
[253] "Jorge Guagua"               "Frickson Erazo"
[255] "Edison Mendez"              "Joao Rojas"
[257] "Walter Ayovi"               "Adrian Bone"
[259] "Oswaldo Minda"              "Michael Arroyo"
[261] "Jaime Ayovi"                "Oscar Bagui"
[263] "Luis Saritama"              "Fidel Martinez"
[265] "Gabriel Achilier"           "Stephen Adams"
[267] "Emmanuel Agyemang-Badu"     "Adam Larsen Kwarasey"
[269] "Rashid Sumaila"             "Fatau Dauda"
[271] "Abdul Majeed Waris"         "Harrison Afful"
[273] "Giorgos Tzavellas"          "Kostas Manolas"
[275] "Kostas Mitroglou"           "Giorgos Karagounis"
[277] "Dimitris Salpingidis"       "Vasilis Torosidis"
[279] "Jose Holebas"               "Kostas Katsouranis"
[281] "Osman Chavez"               "Juan Pablo Montes"
[283] "Victor Bernardez"           "Juan Carlos Garcia"
[285] "Jerry Palacios"             "Jerry Bengtson"
[287] "Edder Delgado"              "Boniek Garcia"
[289] "Rony Martinez"              "Noel Valladares"
[291] "Luis Garrido"               "Donis Escober"
[293] "Marvin Chavez"              "Rahman Ahmadi"
[295] "Khosro Heydari"             "Jalal Hosseini"
[297] "Amir Hossein Sadeghi"       "Javad Nekounam"
[299] "Reza Haghighi"              "Ghasem Haddadifar"
[301] "Hossein Mahini"             "Andranik Teymourian"
[303] "Ahmad Alenemeh"             "Bakhtiar Rahmani"
[305] "Hashem Beikzadeh"           "Steven Beitashour"
[307] "Mehrdad Pooladi"            "Boubacar Barry"
[309] "Cheick Tiote"               "Sylvain Gbohouo"
[311] "Serey Die"                  "Sayouba Mande"
[313] "Yasuhito Endo"              "Yoichiro Kakitani"
[315] "Yoshito Okubo"              "Yasuyuki Konno"
[317] "Masahiko Inoha"             "Manabu Saito"
[319] "Francisco Javier Rodriguez" "Carlos Salcido"
[321] "Miguel Angel Ponce"         "Isaac Brizuela"
[323] "Paul Aguilar"               "Jose Juan Vazquez"
[325] "Azubuike Egwuekwe"          "Kunle Odunlami"
[327] "Austin Ejide"               "Michael Babatunde"
[329] "Chigozie Agbim"             "Aleksei Kozlov"
[331] "Georgi Shchennikov"         "Yuri Lodygin"
[333] "Vasili Berezutski"          "Viktor Fayzulin"
[335] "Aleksei Ionov"              "Andrey Yeshchenko"
[337] "Dmitri Kombarov"            "Chang-soo Kim"
[339] "Suk-young Yun"              "Tae-hwi Kwak"
[341] "Dae-sung Ha"                "Keun-ho Lee"
[343] "Kook-young Han"             "Jong-woo Park"
[345] "Bum-young Lee"              "Matt Besler"
[347] "DaMarcus Beasley"           "Brad Davis"
[349] "Kyle Beckerman"             "Chris Wondolowski"
[351] "Graham Zusi"                "Nick Rimando"
[353] "Diego Forlan"               "Rodrigo Munoz"
[355] "Lounes Gaouaoui"            "Nadir Belhadj"
[357] "Antar Yahia"                "Yazid Mansouri"
[359] "Rafik Saifi"                "Habib Bellaid"
[361] "Abdelkader Laifaoui"        "Karim Ziani"
[363] "Faouzi Chaouchi"            "Diego Pozo"
[365] "Clemente Rodriguez"         "Mario Bolatti"
[367] "Gabriel Heinze"             "Juan Sebastian Veron"
[369] "Ariel Garce"                "Martin Palermo"
[371] "Lucas Neill"                "Jason Culina"
[373] "Michael Beauchamp"          "Brett Emerton"
[375] "Joshua Kennedy"             "Harry Kewell"
[377] "Scott Chipperfield"         "Vince Grella"
[379] "Richard Garcia"             "David Carney"
[381] "Elano"                      "Gilberto Silva"
[383] "Luis Fabiano"               "Kleberson"
[385] "Nilmar"                     "Doni"
[387] "Grafite"                    "Rigobert Song"
[389] "Geremi"                     "Achille Emana"
[391] "Souleymanou Hamidou"        "Mohammadou Idrissou"
[393] "Guy N'dy Assembe"           "Ismael Fuentes"
[395] "Waldo Ponce"                "Humberto Suazo"
[397] "Miguel Pinto"               "Gonzalo Fierro"
[399] "Rodrigo Millar"             "Luis Marin"
[401] "Jesper Gronkjaer"           "Jon Dahl Tomasson"
[403] "David James"                "Robert Green"
[405] "Stephen Warnock"            "Ledley King"
[407] "Emile Heskey"               "Thierry Henry"
[409] "Arne Friedrich"             "Hans-Jorg Butt"
[411] "Daniel Agyei"               "Hans Sarpei"
[413] "John Paintsil"              "Stephen Appiah"
[415] "Prince Tagoe"               "Isaac Vorsah"
[417] "Stephen Ahorlu"             "Lee Addy"
[419] "Richard Kingson"            "Kostas Chalkias"
[421] "Giourkas Seitaridis"        "Nikos Spyropoulos"
[423] "Angelos Charisteas"         "Sotirios Kyrgiakos"
[425] "Sakis Prittas"              "Ricardo Canales"
[427] "Johnny Palacios"            "Hendry Thomas"
[429] "Ramon Nunez"                "Carlos Pavon"
[431] "David Suazo"                "Georgie Welcome"
[433] "Walter Martinez"            "Mauricio Sabillon"
[435] "Edgar Alvarez"              "Danilo Turcios"
[437] "Amado Guevara"              "Sergio Mendoza"
[439] "Fabio Cannavaro"            "Gennaro Gattuso"
[441] "Mauro Camoranesi"           "Gianluca Zambrotta"
[443] "Aruna Dindane"              "Aristide Zogbo"
[445] "Abdul Kader Keita"          "Daniel Yeboah"
[447] "Seigo Narazaki"             "Yuki Abe"
[449] "Yuichi Komano"              "Marcus Tulio Tanaka"
[451] "Daisuke Matsui"             "Shunsuke Nakamura"
[453] "Keiji Tamada"               "Kisho Yano"
[455] "Daiki Iwamasa"              "Kengo Nakamura"
[457] "Junichi Inamoto"            "Yuji Nakazawa"
[459] "Yoshikatsu Kawaguchi"       "Oscar Perez"
[461] "Ricardo Osorio"             "Gerardo Torrado"
[463] "Israel Castro"              "Guillermo Franco"
[465] "Cuauhtemoc Blanco"          "Efrain Juarez"
[467] "Jonny Magallon"             "Jorge Torres Nilo"
[469] "Adolfo Bautista"            "Alberto Medina"
[471] "Luis Ernesto Michel"        "John Heitinga"
[473] "Giovanni van Bronckhorst"   "Andre Ooijer"
[475] "Mark Paston"                "Ben Sigmund"
[477] "Tony Lochhead"              "Ivan Vicelich"
[479] "Simon Elliott"              "Tim Brown"
[481] "Shane Smeltz"               "Chris Killen"
[483] "Leo Bertos"                 "Glen Moss"
[485] "Andy Barron"                "Michael McGlinchey"
[487] "Aaron Clapham"              "Dave Mulligan"
[489] "Andrew Boyens"              "Jeremy Christie"
[491] "Jeremy Brockie"             "James Bannatyne"
[493] "Nwankwo Kanu"               "Danny Shittu"
[495] "Yakubu"                     "Sani Kaita"
[497] "Chidi Odiah"                "Dickson Etuhu"
[499] "Dele Aiyenugba"             "Myong-guk Ri"
[501] "Jong-hyok Cha"              "Jun-il Ri"
[503] "Nam-chol Pak"               "Kwang-chon Ri"
[505] "Kum-il Kim"                 "Chol-hyok An"
[507] "Yun-nam Ji"                 "Tae-se Jong"
[509] "Yong-jo Hong"               "In-guk Mun"
[511] "Kum-chol Choe"              "Chol-jin Pak"
[513] "Nam-Chol Pak"               "Yong-jun Kim"
[515] "Song-chol Nam"              "Yong-hak An"
[517] "Myong-gil Kim"              "Chol-myong Ri"
[519] "Myong-won Kim"              "Kwang-hyok Ri"
[521] "Kyong-il Kim"               "Il-gwan Jong"
[523] "Justo Villar"               "Dario Veron"
[525] "Claudio Morel"              "Denis Caniza"
[527] "Julio Cesar Caceres"        "Carlos Bonet"
[529] "Edgar Benitez"              "Jonathan Santana"
[531] "Diego Barreto"              "Enrique Vera"
[533] "Paulo da Silva"             "Victor Caceres"
[535] "Aureliano Torres"           "Nestor Ortigoza"
[537] "Aldo Bobadilla"             "Rodolfo Gamarra"
[539] "Miguel"                     "Deco"
[541] "Nemanja Vidic"              "Nenad Milijas"
[543] "Bojan Isailovic"            "Nikola Zigic"
[545] "Dragan Mrda"                "Andelko Duricic"
[547] "Zdeno Strba"                "Jan Kozak"
[549] "Kamil Kopunek"              "Martin Petras"
[551] "Marko Suler"                "Nejc Pecnik"
[553] "Zlatan Ljubijankic"         "Milivoje Novakovic"
[555] "Jasmin Handanovic"          "Zlatko Dedic"
[557] "Aleksander Seliga"          "Suad Filekovic"
[559] "Andrej Komac"               "Matej Mavric"
[561] "Moeneeb Josephs"            "Siboniso Gaxa"
[563] "Tsepo Masilela"             "Aaron Mokoena"
[565] "MacBeth Sibaya"             "Katlego Mphela"
[567] "Teko Modise"                "Reneilwe Letsholonyane"
[569] "Matthew Booth"              "Lucas Thwala"
[571] "Itumeleng Khune"            "Bernard Parker"
[573] "Siyabonga Nomvethe"         "Surprise Moriri"
[575] "Siyabonga Sangweni"         "Shu-Aib Walters"
[577] "Thanduyise Khuboni"         "Woon-jae Lee"
[579] "Beom-seok Oh"               "Hyung-il Kim"
[581] "Yong-hyung Cho"             "Nam-il Kim"
[583] "Jung-woo Kim"               "Jung-hwan Ahn"
[585] "Seung-yeoul Lee"            "Young-pyo Lee"
[587] "Jung-soo Lee"               "Ki-hun Yeom"
[589] "Dong-gook Lee"              "Young-kwang Kim"
[591] "Min-soo Kang"               "Ludovic Magnin"
[593] "Benjamin Huggel"            "Alexander Frei"
[595] "Blaise Nkufo"               "Marco Wolfli"
[597] "Stephane Grichting"         "Marco Padalino"
[599] "Hakan Yakin"                "Albert Bunjaku"
[601] "Carlos Bocanegra"           "Steve Cherundolo"
[603] "Herculez Gomez"             "Landon Donovan"
[605] "Stuart Holden"              "Jonathan Bornstein"
[607] "Ricardo Clark"              "Edson Buddle"
[609] "Jay DeMerit"                "Jose Francisco Torres"
[611] "Robbie Findley"             "Benny Feilhaber"
[613] "Marcus Hahnemann"           "Mauricio Victorino"
[615] "Sebastian Eguren"           "Sebastian Abreu"
[617] "Andres Scotti"

Great! 74 out of the 85 players with not applicable were solved with this issue. Lets asses the other 11. We can do this by checking all full names with no spaces in the sett differences list. If we have 11 then we know we got all of the not applicables we're missing.

In [17]:
unmatched_players <- setdiff(worldcup_players$full_name, player_names$name)

one_word_unmatched <- unmatched_players[!grepl("\\s", unmatched_players)]

length(one_word_unmatched)
one_word_unmatched

[1] 11

 [1] "Ro-Ro"     "Cedric"    "Elano"     "Kleberson" "Nilmar"    "Doni"
 [7] "Grafite"   "Geremi"    "Yakubu"    "Miguel"    "Deco"

In [18]:
player_data_clean <- player_data %>%
  mutate(clean_name = remove_not_applicable(remove_accents(name)))

pattern <- paste0("\\b(", paste(one_word_unmatched, collapse = "|"), ")\\b")

player_data_clean %>%
  filter(grepl(pattern, clean_name)) %>%
    filter(!(clean_name %in% worldcup_players$full_name)) %>%
      distinct(name, clean_name, last_season, international_caps) %>%
        filter(last_season>= 2010 & international_caps > 0)

   name                         clean_name            last_season
1  Miguel Lopes                 Miguel Lopes          2024
2  Miguel Lloyd                 Miguel Lloyd          2025
3  Luis Miguel Rodr<U+00ED>guez Luis Miguel Rodriguez 2024
4  C<U+00E9>dric Soares         Cedric Soares         2025
5  C<U+00E9>dric Bakambu        Cedric Bakambu        2025
6  C<U+00E9>dric Hountondji     Cedric Hountondji     2024
7  Cedric Teuchert              Cedric Teuchert       2025
8  Pedro Miguel                 Pedro Miguel          2025
9  Cedric Itten                 Cedric Itten          2025
10 Miguel Almir<U+00F3>n        Miguel Almiron        2025
11 Miguel Lu<U+00ED>s           Miguel Luis           2025
12 C<U+00E9>dric Kipr<U+00E9>   Cedric Kipre          2024
13 C<U+00E9>dric Zesiger        Cedric Zesiger        2025
14 Miguel N<U+00F3>brega        Miguel Nobrega        2025
15 Miguel Reisinho              Miguel Reisinho       2024
16 Miguel de la Fuente          Miguel de la Fuente   2024
17 Miguel Merentiel             Miguel Merentiel      2025
18 Miguel Navarro               Miguel Navarro        2025
19 Miguel Baeza                 Miguel Baeza          2025
20 Miguel Guti<U+00E9>rrez      Miguel Gutierrez      2025
21 Cedric Teguia                Cedric Teguia         2025
22 Miguel Reichmuth             Miguel Reichmuth      2025
23 Miguel <U+00C1>ngel Morro    Miguel Angel Morro    2024
24 Miguel Sandberg              Miguel Sandberg       2025
25 Miguel Rodr<U+00ED>guez      Miguel Rodriguez      2025
26 Miguel Silveira              Miguel Silveira       2024
27 Miguel Menino                Miguel Menino         2024
28 Miguel Monsalve              Miguel Monsalve       2025
29 Miguel G<U+00F3>mez          Miguel Gomez          2025
30 Miguel Ram<U+00ED>rez        Miguel Ramirez        2025
31 C<U+00E9>dric Nuozzi         Cedric Nuozzi         2025
32 Miguel Carvalho              Miguel Carvalho       2025
33 Miguel Chaiwa                Miguel Chaiwa         2025
34 Miguel Perez                 Miguel Perez          2025
35 Mardoch<U+00E9>e Miguel      Mardochee Miguel      2025
36 Miguel Di Pizio              Miguel Di Pizio       2025
37 Miguel <U+00C1>ngel Beltre   Miguel Angel Beltre   2025
38 Miguel Agamez                Miguel Agamez         2024
39 Miguel Marulanda             Miguel Marulanda      2025
   international_caps
1   4
2  47
3   1
4  34
5  67
6  29
7   8
8  99
9  13
10 75
11  6
12  1
13  6
14  2
15  1
16  4
17  1
18 23
19  1
20  2
21  5
22  3
23  2
24  8
25  5
26  1
27  2
28 17
29  3
30  2
31  2
32  2
33 16
34  1
35  6
36  3
37  6
38  9
39  2

After further research Im comfortable assigning the full names to the following players.

In [19]:
worldcup_players <- worldcup_players %>%
  mutate(
    full_name = case_when(
      full_name == "Elano" ~ "Elano Yegen",
      full_name == "Cedric" ~ "Cedric Soares",
      full_name == "Ro-Ro" ~ "Pedro Miguel",
      TRUE ~ full_name
    )
  )

The other few players with one word names we will leave as undefined for now.


I will Have CODEX AI go thorugh the full list of differences and through the full p[layers.csv dataset and find clear minimal gramatical mismatches. I willl then manually check a few to minimize likelihood of errors.

In [20]:
# Obvious name fixes found by comparing unmatched World Cup names to players.csv
# Only includes high-confidence spelling, punctuation, or known single-name expansions.
worldcup_players <- worldcup_players %>%
  mutate(
    full_name = case_when(
      full_name == "Abdulrahman Al-Aboud" ~ "Abdulrahman Al-Oboud",
      full_name == "Eric Maxim Choupo-Moting" ~ "Eric-Maxim Choupo-Moting",
      full_name == "Lawrence Ati-Zigi" ~ "Lawrence Ati Zigi",
      full_name == "Abdulaziz Hatem" ~ "Abdulaziz Hatim",
      full_name == "Abdulellah Al-Malki" ~ "Abdulelah Al-Malki",
      full_name == "Ahmed Hegazi" ~ "Ahmed Hegazy",
      full_name == "Aleksandr Yerokhin" ~ "Aleksandr Erokhin",
      full_name == "Aleksei Ionov" ~ "Aleksey Ionov",
      full_name == "Aleksei Kozlov" ~ "Aleksey Kozlov",
      full_name == "Aleksei Miranchuk" ~ "Aleksey Miranchuk",
      full_name == "Andrey Yeshchenko" ~ "Andrey Eshchenko",
      full_name == "Antar Yahia" ~ "Anthar Yahia",
      full_name == "Bilal El Khannous" ~ "Bilal El Khannouss",
      full_name == "Brian Idowu" ~ "Bryan Idowu",
      full_name == "Cheick Tiote" ~ "Cheik Tiote",
      full_name == "Daler Kuzyayev" ~ "Daler Kuzyaev",
      full_name == "Dimitris Salpingidis" ~ "Dimitrios Salpingidis",
      full_name == "Dmitri Kombarov" ~ "Dmitriy Kombarov",
      full_name == "Erick Davis" ~ "Eric Davis",
      full_name == "Filip Duricic" ~ "Filip Djuricic",
      full_name == "Georgi Shchennikov" ~ "Georgiy Shchennikov",
      full_name == "Giorgian De Arrascaeta" ~ "Giorgian de Arrascaeta",
      full_name == "Guy N'dy Assembe" ~ "Guy Ndy Assembe",
      full_name == "Hannes THor Halldorsson" ~ "Hannes Thor Halldorsson",
      full_name == "Hassan Al-Haydos" ~ "Hasan Al-Haydos",
      full_name == "Marco Urena" ~ "Marcos Urena",
      full_name == "Mateus Uribe" ~ "Matheus Uribe",
      full_name == "Michael Babatunde" ~ "Michel Babatunde",
      full_name == "Sergei Ignashevich" ~ "Sergey Ignashevich",
      full_name == "Sotirios Kyrgiakos" ~ "Sotiris Kyrgiakos",
      full_name == "Srdan Babic" ~ "Srdjan Babic",
      full_name == "Steve Cherundolo" ~ "Steven Cherundolo",
      full_name == "Vasili Berezutski" ~ "Vasiliy Berezutski",
      full_name == "Vasilis Torosidis" ~ "Vasilios Torosidis",
      full_name == "Viktor Fayzulin" ~ "Viktor Faizulin",
      full_name == "William Pacho" ~ "Willian Pacho",
      full_name == "Yuri Lodygin" ~ "Yuriy Lodygin",
      full_name == "Yuri Zhirkov" ~ "Yuriy Zhirkov",
      full_name == "Andrey Lunyov" ~ "Andrey Lunev",
      full_name == "Dani Carvajal" ~ "Daniel Carvajal",
      full_name == "Fyodor Kudryashov" ~ "Fedor Kudryashov",
      full_name == "Fyodor Smolov" ~ "Fedor Smolov",
      full_name == "Georges-Kevin Nkoudou" ~ "Georges-Kevin N'Koudou",
      full_name == "Giorgos Karagounis" ~ "Georgios Karagounis",
      full_name == "Giorgos Tzavellas" ~ "Georgios Tzavellas",
      full_name == "John Heitinga" ~ "Johnny Heitinga",
      full_name == "Joo-ho Park" ~ "Ju-ho Park",
      full_name == "Mbark Boussoufa" ~ "Moubarak Boussoufa",
      full_name == "Nikos Spyropoulos" ~ "Nikolaos Spyropoulos",
      full_name == "Robert Green" ~ "Rob Green",
      full_name == "Yakubu" ~ "Yakubu Aiyegbeni",
      TRUE ~ full_name
    )
  )

In [21]:
length(setdiff(worldcup_players$full_name, player_names$name))
length(worldcup_players$full_name)
setdiff(worldcup_players$full_name, player_names$name)

[1] 563

[1] 2379

  [1] "Bailey Wright"              "Cameron Devlin"
  [3] "Jerome Ngom Mbekeli"        "Nicolas Nkoulou"
  [5] "Moumi Ngamaleu"             "Andre-Frank Zambo Anguissa"
  [7] "Samuel Gouet"               "Nouhou Tolo"
  [9] "Souaibou Marou"             "Liam Fraser"
 [11] "Lucas Cavallini"            "Daniel Chacon"
 [13] "Keysher Fuller"             "Johan Venegas"
 [15] "Gerson Torres"              "Douglas Lopez"
 [17] "Jens Stryger Larsen"        "Romario Ibarra"
 [19] "Michael Estrada"            "Xavier Arreaga"
 [21] "Sebas Mendez"               "Alexander Dominguez"
 [23] "Djorkaeff Reasco"           "Abdul Fatawu Issahaku"
 [25] "Ibrahim Danlad"             "Abdul Manaf Nurudeen"
 [27] "Baba Rahman"                "Shojae Khalilzadeh"
 [29] "Hossein Kanaanizadegan"     "Rouzbeh Cheshmi"
 [31] "Mehdi Torabi"               "Ahmad Nourollahi"
 [33] "Hossein Hosseini"           "Abolfazl Jalali"
 [35] "Alfredo Talavera"           "Munir Mohamedi"
 [37] "Ilias Chair"                "Ahmed Reda Tagnaouti"
 [39] "Badr Benoun"                "Yahya Jabrane"
 [41] "Saad Al-Sheeb"              "Ali Assadalla"
 [43] "Musab Kheder"               "Homam Ahmed"
 [45] "Ismaeel Mohammad"           "Khalid Muneer"
 [47] "Salem Al-Hajri"             "Yousef Hassan"
 [49] "Naif Al-Hadhrami"           "Mostafa Meshaal"
 [51] "Mohammed Al-Rubaie"         "Ali Al-Bulaihi"
 [53] "Mohammed Al-Breik"          "Hassan Al-Tambakti"
 [55] "Moussa N'Diaye"             "Moustapha Name"
 [57] "Yoon Jong-gyu"              "Kim Jin-su"
 [59] "Kim Min-jae"                "Hwang In-beom"
 [61] "Paik Seung-ho"              "Cho Gue-sung"
 [63] "Song Bum-keun"              "Son Jun-ho"
 [65] "Kim Moon-hwan"              "Hwang Ui-jo"
 [67] "Na Sang-ho"                 "Lee Kang-in"
 [69] "Kwon Kyung-won"             "Kwon Chang-hoon"
 [71] "Kim Tae-hwan"               "Cho Yu-min"
 [73] "Jeong Woo-yeong"            "Song Min-kyu"
 [75] "Aymen Mathlouthi"           "Bilel Ifa"
 [77] "Hannibal Mejbri"            "Taha Yassine Khenissi"
 [79] "Ali Maaloul"                "Mohamed Ali Ben Romdhane"
 [81] "Ghailene Chaalali"          "Seifeddine Jaziri"
 [83] "Anis Ben Slimane"           "Jose Gimenez"
 [85] "Sebastian Sosa"             "Joe Morrell"
 [87] "Jonny Williams"             "James Meredith"
 [89] "Tim Cahill"                 "Dimitri Petratos"
 [91] "Oscar Murillo"              "Farid Diaz"
 [93] "Jose Fernando Cuadrado"     "Jhonny Acosta"
 [95] "Daniel Colindres"           "Patrick Pemberton"
 [97] "David Guzman"               "Kenner Gutierrez"
 [99] "Leonel Moreira"             "Essam El Hadary"
[101] "Omar Gaber"                 "Ahmed Fathy"
[103] "Ayman Ashraf"               "Mohamed Abdel Shafy"
[105] "Mahmoud Hamdy"              "Sherif Ekramy"
[107] "Abdallah El Said"           "Saad Samir"
[109] "Birkir Mar Saevarsson"      "Bjorn Bergmann Sigurdarson"
[111] "Holmar Orn Eyjolfsson"      "Hordur Bjorgvin Magnusson"
[113] "Jon Dadi Bodvarsson"        "Mohammad Rashid Mazaheri"
[115] "Mohammad Reza Khanzadeh"    "Pejman Montazeri"
[117] "Tomoaki Makino"             "Jose de Jesus Corona"
[119] "Hugo Ayala"                 "Rafael Marquez"
[121] "Javier Hernandez"           "Jesus Manuel Corona"
[123] "Oribe Peralta"              "Aziz Bouhaddouz"
[125] "Mehdi Carcela"              "Ikechukwu Ezenwa"
[127] "Elderson Echiejile"         "John Obi Mikel"
[129] "Shehu Abdullahi"            "Simeon Nwankwo"
[131] "Daniel Akpeyi"              "Jaime Penedo"
[133] "Michael Amir Murillo"       "Harold Cummings"
[135] "Gabriel Gomez"              "Blas Perez"
[137] "Edgar Barcenas"             "Gabriel Torres"
[139] "Armando Cooper"             "Adolfo Machado"
[141] "Valentin Pimentel"          "Luis Ovalle"
[143] "Luis Tejada"                "Ricardo Avila"
[145] "Felipe Baloy"               "Aldo Corzo"
[147] "Raul Ruidiaz"               "Christian Ramos"
[149] "Jose Carvallo"              "Nilson Loyola"
[151] "Bartosz Bialkowski"         "Andrei Semyonov"
[153] "Yury Gazinsky"              "Mansoor Al-Harbi"
[155] "Omar Hawsawi"               "Mohammad Al-Sahlawi"
[157] "Abdulmalek Al-Khaibri"      "Housain Al-Mogahwi"
[159] "Taisir Al-Jassim"           "Muhannad Assiri"
[161] "Yasser Al-Mosailem"         "Motaz Hawsawi"
[163] "Kara Mbodji"                "Mame Biram Diouf"
[165] "Khadim N'Diaye"             "Ban-suk Oh"
[167] "Young-sun Yun"              "Shin-wook Kim"
[169] "Hyun-soo Jang"              "Yo-han Go"
[171] "Farouk Ben Mustapha"        "Rami Bedoui"
[173] "Mohamed Amine Ben Amor"     "Ahmed Khalil"
[175] "Hamdi Nagguez"              "Martin Campana"
[177] "Maxi Pereira"               "Martin Silva"
[179] "Cedric Si Mohamed"          "Madjid Bougherra"
[181] "Hillal Soudani"             "Mohamed Zemmamouche"
[183] "Liassine Cadamuro-Bentaiba" "Abdelmoumene Djabou"
[185] "Maxi Rodriguez"             "Agustin Orion"
[187] "Ricky Alvarez"              "Matthew Spiranovic"
[189] "James Holland"              "Matt McKay"
[191] "Eugene Galekovic"           "Dario Vidosic"
[193] "Alex Wilkinson"             "Mark Bresciano"
[195] "Jasmin Fejzic"              "Asmir Avdukic"
[197] "Loic Feudjou"               "Cedric Djeugoue"
[199] "Eugenio Mena"               "Jorge Valdivia"
[201] "Cristopher Toselli"         "Jose Manuel Rojas"
[203] "Jose Pablo Fuenzalida"      "Esteban Paredes"
[205] "Johnny Herrera"             "Alexander Mejia"
[207] "Eder Alvarez Balanta"       "Juan Camilo Zuniga"
[209] "Faryd Mondragon"            "Carlos Valdes"
[211] "Michael Umana"              "David Myrie"
[213] "Michael Barrantes"          "Waylon Francis"
[215] "Oscar Granados"             "Randall Brenes"
[217] "Roy Miller"                 "Diego Calvo"
[219] "Jose Miguel Cubero"         "Daniel Cambronero"
[221] "Maximo Banguera"            "Jorge Guagua"
[223] "Frickson Erazo"             "Edison Mendez"
[225] "Joao Rojas"                 "Walter Ayovi"
[227] "Adrian Bone"                "Oswaldo Minda"
[229] "Michael Arroyo"             "Jaime Ayovi"
[231] "Oscar Bagui"                "Luis Saritama"
[233] "Fidel Martinez"             "Gabriel Achilier"
[235] "Stephen Adams"              "Emmanuel Agyemang-Badu"
[237] "Adam Larsen Kwarasey"       "Rashid Sumaila"
[239] "Fatau Dauda"                "Abdul Majeed Waris"
[241] "Harrison Afful"             "Kostas Manolas"
[243] "Kostas Mitroglou"           "Jose Holebas"
[245] "Kostas Katsouranis"         "Osman Chavez"
[247] "Juan Pablo Montes"          "Victor Bernardez"
[249] "Juan Carlos Garcia"         "Jerry Palacios"
[251] "Jerry Bengtson"             "Edder Delgado"
[253] "Boniek Garcia"              "Rony Martinez"
[255] "Noel Valladares"            "Luis Garrido"
[257] "Donis Escober"              "Marvin Chavez"
[259] "Rahman Ahmadi"              "Khosro Heydari"
[261] "Jalal Hosseini"             "Amir Hossein Sadeghi"
[263] "Javad Nekounam"             "Reza Haghighi"
[265] "Ghasem Haddadifar"          "Hossein Mahini"
[267] "Andranik Teymourian"        "Ahmad Alenemeh"
[269] "Bakhtiar Rahmani"           "Hashem Beikzadeh"
[271] "Steven Beitashour"          "Mehrdad Pooladi"
[273] "Boubacar Barry"             "Sylvain Gbohouo"
[275] "Serey Die"                  "Sayouba Mande"
[277] "Yasuhito Endo"              "Yoichiro Kakitani"
[279] "Yoshito Okubo"              "Yasuyuki Konno"
[281] "Masahiko Inoha"             "Manabu Saito"
[283] "Francisco Javier Rodriguez" "Carlos Salcido"
[285] "Miguel Angel Ponce"         "Isaac Brizuela"
[287] "Paul Aguilar"               "Jose Juan Vazquez"
[289] "Azubuike Egwuekwe"          "Kunle Odunlami"
[291] "Austin Ejide"               "Chigozie Agbim"
[293] "Chang-soo Kim"              "Suk-young Yun"
[295] "Tae-hwi Kwak"               "Dae-sung Ha"
[297] "Keun-ho Lee"                "Kook-young Han"
[299] "Jong-woo Park"              "Bum-young Lee"
[301] "Matt Besler"                "DaMarcus Beasley"
[303] "Brad Davis"                 "Kyle Beckerman"
[305] "Chris Wondolowski"          "Graham Zusi"
[307] "Nick Rimando"               "Diego Forlan"
[309] "Rodrigo Munoz"              "Lounes Gaouaoui"
[311] "Nadir Belhadj"              "Yazid Mansouri"
[313] "Rafik Saifi"                "Habib Bellaid"
[315] "Abdelkader Laifaoui"        "Karim Ziani"
[317] "Faouzi Chaouchi"            "Diego Pozo"
[319] "Clemente Rodriguez"         "Mario Bolatti"
[321] "Gabriel Heinze"             "Juan Sebastian Veron"
[323] "Ariel Garce"                "Martin Palermo"
[325] "Lucas Neill"                "Jason Culina"
[327] "Michael Beauchamp"          "Brett Emerton"
[329] "Joshua Kennedy"             "Harry Kewell"
[331] "Scott Chipperfield"         "Vince Grella"
[333] "Richard Garcia"             "David Carney"
[335] "Gilberto Silva"             "Luis Fabiano"
[337] "Kleberson"                  "Nilmar"
[339] "Doni"                       "Grafite"
[341] "Rigobert Song"              "Geremi"
[343] "Achille Emana"              "Souleymanou Hamidou"
[345] "Mohammadou Idrissou"        "Ismael Fuentes"
[347] "Waldo Ponce"                "Humberto Suazo"
[349] "Miguel Pinto"               "Gonzalo Fierro"
[351] "Rodrigo Millar"             "Luis Marin"
[353] "Jesper Gronkjaer"           "Jon Dahl Tomasson"
[355] "David James"                "Stephen Warnock"
[357] "Ledley King"                "Emile Heskey"
[359] "Thierry Henry"              "Arne Friedrich"
[361] "Hans-Jorg Butt"             "Daniel Agyei"
[363] "Hans Sarpei"                "John Paintsil"
[365] "Stephen Appiah"             "Prince Tagoe"
[367] "Isaac Vorsah"               "Stephen Ahorlu"
[369] "Lee Addy"                   "Richard Kingson"
[371] "Kostas Chalkias"            "Giourkas Seitaridis"
[373] "Angelos Charisteas"         "Sakis Prittas"
[375] "Ricardo Canales"            "Johnny Palacios"
[377] "Hendry Thomas"              "Ramon Nunez"
[379] "Carlos Pavon"               "David Suazo"
[381] "Georgie Welcome"            "Walter Martinez"
[383] "Mauricio Sabillon"          "Edgar Alvarez"
[385] "Danilo Turcios"             "Amado Guevara"
[387] "Sergio Mendoza"             "Fabio Cannavaro"
[389] "Gennaro Gattuso"            "Mauro Camoranesi"
[391] "Gianluca Zambrotta"         "Aruna Dindane"
[393] "Aristide Zogbo"             "Abdul Kader Keita"
[395] "Daniel Yeboah"              "Seigo Narazaki"
[397] "Yuki Abe"                   "Yuichi Komano"
[399] "Marcus Tulio Tanaka"        "Daisuke Matsui"
[401] "Shunsuke Nakamura"          "Keiji Tamada"
[403] "Kisho Yano"                 "Daiki Iwamasa"
[405] "Kengo Nakamura"             "Junichi Inamoto"
[407] "Yuji Nakazawa"              "Yoshikatsu Kawaguchi"
[409] "Oscar Perez"                "Ricardo Osorio"
[411] "Gerardo Torrado"            "Israel Castro"
[413] "Guillermo Franco"           "Cuauhtemoc Blanco"
[415] "Efrain Juarez"              "Jonny Magallon"
[417] "Jorge Torres Nilo"          "Adolfo Bautista"
[419] "Alberto Medina"             "Luis Ernesto Michel"
[421] "Giovanni van Bronckhorst"   "Andre Ooijer"
[423] "Mark Paston"                "Ben Sigmund"
[425] "Tony Lochhead"              "Ivan Vicelich"
[427] "Simon Elliott"              "Tim Brown"
[429] "Shane Smeltz"               "Chris Killen"
[431] "Leo Bertos"                 "Glen Moss"
[433] "Andy Barron"                "Michael McGlinchey"
[435] "Aaron Clapham"              "Dave Mulligan"
[437] "Andrew Boyens"              "Jeremy Christie"
[439] "Jeremy Brockie"             "James Bannatyne"
[441] "Nwankwo Kanu"               "Danny Shittu"
[443] "Sani Kaita"                 "Chidi Odiah"
[445] "Dickson Etuhu"              "Dele Aiyenugba"
[447] "Myong-guk Ri"               "Jong-hyok Cha"
[449] "Jun-il Ri"                  "Nam-chol Pak"
[451] "Kwang-chon Ri"              "Kum-il Kim"
[453] "Chol-hyok An"               "Yun-nam Ji"
[455] "Tae-se Jong"                "Yong-jo Hong"
[457] "In-guk Mun"                 "Kum-chol Choe"
[459] "Chol-jin Pak"               "Nam-Chol Pak"
[461] "Yong-jun Kim"               "Song-chol Nam"
[463] "Yong-hak An"                "Myong-gil Kim"
[465] "Chol-myong Ri"              "Myong-won Kim"
[467] "Kwang-hyok Ri"              "Kyong-il Kim"
[469] "Il-gwan Jong"               "Justo Villar"
[471] "Dario Veron"                "Claudio Morel"
[473] "Denis Caniza"               "Julio Cesar Caceres"
[475] "Carlos Bonet"               "Edgar Benitez"
[477] "Jonathan Santana"           "Diego Barreto"
[479] "Enrique Vera"               "Paulo da Silva"
[481] "Victor Caceres"             "Aureliano Torres"
[483] "Nestor Ortigoza"            "Aldo Bobadilla"
[485] "Rodolfo Gamarra"            "Miguel"
[487] "Deco"                       "Nemanja Vidic"
[489] "Nenad Milijas"              "Bojan Isailovic"
[491] "Nikola Zigic"               "Dragan Mrda"
[493] "Andelko Duricic"            "Zdeno Strba"
[495] "Jan Kozak"                  "Kamil Kopunek"
[497] "Martin Petras"              "Marko Suler"
[499] "Nejc Pecnik"                "Zlatan Ljubijankic"
[501] "Milivoje Novakovic"         "Jasmin Handanovic"
[503] "Zlatko Dedic"               "Aleksander Seliga"
[505] "Suad Filekovic"             "Andrej Komac"
[507] "Matej Mavric"               "Moeneeb Josephs"
[509] "Siboniso Gaxa"              "Tsepo Masilela"
[511] "Aaron Mokoena"              "MacBeth Sibaya"
[513] "Katlego Mphela"             "Teko Modise"
[515] "Reneilwe Letsholonyane"     "Matthew Booth"
[517] "Lucas Thwala"               "Itumeleng Khune"
[519] "Bernard Parker"             "Siyabonga Nomvethe"
[521] "Surprise Moriri"            "Siyabonga Sangweni"
[523] "Shu-Aib Walters"            "Thanduyise Khuboni"
[525] "Woon-jae Lee"               "Beom-seok Oh"
[527] "Hyung-il Kim"               "Yong-hyung Cho"
[529] "Nam-il Kim"                 "Jung-woo Kim"
[531] "Jung-hwan Ahn"              "Seung-yeoul Lee"
[533] "Young-pyo Lee"              "Jung-soo Lee"
[535] "Ki-hun Yeom"                "Dong-gook Lee"
[537] "Young-kwang Kim"            "Min-soo Kang"
[539] "Ludovic Magnin"             "Benjamin Huggel"
[541] "Alexander Frei"             "Blaise Nkufo"
[543] "Marco Wolfli"               "Stephane Grichting"
[545] "Marco Padalino"             "Hakan Yakin"
[547] "Albert Bunjaku"             "Carlos Bocanegra"
[549] "Herculez Gomez"             "Landon Donovan"
[551] "Stuart Holden"              "Jonathan Bornstein"
[553] "Ricardo Clark"              "Edson Buddle"
[555] "Jay DeMerit"                "Jose Francisco Torres"
[557] "Robbie Findley"             "Benny Feilhaber"
[559] "Marcus Hahnemann"           "Mauricio Victorino"
[561] "Sebastian Eguren"           "Sebastian Abreu"
[563] "Andres Scotti"

I want to assses the relevance of this unmatched players to our dataset and start considering the possibility of excluding some of these players.

In [22]:
nonmatched <- setdiff(worldcup_players$full_name, player_names$name)
fullworldcup_players <- readRDS(here("1.DataCleaning-R", "Data", "RDS", "FullRoster.rds"))

fullworldcup_players %>% 
    filter(full_name %in% nonmatched) %>%
        group_by(team_name, tournament_id) %>%
            summarize(players= sum(n())) %>%
                arrange(desc(players))

`summarise()` has grouped output by 'team_name'. You can override using the
`.groups` argument.

    team_name     tournament_id players
1   North Korea   WC-2010       23
2   New Zealand   WC-2010       18
3   South Korea   WC-2022       18
4   South Africa  WC-2010       17
5   Iran          WC-2014       15
6   South Korea   WC-2010       14
7   Australia     WC-2010       13
8   Japan         WC-2010       13
9   United States WC-2010       12
10  Honduras      WC-2010       11
11  Paraguay      WC-2010       11
12  Saudi Arabia  WC-2018       11
13  Mexico        WC-2010       10
14  Qatar         WC-2022       10
15  Costa Rica    WC-2014        9
16  Egypt         WC-2018        9
17  Ghana         WC-2010        9
18  Panama        WC-2018        9
19  South Korea   WC-2014        9
20  Australia     WC-2014        8
21  Chile         WC-2010        8
22  Tunisia       WC-2022        8
23  Ecuador       WC-2014        7
24  Ghana         WC-2014        7
25  Honduras      WC-2014        7
26  Iran          WC-2022        7
27  Nigeria       WC-2010        7
28  Switzerland   WC-2010        7
29  Tunisia       WC-2018        7
30  United States WC-2014        7
... ...           ...           ...
50  Saudi Arabia  WC-2022       4
51  Argentina     WC-2010       3
52  Australia     WC-2018       3
53  Costa Rica    WC-2022       3
54  Greece        WC-2014       3
55  Japan         WC-2014       3
56  Mexico        WC-2018       3
57  Peru          WC-2018       3
58  Senegal       WC-2018       3
59  Australia     WC-2022       2
60  Canada        WC-2022       2
61  Ivory Coast   WC-2014       2
62  Russia        WC-2018       2
63  Senegal       WC-2022       2
64  Uruguay       WC-2010       2
65  Wales         WC-2022       2
66  Brazil        WC-2010       1
67  Cameroon      WC-2014       1
68  Denmark       WC-2010       1
69  Denmark       WC-2018       1
70  Denmark       WC-2022       1
71  France        WC-2010       1
72  Germany       WC-2010       1
73  Japan         WC-2018       1
74  Mexico        WC-2022       1
75  Netherlands   WC-2010       1
76  Russia        WC-2014       1
77  Slovenia      WC-2010       1
78  Uruguay       WC-2014       1
79  Uruguay       WC-2018       1

Looking at this table we can see two clear trends. Firstly, some countries have almost all their players missing, there's a big chance that some of this countries leagues are simply not in our dataste and hence most of their national team players arent available. The other trend is that the oldest the tournamnet the most missing players. Since there is a good chance many of this players we just dont have data for I've decided to take all temas with 8 or more missing players out of our training data.

In [23]:
fullworldcup_players %>% 
  filter(full_name %in% nonmatched) %>%
    group_by(team_name, tournament_id) %>%
        summarize(players = n(), .groups = "drop") %>%
            filter(players >= 8) %>%
                summarize(total_players = sum(players))

563-265

  total_players
1 265

[1] 298

Now we only have 298 missing players, this is reasonable at around 10% of total players. It's inevitable to work with some incomplete data and assuming most of the missing plkayers are lower profile players we can assume that there effect on team performances would be lower so the model shouldn't be affected too strongly.

In [24]:
matched_players <- worldcup_players %>%
  rename(player_id_fj = player_id) %>%
  mutate(wc_year = as.integer(sub("WC-", "", tournament_id))) %>%
  arrange(full_name, desc(wc_year)) %>%
  distinct(full_name, .keep_all = TRUE) %>%
  inner_join(
    player_names %>%
      rename(
        player_id_kag = player_id,
        full_name = name
      ),
    by = "full_name"
  ) %>%
  filter(wc_year <= last_season) %>%
  distinct(full_name, .keep_all = TRUE) %>%
  select(full_name, player_id_fj, player_id_kag)

I added some players manually using other tools, the idea was to find the most relevant unmatched players.

In [25]:
manual_matches <- tibble::tribble(
  ~full_name,            ~player_id_fj, ~player_id_kag,
  "Saul",                "P-52837",      148928,
  "Thiago",              "P-92520",      60444,
  "Jose Maria Gimenez",  "P-65659",      250845,
  "Gareth Bale",         "P-63927",      39381,
  "Andres Iniesta",	     "P-56330",      7600,
  "David",               "P-49097",      7980,
  "Nemanja Vidic",       "P-68901",      19726,
  "Dani Alves",          "P-09441",      15951,
  "Javier Mascherano",   "P-77063",      19981,
  "Mikel Jon Obi",       "P-01164",      30739,
  "Javier Hernandez",    "P-36515",      50935,
  "Diego Godin",         "P-78440",      54928,	
  "Paulinho",            "P-54013",      57229,
  "Konstantino Manolas", "P-23816",	     104752
)

matched_players<- bind_rows(matched_players, manual_matches)

matched_players <- matched_players %>%
  filter(!(player_id_kag == 85771))

In [26]:
str(matched_players)
head(matched_players)
dim(matched_players)
any(duplicated(matched_players$player_id_fj))
any(duplicated(matched_players$player_id_kag))

tibble [1,728 x 3] (S3: tbl_df/tbl/data.frame)
 $ full_name    : chr [1:1728] "Aaron Lennon" "Aaron Long" "Aaron Mooy" "Aaron Ramsdale" ...
 $ player_id_fj : chr [1:1728] "P-64864" "P-75522" "P-95847" "P-62368" ...
 $ player_id_kag: num [1:1728] 14221 271072 123951 427568 50057 ...

  full_name       player_id_fj player_id_kag
1 Aaron Lennon    P-64864       14221
2 Aaron Long      P-75522      271072
3 Aaron Mooy      P-95847      123951
4 Aaron Ramsdale  P-62368      427568
5 Aaron Ramsey    P-86951       50057
6 Abde Ezzalzouli P-21052      724520

[1] 1728    3

[1] FALSE

[1] FALSE

In [31]:
saveRDS(matched_players, here("1.DataCleaning-R", "Data", "RDS", "Matching.rds"))