# Player Data Kaggle-Fjelstul

## Objectives

Develop a dataset with Kaggle dataset ID's, Fjestul Dataset IDs, and Player Names.

Thgis will serve as a mathcing tool to assign season data (from the kaggle dataset) to world cup data (from thje Fjestul dataset)


## Acknowledgments

Data in this notebook is taken from Kaggle using Kaggle's API. The dataset in Kaggle is made from data originally from Transfermarket.com.

## Libraries

In [241]:
library(dplyr)
library(here)
library(stringr)
library(stringi)

## Player data (Kaggle)

### Call Data with our Kaggle API

In [242]:
system("kaggle datasets download davidcariboo/player-scores -p kaggle_data")

unzip("kaggle_data/player-scores.zip",exdir = "kaggle_data")

In [243]:
player_data <- read.csv(here("1.DataCleaning-R", "kaggle_data", "players.csv"), stringsAsFactors = FALSE, encoding = "UTF-8")

colnames(player_data)

 [1] "player_id"
 [2] "first_name"
 [3] "last_name"
 [4] "name"
 [5] "last_season"
 [6] "current_club_id"
 [7] "player_code"
 [8] "country_of_birth"
 [9] "city_of_birth"
[10] "country_of_citizenship"
[11] "date_of_birth"
[12] "sub_position"
[13] "position"
[14] "foot"
[15] "height_in_cm"
[16] "contract_expiration_date"
[17] "agent_name"
[18] "image_url"
[19] "international_caps"
[20] "international_goals"
[21] "current_national_team_id"
[22] "url"
[23] "current_club_domestic_competition_id"
[24] "current_club_name"
[25] "market_value_in_eur"
[26] "highest_market_value_in_eur"

In [244]:
player_names <- player_data %>%
    select(player_id, name)

## Clean Data

### Lets get the player names and IDs from Fjestul

In [245]:
worldcup_players <- readRDS(here("1.DataCleaning-R", "Data", "RDS", "FullRoster.rds"))

worldcup_players <- worldcup_players %>%
    select(player_id, full_name) %>%
        distinct(player_id, .keep_all = TRUE)

Since the dataset for worldcup_players and player_namess come from sepearate orders their player_id system is different. It is also likely that some names may not match exaclty, lets investigate this possibility.

In [246]:
length(setdiff(worldcup_players$full_name, player_names$name))
length(worldcup_players$full_name)
setdiff(worldcup_players$full_name, player_names$name)

[1] 856

[1] 2379

  [1] "Loun<U+00E8>s Gaouaoui"     "Madjid Bougherra"
  [3] "Nadir Belhadj"              "Antar Yahia"
  [5] "Yazid Mansouri"             "Rafik Sa<U+00EF>fi"
  [7] "Habib Bella<U+00EF>d"       "Abdelkader La<U+00EF>faoui"
  [9] "Karim Ziani"                "Faouzi Chaouchi"
 [11] "Adl<U+00E8>ne Guedioura"    "Diego Pozo"
 [13] "Clemente Rodr<U+00ED>guez"  "Mario Bolatti"
 [15] "Gabriel Heinze"             "Juan Sebasti<U+00E1>n Ver<U+00F3>n"
 [17] "Ariel Garc<U+00E9>"         "Mart<U+00ED>n Palermo"
 [19] "Maxi Rodr<U+00ED>guez"      "Lucas Neill"
 [21] "Tim Cahill"                 "Jason Culina"
 [23] "Michael Beauchamp"          "Brett Emerton"
 [25] "Joshua Kennedy"             "Harry Kewell"
 [27] "Scott Chipperfield"         "Vince Grella"
 [29] "Eugene Galekovic"           "Richard Garcia"
 [31] "David Carney"               "Dario Vido<U+0161>i<U+0107>"
 [33] "Mark Bresciano"             "not applicable Maicon"
 [35] "not applicable L<U+00FA>cio" "not applicable Juan"
 [37] "not applicable Elano"       "Gilberto Silva"
 [39] "Lu<U+00ED>s Fabiano"        "not applicable Kak<U+00E1>"
 [41] "not applicable Robinho"     "not applicable Luis<U+00E3>o"
 [43] "not applicable Gilberto"    "not applicable Josu<U+00E9>"
 [45] "not applicable Ramires"     "not applicable Kl<U+00E9>berson"
 [47] "not applicable Nilmar"      "not applicable Doni"
 [49] "not applicable Grafite"     "Nicolas Nkoulou"
 [51] "Rigobert Song"              "not applicable Geremi"
 [53] "Achille Eman<U+00E1>"       "Eric Maxim Choupo-Moting"
 [55] "Souleymanou Hamidou"        "Mohammadou Idrissou"
 [57] "Jo<U+00EB>l Matip"          "Guy N'dy Assemb<U+00E9>"
 [59] "Ismael Fuentes"             "Waldo Ponce"
 [61] "Humberto Suazo"             "Jorge Valdivia"
 [63] "Miguel Pinto"               "Gonzalo Fierro"
 [65] "Rodrigo Millar"             "Esteban Paredes"
 [67] "Luis Mar<U+00ED>n"          "Thomas S<U+00F8>rensen"
 [69] "Jesper Gr<U+00F8>nkj<U+00E6>r" "Jon Dahl Tomasson"
 [71] "Martin J<U+00F8>rgensen"    "Per Kr<U+00F8>ldrup"
 [73] "S<U+00F8>ren Larsen"        "David James"
 [75] "Robert Green"               "Stephen Warnock"
 [77] "Ledley King"                "Emile Heskey"
 [79] "Eric Abidal"                "Thierry Henry"
 [81] "Arne Friedrich"             "not applicable Cacau"
 [83] "Hans-J<U+00F6>rg Butt"      "Daniel Agyei"
 [85] "Hans Sarpei"                "John Paintsil"
 [87] "Stephen Appiah"             "Prince Tagoe"
 [89] "Isaac Vorsah"               "Stephen Ahorlu"
 [91] "Lee Addy"                   "Richard Kingson"
 [93] "Kostas Chalkias"            "Giourkas Seitaridis"
 [95] "Nikos Spyropoulos"          "Angelos Charisteas"
 [97] "Giorgos Karagounis"         "Dimitris Salpingidis"
 [99] "Vasilis Torosidis"          "Sotirios Kyrgiakos"
[101] "Kostas Katsouranis"         "Sakis Prittas"
[103] "Ricardo Canales"            "Osman Ch<U+00E1>vez"
[105] "Johnny Palacios"            "V<U+00ED>ctor Bern<U+00E1>rdez"
[107] "Hendry Thomas"              "Ram<U+00F3>n N<U+00FA><U+00F1>ez"
[109] "Carlos Pav<U+00F3>n"        "Jerry Palacios"
[111] "David Suazo"                "Georgie Welcome"
[113] "Roger Espinoza"             "Boniek Garc<U+00ED>a"
[115] "Walter Mart<U+00ED>nez"     "Mauricio Sabill<U+00F3>n"
[117] "<U+00C9>dgar <U+00C1>lvarez" "Noel Valladares"
[119] "Danilo Turcios"             "Amado Guevara"
[121] "Donis Escober"              "Sergio Mendoza"
[123] "Fabio Cannavaro"            "Gennaro Gattuso"
[125] "Mauro Camoranesi"           "Gianluca Zambrotta"
[127] "Boubacar Barry"             "Cheick Tiot<U+00E9>"
[129] "not applicable Gervinho"    "not applicable Romaric"
[131] "Aruna Dindane"              "Aristide Zogbo"
[133] "Abdul Kader Ke<U+00EF>ta"   "Daniel Yeboah"
[135] "Seigo Narazaki"             "Yuki Abe"
[137] "Y<U+016B>ichi Komano"       "Marcus Tulio Tanaka"
[139] "Yasuhito End<U+014D>"       "Daisuke Matsui"
[141] "Shunsuke Nakamura"          "Keiji Tamada"
[143] "Kisho Yano"                 "Daiki Iwamasa"
[145] "Kengo Nakamura"             "Yasuyuki Konno"
[147] "Yoshito <U+014C>kubo"       "Junichi Inamoto"
[149] "Yuji Nakazawa"              "Yoshikatsu Kawaguchi"
[151] "<U+00D3>scar P<U+00E9>rez"  "Francisco Javier Rodr<U+00ED>guez"
[153] "Carlos Salcido"             "Rafael M<U+00E1>rquez"
[155] "Ricardo Osorio"             "Gerardo Torrado"
[157] "Israel Castro"              "Guillermo Franco"
[159] "Cuauht<U+00E9>moc Blanco"   "Paul Aguilar"
[161] "Javier Hern<U+00E1>ndez"    "Efra<U+00ED>n Ju<U+00E1>rez"
[163] "Jonny Magall<U+00F3>n"      "Jorge Torres Nilo"
[165] "Adolfo Bautista"            "Alberto Medina"
[167] "Luis Ernesto Michel"        "John Heitinga"
[169] "Giovanni van Bronckhorst"   "Andr<U+00E9> Ooijer"
[171] "Mark Paston"                "Ben Sigmund"
[173] "Tony Lochhead"              "Ivan Vicelich"
[175] "Simon Elliott"              "Tim Brown"
[177] "Shane Smeltz"               "Chris Killen"
[179] "Leo Bertos"                 "Glen Moss"
[181] "Andy Barron"                "Michael McGlinchey"
[183] "Aaron Clapham"              "Dave Mulligan"
[185] "Andrew Boyens"              "Jeremy Christie"
[187] "Jeremy Brockie"             "James Bannatyne"
[189] "Nwankwo Kanu"               "Danny Shittu"
[191] "not applicable Yakubu"      "Sani Kaita"
[193] "Austin Ejide"               "Chidi Odiah"
[195] "Dickson Etuhu"              "Elderson Echi<U+00E9>jil<U+00E9>"
[197] "Dele Aiyenugba"             "Myong-guk Ri"
[199] "Jong-hyok Cha"              "Jun-il Ri"
[201] "Nam-chol Pak"               "Kwang-chon Ri"
[203] "Kum-il Kim"                 "Chol-hyok An"
[205] "Yun-nam Ji"                 "Tae-se Jong"
[207] "Yong-jo Hong"               "In-guk Mun"
[209] "Kum-chol Choe"              "Chol-jin Pak"
[211] "Nam-Chol Pak"               "Yong-jun Kim"
[213] "Song-chol Nam"              "Yong-hak An"
[215] "Myong-gil Kim"              "Chol-myong Ri"
[217] "Myong-won Kim"              "Kwang-hyok Ri"
[219] "Kyong-il Kim"               "Il-gwan Jong"
[221] "Justo Villar"               "Dar<U+00ED>o Ver<U+00F3>n"
[223] "Claudio Morel"              "Denis Caniza"
[225] "Julio C<U+00E9>sar C<U+00E1>ceres" "Carlos Bonet"
[227] "<U+00C9>dgar Ben<U+00ED>tez" "Jonathan Santana"
[229] "Diego Barreto"              "Enrique Vera"
[231] "Paulo da Silva"             "V<U+00ED>ctor C<U+00E1>ceres"
[233] "Aureliano Torres"           "N<U+00E9>stor Ortigoza"
[235] "Aldo Bobadilla"             "Rodolfo Gamarra"
[237] "not applicable Eduardo"     "not applicable Rolando"
[239] "not applicable Duda"        "not applicable Li<U+00E9>dson"
[241] "not applicable Danny"       "not applicable Sim<U+00E3>o"
[243] "not applicable Beto"        "not applicable Miguel"
[245] "not applicable Pepe"        "Raul Meireles"
[247] "not applicable Tiago"       "not applicable Deco"
[249] "Gojko Ka<U+010D>ar"         "Nemanja Vidi<U+0107>"
[251] "Branislav Ivanovi<U+0107>"  "Zoran To<U+0161>i<U+0107>"
[253] "Danko Lazovi<U+0107>"       "Marko Panteli<U+0107>"
[255] "Dejan Stankovi<U+0107>"     "Nenad Milija<U+0161>"
[257] "Bojan Isailovi<U+0107>"     "Aleksandar Lukovi<U+0107>"
[259] "Milan Jovanovi<U+0107>"     "Nikola <U+017D>igi<U+0107>"
[261] "Ivan Obradovi<U+0107>"      "Milo<U+0161> Krasi<U+0107>"
[263] "Milo<U+0161> Ninkovi<U+0107>" "Radosav Petrovi<U+0107>"
[265] "Neven Suboti<U+0107>"       "Dragan Mr<U+0111>a"
[267] "Zdravko Kuzmanovi<U+0107>"  "An<U+0111>elko <U+0110>uri<U+010D>i<U+0107>"
[269] "J<U+00E1>n Mucha"           "Martin <U+0160>krtel"
[271] "Marek <U+010C>ech"          "Radoslav Zabavn<U+00ED>k"
[273] "Zdeno <U+0160>trba"         "Vladim<U+00ED>r Weiss"
[275] "J<U+00E1>n Koz<U+00E1>k"    "Stanislav <U+0160>est<U+00E1>k"
[277] "R<U+00F3>bert Vittek"       "Du<U+0161>an Perni<U+0161>"
[279] "Filip Holo<U+0161>ko"       "J<U+00E1>n <U+010E>urica"
[281] "Marek Ham<U+0161><U+00ED>k" "Erik Jendri<U+0161>ek"
[283] "Kamil Kop<U+00FA>nek"       "Kornel Sal<U+00E1>ta"
[285] "Martin Petr<U+00E1><U+0161>" "Du<U+0161>an Kuciak"
[287] "Samir Handanovi<U+0107>"    "Mi<U+0161>o Bre<U+010D>ko"
[289] "Elvedin D<U+017E>ini<U+0107>" "Marko <U+0160>uler"
[291] "Bo<U+0161>tjan Cesar"       "Branko Ili<U+0107>"
[293] "Nejc Pe<U+010D>nik"         "Zlatan Ljubijanki<U+0107>"
[295] "Milivoje Novakovi<U+0107>"  "Jasmin Handanovi<U+0107>"
[297] "Bojan Joki<U+0107>"         "Zlatko Dedi<U+0107>"
[299] "Aleksander <U+0160>eliga"   "Andra<U+017E> Kirm"
[301] "Aleksandar Radosavljevi<U+0107>" "Suad Filekovi<U+0107>"
[303] "Andrej Komac"               "Dalibor Stevanovi<U+0107>"
[305] "Matej Mavri<U+010D>"        "Tim Matav<U+017E>"
[307] "Moeneeb Josephs"            "Siboniso Gaxa"
[309] "Tsepo Masilela"             "Aaron Mokoena"
[311] "MacBeth Sibaya"             "Katlego Mphela"
[313] "Teko Modise"                "Reneilwe Letsholonyane"
[315] "Matthew Booth"              "Lucas Thwala"
[317] "Itumeleng Khune"            "Bernard Parker"
[319] "Siyabonga Nomvethe"         "Surprise Moriri"
[321] "Siyabonga Sangweni"         "Shu-Aib Walters"
[323] "Thanduyise Khuboni"         "Woon-jae Lee"
[325] "Beom-seok Oh"               "Hyung-il Kim"
[327] "Yong-hyung Cho"             "Nam-il Kim"
[329] "Jung-woo Kim"               "Jung-hwan Ahn"
[331] "Seung-yeoul Lee"            "Young-pyo Lee"
[333] "Jung-soo Lee"               "Ki-hun Yeom"
[335] "Dong-gook Lee"              "Young-kwang Kim"
[337] "Min-soo Kang"               "not applicable Xavi"
[339] "not applicable Pedro"       "Ludovic Magnin"
[341] "Benjamin Huggel"            "Alexander Frei"
[343] "Blaise Nkufo"               "Marco W<U+00F6>lfli"
[345] "St<U+00E9>phane Grichting"  "Marco Padalino"
[347] "Hakan Yakin"                "G<U+00E9>lson Fernandes"
[349] "Albert Bunjaku"             "Carlos Bocanegra"
[351] "Steve Cherundolo"           "DaMarcus Beasley"
[353] "Herculez Gomez"             "Landon Donovan"
[355] "Stuart Holden"              "Jonathan Bornstein"
[357] "Ricardo Clark"              "Edson Buddle"
[359] "Jay DeMerit"                "Jos<U+00E9> Francisco Torres"
[361] "Robbie Findley"             "Benny Feilhaber"
[363] "Marcus Hahnemann"           "Mauricio Victorino"
[365] "Sebasti<U+00E1>n Eguren"    "Diego Forl<U+00E1>n"
[367] "Sebasti<U+00E1>n Abreu"     "Maxi Pereira"
[369] "Andr<U+00E9>s Scotti"       "Mart<U+00ED>n Silva"
[371] "C<U+00E9>dric Si Mohamed"   "Hillal Soudani"
[373] "Mohamed Zemmamouche"        "Liassine Cadamuro-Benta<U+00EF>ba"
[375] "Abdelmoumene Djabou"        "Agust<U+00ED>n Ori<U+00F3>n"
[377] "Ricky <U+00C1>lvarez"       "Matthew Spiranovic"
[379] "Bailey Wright"              "James Holland"
[381] "Matt McKay"                 "Alex Wilkinson"
[383] "Asmir Begovi<U+0107>"       "Avdija Vr<U+0161>ajevi<U+0107>"
[385] "Ermin Bi<U+010D>ak<U+010D>i<U+0107>" "Emir Spahi<U+0107>"
[387] "Sead Kola<U+0161>inac"      "Ognjen Vranje<U+0161>"
[389] "Muhamed Be<U+0161>i<U+0107>" "Vedad Ibi<U+0161>evi<U+0107>"
[391] "Zvjezdan Misimovi<U+0107>"  "Edin D<U+017E>eko"
[393] "Jasmin Fejzi<U+0107>"       "Mensur Mujd<U+017E>a"
[395] "Tino-Sven Su<U+0161>i<U+0107>" "Toni <U+0160>unji<U+0107>"
[397] "Senad Luli<U+0107>"         "Senijad Ibri<U+010D>i<U+0107>"
[399] "Edin Vi<U+0161><U+0107>a"   "Izet Hajrovi<U+0107>"
[401] "Anel Had<U+017E>i<U+0107>"  "Asmir Avduki<U+0107>"
[403] "Sejad Salihovi<U+0107>"     "not applicable Jefferson"
[405] "not applicable Fernandinho" "not applicable Marcelo"
[407] "not applicable Hulk"        "not applicable Paulinho"
[409] "not applicable Fred"        "not applicable Neymar"
[411] "not applicable Oscar"       "not applicable Dante"
[413] "not applicable Maxwell"     "not applicable Henrique"
[415] "not applicable Hernanes"    "not applicable Willian"
[417] "not applicable Bernard"     "not applicable J<U+00F4>"
[419] "not applicable Victor"      "Lo<U+00EF>c Feudjou"
[421] "C<U+00E9>dric Djeugou<U+00E9>" "Eugenio Mena"
[423] "Cristopher Toselli"         "Jos<U+00E9> Manuel Rojas"
[425] "Jos<U+00E9> Pablo Fuenzalida" "Johnny Herrera"
[427] "Cristi<U+00E1>n Zapata"     "Alexander Mej<U+00ED>a"
[429] "<U+00C9>der <U+00C1>lvarez Balanta" "Juan Camilo Z<U+00FA><U+00F1>iga"
[431] "Faryd Mondrag<U+00F3>n"     "Carlos Vald<U+00E9>s"
[433] "Jhonny Acosta"              "Michael Uma<U+00F1>a"
[435] "David Myrie"                "Michael Barrantes"
[437] "Waylon Francis"             "<U+00D3>scar Granados"
[439] "Randall Brenes"             "Patrick Pemberton"
[441] "Roy Miller"                 "Diego Calvo"
[443] "Marco Ure<U+00F1>a"         "Jos<U+00E9> Miguel Cubero"
[445] "Daniel Cambronero"          "<U+0160>ime Vrsaljko"
[447] "Danijel Pranji<U+0107>"     "Vedran <U+0106>orluka"
[449] "Ivan Rakiti<U+0107>"        "Ognjen Vukojevi<U+0107>"
[451] "Nikica Jelavi<U+0107>"      "Mario Mand<U+017E>uki<U+0107>"
[453] "Ivica Oli<U+0107>"          "not applicable Sammir"
[455] "Mateo Kova<U+010D>i<U+0107>" "Danijel Suba<U+0161>i<U+0107>"
[457] "M<U+00E1>ximo Banguera"     "Jorge Guagua"
[459] "Frickson Erazo"             "<U+00C9>dison M<U+00E9>ndez"
[461] "Joao Rojas"                 "Walter Ayov<U+00ED>"
[463] "Adri<U+00E1>n Bone"         "Oswaldo Minda"
[465] "Michael Arroyo"             "Jaime Ayov<U+00ED>"
[467] "<U+00D3>scar Bag<U+00FC><U+00ED>" "Luis Saritama"
[469] "Fidel Mart<U+00ED>nez"      "Gabriel Achilier"
[471] "Alexander Dom<U+00ED>nguez" "Stephen Adams"
[473] "Emmanuel Agyemang-Badu"     "Adam Larsen Kwarasey"
[475] "Rashid Sumaila"             "Fatau Dauda"
[477] "Abdul Majeed Waris"         "Harrison Afful"
[479] "Giorgos Tzavellas"          "Kostas Manolas"
[481] "Kostas Mitroglou"           "Jos<U+00E9> Holebas"
[483] "Juan Pablo Montes"          "Juan Carlos Garc<U+00ED>a"
[485] "Jerry Bengtson"             "Edder Delgado"
[487] "Rony Mart<U+00ED>nez"       "Andy Najar"
[489] "Luis Garrido"               "Marvin Ch<U+00E1>vez"
[491] "Rahman Ahmadi"              "Khosro Heydari"
[493] "Jalal Hosseini"             "Amir Hossein Sadeghi"
[495] "Javad Nekounam"             "Reza Haghighi"
[497] "Ghasem Haddadifar"          "Hossein Mahini"
[499] "Andranik Teymourian"        "Pejman Montazeri"
[501] "Ahmad Alenemeh"             "Bakhtiar Rahmani"
[503] "Hashem Beikzadeh"           "Steven Beitashour"
[505] "Mehrdad Pooladi"            "Isma<U+00EB>l Diomand<U+00E9>"
[507] "Sylvain Gbohouo"            "Serey Di<U+00E9>"
[509] "Sayouba Mand<U+00E9>"       "G<U+014D>toku Sakai"
[511] "Yoichiro Kakitani"          "Masahiko Inoha"
[513] "Manabu Sait<U+014D>"        "Sh<U+016B>ichi Gonda"
[515] "Jos<U+00E9> de Jes<U+00FA>s Corona" "Alfredo Talavera"
[517] "Miguel <U+00C1>ngel Ponce"  "Isa<U+00E1>c Brizuela"
[519] "Oribe Peralta"              "Jos<U+00E9> Juan V<U+00E1>zquez"
[521] "Azubuike Egwuekwe"          "John Obi Mikel"
[523] "Kunle Odunlami"             "Michael Babatunde"
[525] "Chigozie Agbim"             "not applicable Vieirinha"
[527] "not applicable Eder"        "not applicable Nani"
[529] "Aleksei Kozlov"             "Georgi Shchennikov"
[531] "Sergei Ignashevich"         "Andrei Semyonov"
[533] "Yuri Lodygin"               "Vasili Berezutski"
[535] "Yuri Zhirkov"               "Viktor Fayzulin"
[537] "Aleksei Ionov"              "Andrey Yeshchenko"
[539] "Dmitri Kombarov"            "Chang-soo Kim"
[541] "Suk-young Yun"              "Tae-hwi Kwak"
[543] "Dae-sung Ha"                "Keun-ho Lee"
[545] "Kook-young Han"             "Jong-woo Park"
[547] "Shin-wook Kim"              "Joo-ho Park"
[549] "Bum-young Lee"              "not applicable Juanfran"
[551] "not applicable Koke"        "Blerim D<U+017E>emaili"
[553] "Mario Gavranovi<U+0107>"    "Josip Drmi<U+0107>"
[555] "Omar Gonzalez"              "Matt Besler"
[557] "Brad Davis"                 "Kyle Beckerman"
[559] "Chris Wondolowski"          "Graham Zusi"
[561] "Nick Rimando"               "Rodrigo Mu<U+00F1>oz"
[563] "Jos<U+00E9> Gim<U+00E9>nez" "Milo<U+0161> Degenek"
[565] "James Meredith"             "Dimitri Petratos"
[567] "not applicable Alisson"     "not applicable Miranda"
[569] "not applicable Casemiro"    "not applicable Marquinhos"
[571] "not applicable Danilo"      "not applicable C<U+00E1>ssio"
[573] "not applicable Taison"      "not applicable Fagner"
[575] "not applicable Ederson"     "<U+00D3>scar Murillo"
[577] "Mateus Uribe"               "Farid D<U+00ED>az"
[579] "Jos<U+00E9> Fernando Cuadrado" "Daniel Colindres"
[581] "Johan Venegas"              "David Guzm<U+00E1>n"
[583] "Kenner Guti<U+00E9>rrez"    "Leonel Moreira"
[585] "Dominik Livakovi<U+0107>"   "Ivan Strini<U+0107>"
[587] "Andrej Kramari<U+0107>"     "Lovre Kalini<U+0107>"
[589] "Filip Bradari<U+0107>"      "Duje <U+0106>aleta-Car"
[591] "Nikola Kalini<U+0107>"      "Josip Pivari<U+0107>"
[593] "Nicolai J<U+00F8>rgensen"   "Jens Stryger Larsen"
[595] "Frederik R<U+00F8>nnow"     "Essam El Hadary"
[597] "Omar Gaber"                 "Ahmed Hegazi"
[599] "Ahmed Fathy"                "not applicable Kahraba"
[601] "Ayman Ashraf"               "Mohamed Abdel Shafy"
[603] "Mahmoud Hamdy"              "Sherif Ekramy"
[605] "not applicable Shikabala"   "Abdallah El Said"
[607] "Saad Samir"                 "not applicable Tr<U+00E9>z<U+00E9>guet"
[609] "Lucas Hernandez"            "Hannes <U+00DE><U+00F3>r Halld<U+00F3>rsson"
[611] "Birkir M<U+00E1>r S<U+00E6>varsson" "Sam<U+00FA>el Fri<U+00F0>j<U+00F3>nsson"
[613] "Albert Gu<U+00F0>mundsson"  "Ragnar Sigur<U+00F0>sson"
[615] "J<U+00F3>hann Berg Gu<U+00F0>mundsson" "Bj<U+00F6>rn Bergmann Sigur<U+00F0>arson"
[617] "Gylfi Sigur<U+00F0>sson"    "Alfre<U+00F0> Finnbogason"
[619] "H<U+00F3>lmar <U+00D6>rn Eyj<U+00F3>lfsson" "H<U+00F6>r<U+00F0>ur Bj<U+00F6>rgvin Magn<U+00FA>sson"
[621] "Emil Hallfre<U+00F0>sson"   "J<U+00F3>n Da<U+00F0>i B<U+00F6><U+00F0>varsson"
[623] "Mehdi Torabi"               "Rouzbeh Cheshmi"
[625] "Mohammad Rashid Mazaheri"   "Mohammad Reza Khanzadeh"
[627] "Tomoaki Makino"             "Hugo Ayala"
[629] "Jes<U+00FA>s Manuel Corona" "Munir Mohamedi"
[631] "Mbark Boussoufa"            "Aziz Bouhaddouz"
[633] "Ahmed Reda Tagnaouti"       "Mehdi Carcela"
[635] "Ikechukwu Ezenwa"           "Brian Idowu"
[637] "Shehu Abdullahi"            "Simeon Nwankwo"
[639] "Daniel Akpeyi"              "Jaime Penedo"
[641] "Michael Amir Murillo"       "Harold Cummings"
[643] "Gabriel G<U+00F3>mez"       "Blas P<U+00E9>rez"
[645] "<U+00C9>dgar B<U+00E1>rcenas" "Gabriel Torres"
[647] "Armando Cooper"             "Adolfo Machado"
[649] "Valent<U+00ED>n Pimentel"   "Erick Davis"
[651] "Luis Ovalle"                "Luis Tejada"
[653] "Ricardo <U+00C1>vila"       "<U+00C1>lex Rodr<U+00ED>guez"
[655] "Felipe Baloy"               "Aldo Corzo"
[657] "Ra<U+00FA>l Ruid<U+00ED>az" "Christian Ramos"
[659] "Jos<U+00E9> Carvallo"       "Nilson Loyola"
[661] "Wojciech Szcz<U+0119>sny"   "Micha<U+0142> Pazdan"
[663] "Jacek G<U+00F3>ralski"      "Bartosz Bia<U+0142>kowski"
[665] "<U+0141>ukasz Teodorczyk"   "Jakub B<U+0142>aszczykowski"
[667] "S<U+0142>awomir Peszko"     "Piotr Zieli<U+0144>ski"
[669] "<U+0141>ukasz Piszczek"     "<U+0141>ukasz Fabia<U+0144>ski"
[671] "not applicable C<U+00E9>dric" "Daler Kuzyayev"
[673] "Yury Gazinsky"              "Fyodor Smolov"
[675] "Andrey Lunyov"              "Fyodor Kudryashov"
[677] "Aleksei Miranchuk"          "Aleksandr Yerokhin"
[679] "Mansoor Al-Harbi"           "Ali Al-Bulaihi"
[681] "Omar Hawsawi"               "Mohammed Al-Breik"
[683] "Mohammad Al-Sahlawi"        "Abdulmalek Al-Khaibri"
[685] "Housain Al-Mogahwi"         "Taisir Al-Jassim"
[687] "Muhannad Assiri"            "Yasser Al-Mosailem"
[689] "Motaz Hawsawi"              "Kara Mbodji"
[691] "Mame Biram Diouf"           "Khadim N'Diaye"
[693] "Du<U+0161>ko To<U+0161>i<U+0107>" "Luka Milivojevi<U+0107>"
[695] "Uro<U+0161> Spaji<U+0107>"  "Andrija <U+017D>ivkovi<U+0107>"
[697] "Aleksandar Prijovi<U+0107>" "Milo<U+0161> Veljkovi<U+0107>"
[699] "Milan Rodi<U+0107>"         "Nemanja Radonji<U+0107>"
[701] "Adem Ljaji<U+0107>"         "Marko Dmitrovi<U+0107>"
[703] "Ban-suk Oh"                 "Young-sun Yun"

We can see a very significant amount of players have mismatched names.

In [247]:
set.seed(12)

player_names %>%
    slice_sample(n = 20) %>%
        select(name)

   name
1  Brad Halliday
2  Pedro Botelho
3  Gabriel Palmero
4  Martin Jiranek
5  You-hyeon Lee
6  Islam Issa
7  Andu Kelati
8  Riccardo Brosco
9  Mohammed Abera
10 Claude Gon<U+00E7>alves
11 Tayfur Bing<U+00F6>l
12 Jer<U+00F3>nimo D<U+00F3>mina
13 Hampus N<U+00E4>sstr<U+00F6>m
14 Muhammed Ergin
15 Bj<U+00F6>rn Engels
16 Dusan Cvetinovic
17 Paulo Monteiro
18 Fraser Murray
19 Tom Dele-Bashiru
20 Manuel Ravasio

After manually inspecting I see some players are just spelled slightly differently in one dataset vs the other. For example Antar/Anthar Yahiya. Let's trouble shoot other issues first since this might require a lot of manual comparison which will be easier to do with less observations.

In [248]:
player_names %>%
  filter(grepl("Anthar Yahia", name)) %>%
    select(name)

worldcup_players %>%
  filter(grepl("Antar Yahia", full_name)) %>%
    select(full_name)

  name
1 Anthar Yahia

  full_name
1 Antar Yahia

Some of the player names also differ in the datasets because of accents. For example Ronald Araujo.

In [249]:
player_names %>%
  filter(grepl("Ronald Araujo", name)) %>%
    select(name)

worldcup_players %>%
  filter(grepl("Ronald Ara", full_name)) %>%
    select(full_name)

  name
1 Ronald Araujo

  full_name
1 Ronald Ara<U+00FA>jo

The accents seem to be a relevant issue across a lot of players. Let's write a function to normalize all text by removing accents. Also making sure to decode all text in the process.

In [250]:
# This was done with significant help from Codex AI
decode_unicode_tags <- function(x) {
  fix_one <- function(s) {
    matches <- regmatches(
      s,
      gregexpr("<U\\+[0-9A-Fa-f]{4,6}>", s, perl = TRUE)
    )[[1]]

    if (length(matches) == 1 && matches[1] == "") return(s)

    for (m in matches) {
      hex <- sub("<U\\+([0-9A-Fa-f]{4,6})>", "\\1", m, perl = TRUE)
      replacement <- intToUtf8(strtoi(hex, base = 16))
      s <- sub(m, replacement, s, fixed = TRUE)
    }

    s
  }

  vapply(x, fix_one, character(1))
}

remove_accents <- function(x) {
  x <- decode_unicode_tags(x)
  x <- enc2utf8(x)
  stringi::stri_trans_general(x, "Latin-ASCII")
}

#Test
remove_accents("Ronald Araújo")
remove_accents("Ángel Di María")
remove_accents("Cristiano Ronaldo")

[1] "Ronald Araujo"

[1] "Angel Di Maria"

[1] "Cristiano Ronaldo"

Seems to work pretty well, lets apply it to both of our datasets and then compare again

In [251]:
player_names <- player_names %>%
    mutate(name = remove_accents(name))

worldcup_players <- worldcup_players %>%
    mutate(full_name = remove_accents(full_name))

length(setdiff(worldcup_players$full_name, player_names$name))
length(worldcup_players$full_name)
setdiff(worldcup_players$full_name, player_names$name)

[1] 691

[1] 2379

  [1] "Lounes Gaouaoui"            "Madjid Bougherra"
  [3] "Nadir Belhadj"              "Antar Yahia"
  [5] "Yazid Mansouri"             "Rafik Saifi"
  [7] "Habib Bellaid"              "Abdelkader Laifaoui"
  [9] "Karim Ziani"                "Faouzi Chaouchi"
 [11] "Diego Pozo"                 "Clemente Rodriguez"
 [13] "Mario Bolatti"              "Gabriel Heinze"
 [15] "Juan Sebastian Veron"       "Ariel Garce"
 [17] "Martin Palermo"             "Maxi Rodriguez"
 [19] "Lucas Neill"                "Tim Cahill"
 [21] "Jason Culina"               "Michael Beauchamp"
 [23] "Brett Emerton"              "Joshua Kennedy"
 [25] "Harry Kewell"               "Scott Chipperfield"
 [27] "Vince Grella"               "Eugene Galekovic"
 [29] "Richard Garcia"             "David Carney"
 [31] "Dario Vidosic"              "Mark Bresciano"
 [33] "not applicable Maicon"      "not applicable Lucio"
 [35] "not applicable Juan"        "not applicable Elano"
 [37] "Gilberto Silva"             "Luis Fabiano"
 [39] "not applicable Kaka"        "not applicable Robinho"
 [41] "not applicable Luisao"      "not applicable Gilberto"
 [43] "not applicable Josue"       "not applicable Ramires"
 [45] "not applicable Kleberson"   "not applicable Nilmar"
 [47] "not applicable Doni"        "not applicable Grafite"
 [49] "Nicolas Nkoulou"            "Rigobert Song"
 [51] "not applicable Geremi"      "Achille Emana"
 [53] "Eric Maxim Choupo-Moting"   "Souleymanou Hamidou"
 [55] "Mohammadou Idrissou"        "Guy N'dy Assembe"
 [57] "Ismael Fuentes"             "Waldo Ponce"
 [59] "Humberto Suazo"             "Jorge Valdivia"
 [61] "Miguel Pinto"               "Gonzalo Fierro"
 [63] "Rodrigo Millar"             "Esteban Paredes"
 [65] "Luis Marin"                 "Jesper Gronkjaer"
 [67] "Jon Dahl Tomasson"          "David James"
 [69] "Robert Green"               "Stephen Warnock"
 [71] "Ledley King"                "Emile Heskey"
 [73] "Thierry Henry"              "Arne Friedrich"
 [75] "not applicable Cacau"       "Hans-Jorg Butt"
 [77] "Daniel Agyei"               "Hans Sarpei"
 [79] "John Paintsil"              "Stephen Appiah"
 [81] "Prince Tagoe"               "Isaac Vorsah"
 [83] "Stephen Ahorlu"             "Lee Addy"
 [85] "Richard Kingson"            "Kostas Chalkias"
 [87] "Giourkas Seitaridis"        "Nikos Spyropoulos"
 [89] "Angelos Charisteas"         "Giorgos Karagounis"
 [91] "Dimitris Salpingidis"       "Vasilis Torosidis"
 [93] "Sotirios Kyrgiakos"         "Kostas Katsouranis"
 [95] "Sakis Prittas"              "Ricardo Canales"
 [97] "Osman Chavez"               "Johnny Palacios"
 [99] "Victor Bernardez"           "Hendry Thomas"
[101] "Ramon Nunez"                "Carlos Pavon"
[103] "Jerry Palacios"             "David Suazo"
[105] "Georgie Welcome"            "Boniek Garcia"
[107] "Walter Martinez"            "Mauricio Sabillon"
[109] "Edgar Alvarez"              "Noel Valladares"
[111] "Danilo Turcios"             "Amado Guevara"
[113] "Donis Escober"              "Sergio Mendoza"
[115] "Fabio Cannavaro"            "Gennaro Gattuso"
[117] "Mauro Camoranesi"           "Gianluca Zambrotta"
[119] "Boubacar Barry"             "Cheick Tiote"
[121] "not applicable Gervinho"    "not applicable Romaric"
[123] "Aruna Dindane"              "Aristide Zogbo"
[125] "Abdul Kader Keita"          "Daniel Yeboah"
[127] "Seigo Narazaki"             "Yuki Abe"
[129] "Yuichi Komano"              "Marcus Tulio Tanaka"
[131] "Yasuhito Endo"              "Daisuke Matsui"
[133] "Shunsuke Nakamura"          "Keiji Tamada"
[135] "Kisho Yano"                 "Daiki Iwamasa"
[137] "Kengo Nakamura"             "Yasuyuki Konno"
[139] "Yoshito Okubo"              "Junichi Inamoto"
[141] "Yuji Nakazawa"              "Yoshikatsu Kawaguchi"
[143] "Oscar Perez"                "Francisco Javier Rodriguez"
[145] "Carlos Salcido"             "Rafael Marquez"
[147] "Ricardo Osorio"             "Gerardo Torrado"
[149] "Israel Castro"              "Guillermo Franco"
[151] "Cuauhtemoc Blanco"          "Paul Aguilar"
[153] "Javier Hernandez"           "Efrain Juarez"
[155] "Jonny Magallon"             "Jorge Torres Nilo"
[157] "Adolfo Bautista"            "Alberto Medina"
[159] "Luis Ernesto Michel"        "John Heitinga"
[161] "Giovanni van Bronckhorst"   "Andre Ooijer"
[163] "Mark Paston"                "Ben Sigmund"
[165] "Tony Lochhead"              "Ivan Vicelich"
[167] "Simon Elliott"              "Tim Brown"
[169] "Shane Smeltz"               "Chris Killen"
[171] "Leo Bertos"                 "Glen Moss"
[173] "Andy Barron"                "Michael McGlinchey"
[175] "Aaron Clapham"              "Dave Mulligan"
[177] "Andrew Boyens"              "Jeremy Christie"
[179] "Jeremy Brockie"             "James Bannatyne"
[181] "Nwankwo Kanu"               "Danny Shittu"
[183] "not applicable Yakubu"      "Sani Kaita"
[185] "Austin Ejide"               "Chidi Odiah"
[187] "Dickson Etuhu"              "Elderson Echiejile"
[189] "Dele Aiyenugba"             "Myong-guk Ri"
[191] "Jong-hyok Cha"              "Jun-il Ri"
[193] "Nam-chol Pak"               "Kwang-chon Ri"
[195] "Kum-il Kim"                 "Chol-hyok An"
[197] "Yun-nam Ji"                 "Tae-se Jong"
[199] "Yong-jo Hong"               "In-guk Mun"
[201] "Kum-chol Choe"              "Chol-jin Pak"
[203] "Nam-Chol Pak"               "Yong-jun Kim"
[205] "Song-chol Nam"              "Yong-hak An"
[207] "Myong-gil Kim"              "Chol-myong Ri"
[209] "Myong-won Kim"              "Kwang-hyok Ri"
[211] "Kyong-il Kim"               "Il-gwan Jong"
[213] "Justo Villar"               "Dario Veron"
[215] "Claudio Morel"              "Denis Caniza"
[217] "Julio Cesar Caceres"        "Carlos Bonet"
[219] "Edgar Benitez"              "Jonathan Santana"
[221] "Diego Barreto"              "Enrique Vera"
[223] "Paulo da Silva"             "Victor Caceres"
[225] "Aureliano Torres"           "Nestor Ortigoza"
[227] "Aldo Bobadilla"             "Rodolfo Gamarra"
[229] "not applicable Eduardo"     "not applicable Rolando"
[231] "not applicable Duda"        "not applicable Liedson"
[233] "not applicable Danny"       "not applicable Simao"
[235] "not applicable Beto"        "not applicable Miguel"
[237] "not applicable Pepe"        "not applicable Tiago"
[239] "not applicable Deco"        "Nemanja Vidic"
[241] "Nenad Milijas"              "Bojan Isailovic"
[243] "Nikola Zigic"               "Dragan Mrda"
[245] "Andelko Duricic"            "Zdeno Strba"
[247] "Jan Kozak"                  "Kamil Kopunek"
[249] "Martin Petras"              "Marko Suler"
[251] "Nejc Pecnik"                "Zlatan Ljubijankic"
[253] "Milivoje Novakovic"         "Jasmin Handanovic"
[255] "Zlatko Dedic"               "Aleksander Seliga"
[257] "Suad Filekovic"             "Andrej Komac"
[259] "Matej Mavric"               "Moeneeb Josephs"
[261] "Siboniso Gaxa"              "Tsepo Masilela"
[263] "Aaron Mokoena"              "MacBeth Sibaya"
[265] "Katlego Mphela"             "Teko Modise"
[267] "Reneilwe Letsholonyane"     "Matthew Booth"
[269] "Lucas Thwala"               "Itumeleng Khune"
[271] "Bernard Parker"             "Siyabonga Nomvethe"
[273] "Surprise Moriri"            "Siyabonga Sangweni"
[275] "Shu-Aib Walters"            "Thanduyise Khuboni"
[277] "Woon-jae Lee"               "Beom-seok Oh"
[279] "Hyung-il Kim"               "Yong-hyung Cho"
[281] "Nam-il Kim"                 "Jung-woo Kim"
[283] "Jung-hwan Ahn"              "Seung-yeoul Lee"
[285] "Young-pyo Lee"              "Jung-soo Lee"
[287] "Ki-hun Yeom"                "Dong-gook Lee"
[289] "Young-kwang Kim"            "Min-soo Kang"
[291] "not applicable Xavi"        "not applicable Pedro"
[293] "Ludovic Magnin"             "Benjamin Huggel"
[295] "Alexander Frei"             "Blaise Nkufo"
[297] "Marco Wolfli"               "Stephane Grichting"
[299] "Marco Padalino"             "Hakan Yakin"
[301] "Albert Bunjaku"             "Carlos Bocanegra"
[303] "Steve Cherundolo"           "DaMarcus Beasley"
[305] "Herculez Gomez"             "Landon Donovan"
[307] "Stuart Holden"              "Jonathan Bornstein"
[309] "Ricardo Clark"              "Edson Buddle"
[311] "Jay DeMerit"                "Jose Francisco Torres"
[313] "Robbie Findley"             "Benny Feilhaber"
[315] "Marcus Hahnemann"           "Mauricio Victorino"
[317] "Sebastian Eguren"           "Diego Forlan"
[319] "Sebastian Abreu"            "Maxi Pereira"
[321] "Andres Scotti"              "Martin Silva"
[323] "Cedric Si Mohamed"          "Hillal Soudani"
[325] "Mohamed Zemmamouche"        "Liassine Cadamuro-Bentaiba"
[327] "Abdelmoumene Djabou"        "Agustin Orion"
[329] "Ricky Alvarez"              "Matthew Spiranovic"
[331] "Bailey Wright"              "James Holland"
[333] "Matt McKay"                 "Alex Wilkinson"
[335] "Jasmin Fejzic"              "Asmir Avdukic"
[337] "not applicable Jefferson"   "not applicable Fernandinho"
[339] "not applicable Marcelo"     "not applicable Hulk"
[341] "not applicable Paulinho"    "not applicable Fred"
[343] "not applicable Neymar"      "not applicable Oscar"
[345] "not applicable Dante"       "not applicable Maxwell"
[347] "not applicable Henrique"    "not applicable Hernanes"
[349] "not applicable Willian"     "not applicable Bernard"
[351] "not applicable Jo"          "not applicable Victor"
[353] "Loic Feudjou"               "Cedric Djeugoue"
[355] "Eugenio Mena"               "Cristopher Toselli"
[357] "Jose Manuel Rojas"          "Jose Pablo Fuenzalida"
[359] "Johnny Herrera"             "Alexander Mejia"
[361] "Eder Alvarez Balanta"       "Juan Camilo Zuniga"
[363] "Faryd Mondragon"            "Carlos Valdes"
[365] "Jhonny Acosta"              "Michael Umana"
[367] "David Myrie"                "Michael Barrantes"
[369] "Waylon Francis"             "Oscar Granados"
[371] "Randall Brenes"             "Patrick Pemberton"
[373] "Roy Miller"                 "Diego Calvo"
[375] "Marco Urena"                "Jose Miguel Cubero"
[377] "Daniel Cambronero"          "not applicable Sammir"
[379] "Maximo Banguera"            "Jorge Guagua"
[381] "Frickson Erazo"             "Edison Mendez"
[383] "Joao Rojas"                 "Walter Ayovi"
[385] "Adrian Bone"                "Oswaldo Minda"
[387] "Michael Arroyo"             "Jaime Ayovi"
[389] "Oscar Bagui"                "Luis Saritama"
[391] "Fidel Martinez"             "Gabriel Achilier"
[393] "Alexander Dominguez"        "Stephen Adams"
[395] "Emmanuel Agyemang-Badu"     "Adam Larsen Kwarasey"
[397] "Rashid Sumaila"             "Fatau Dauda"
[399] "Abdul Majeed Waris"         "Harrison Afful"
[401] "Giorgos Tzavellas"          "Kostas Manolas"
[403] "Kostas Mitroglou"           "Jose Holebas"
[405] "Juan Pablo Montes"          "Juan Carlos Garcia"
[407] "Jerry Bengtson"             "Edder Delgado"
[409] "Rony Martinez"              "Luis Garrido"
[411] "Marvin Chavez"              "Rahman Ahmadi"
[413] "Khosro Heydari"             "Jalal Hosseini"
[415] "Amir Hossein Sadeghi"       "Javad Nekounam"
[417] "Reza Haghighi"              "Ghasem Haddadifar"
[419] "Hossein Mahini"             "Andranik Teymourian"
[421] "Pejman Montazeri"           "Ahmad Alenemeh"
[423] "Bakhtiar Rahmani"           "Hashem Beikzadeh"
[425] "Steven Beitashour"          "Mehrdad Pooladi"
[427] "Sylvain Gbohouo"            "Serey Die"
[429] "Sayouba Mande"              "Yoichiro Kakitani"
[431] "Masahiko Inoha"             "Manabu Saito"
[433] "Jose de Jesus Corona"       "Alfredo Talavera"
[435] "Miguel Angel Ponce"         "Isaac Brizuela"
[437] "Oribe Peralta"              "Jose Juan Vazquez"
[439] "Azubuike Egwuekwe"          "John Obi Mikel"
[441] "Kunle Odunlami"             "Michael Babatunde"
[443] "Chigozie Agbim"             "not applicable Vieirinha"
[445] "not applicable Eder"        "not applicable Nani"
[447] "Aleksei Kozlov"             "Georgi Shchennikov"
[449] "Sergei Ignashevich"         "Andrei Semyonov"
[451] "Yuri Lodygin"               "Vasili Berezutski"
[453] "Yuri Zhirkov"               "Viktor Fayzulin"
[455] "Aleksei Ionov"              "Andrey Yeshchenko"
[457] "Dmitri Kombarov"            "Chang-soo Kim"
[459] "Suk-young Yun"              "Tae-hwi Kwak"
[461] "Dae-sung Ha"                "Keun-ho Lee"
[463] "Kook-young Han"             "Jong-woo Park"
[465] "Shin-wook Kim"              "Joo-ho Park"
[467] "Bum-young Lee"              "not applicable Juanfran"
[469] "not applicable Koke"        "Matt Besler"
[471] "Brad Davis"                 "Kyle Beckerman"
[473] "Chris Wondolowski"          "Graham Zusi"
[475] "Nick Rimando"               "Rodrigo Munoz"
[477] "Jose Gimenez"               "James Meredith"
[479] "Dimitri Petratos"           "not applicable Alisson"
[481] "not applicable Miranda"     "not applicable Casemiro"
[483] "not applicable Marquinhos"  "not applicable Danilo"
[485] "not applicable Cassio"      "not applicable Taison"
[487] "not applicable Fagner"      "not applicable Ederson"
[489] "Oscar Murillo"              "Mateus Uribe"
[491] "Farid Diaz"                 "Jose Fernando Cuadrado"
[493] "Daniel Colindres"           "Johan Venegas"
[495] "David Guzman"               "Kenner Gutierrez"
[497] "Leonel Moreira"             "Jens Stryger Larsen"
[499] "Essam El Hadary"            "Omar Gaber"
[501] "Ahmed Hegazi"               "Ahmed Fathy"
[503] "not applicable Kahraba"     "Ayman Ashraf"
[505] "Mohamed Abdel Shafy"        "Mahmoud Hamdy"
[507] "Sherif Ekramy"              "not applicable Shikabala"
[509] "Abdallah El Said"           "Saad Samir"
[511] "not applicable Trezeguet"   "Hannes THor Halldorsson"
[513] "Birkir Mar Saevarsson"      "Bjorn Bergmann Sigurdarson"
[515] "Holmar Orn Eyjolfsson"      "Hordur Bjorgvin Magnusson"
[517] "Jon Dadi Bodvarsson"        "Mehdi Torabi"
[519] "Rouzbeh Cheshmi"            "Mohammad Rashid Mazaheri"
[521] "Mohammad Reza Khanzadeh"    "Tomoaki Makino"
[523] "Hugo Ayala"                 "Jesus Manuel Corona"
[525] "Munir Mohamedi"             "Mbark Boussoufa"
[527] "Aziz Bouhaddouz"            "Ahmed Reda Tagnaouti"
[529] "Mehdi Carcela"              "Ikechukwu Ezenwa"
[531] "Brian Idowu"                "Shehu Abdullahi"
[533] "Simeon Nwankwo"             "Daniel Akpeyi"
[535] "Jaime Penedo"               "Michael Amir Murillo"
[537] "Harold Cummings"            "Gabriel Gomez"
[539] "Blas Perez"                 "Edgar Barcenas"
[541] "Gabriel Torres"             "Armando Cooper"
[543] "Adolfo Machado"             "Valentin Pimentel"
[545] "Erick Davis"                "Luis Ovalle"
[547] "Luis Tejada"                "Ricardo Avila"
[549] "Felipe Baloy"               "Aldo Corzo"
[551] "Raul Ruidiaz"               "Christian Ramos"
[553] "Jose Carvallo"              "Nilson Loyola"
[555] "Bartosz Bialkowski"         "not applicable Cedric"
[557] "Daler Kuzyayev"             "Yury Gazinsky"
[559] "Fyodor Smolov"              "Andrey Lunyov"
[561] "Fyodor Kudryashov"          "Aleksei Miranchuk"
[563] "Aleksandr Yerokhin"         "Mansoor Al-Harbi"
[565] "Ali Al-Bulaihi"             "Omar Hawsawi"
[567] "Mohammed Al-Breik"          "Mohammad Al-Sahlawi"
[569] "Abdulmalek Al-Khaibri"      "Housain Al-Mogahwi"
[571] "Taisir Al-Jassim"           "Muhannad Assiri"
[573] "Yasser Al-Mosailem"         "Motaz Hawsawi"
[575] "Kara Mbodji"                "Mame Biram Diouf"
[577] "Khadim N'Diaye"             "Ban-suk Oh"
[579] "Young-sun Yun"              "Hyun-soo Jang"
[581] "Yo-han Go"                  "Dani Carvajal"
[583] "not applicable Nacho"       "not applicable Saul"
[585] "not applicable Rodrigo"     "not applicable Thiago"
[587] "not applicable Isco"        "Farouk Ben Mustapha"
[589] "Rami Bedoui"                "Ali Maaloul"
[591] "Mohamed Amine Ben Amor"     "Ahmed Khalil"
[593] "Aymen Mathlouthi"           "Ghailene Chaalali"
[595] "Hamdi Nagguez"              "Giorgian De Arrascaeta"
[597] "Martin Campana"             "Cameron Devlin"
[599] "not applicable Richarlison" "not applicable Raphinha"
[601] "not applicable Weverton"    "not applicable Fabinho"
[603] "not applicable Antony"      "not applicable Rodrygo"
[605] "not applicable Bremer"      "Jerome Ngom Mbekeli"
[607] "Moumi Ngamaleu"             "Georges-Kevin Nkoudou"
[609] "Andre-Frank Zambo Anguissa" "Samuel Gouet"
[611] "Nouhou Tolo"                "Souaibou Marou"
[613] "Liam Fraser"                "Lucas Cavallini"
[615] "Daniel Chacon"              "Keysher Fuller"
[617] "Gerson Torres"              "Douglas Lopez"
[619] "William Pacho"              "Romario Ibarra"
[621] "Michael Estrada"            "Xavier Arreaga"
[623] "Sebas Mendez"               "Djorkaeff Reasco"
[625] "Lawrence Ati-Zigi"          "Abdul Fatawu Issahaku"
[627] "Ibrahim Danlad"             "Abdul Manaf Nurudeen"
[629] "Baba Rahman"                "Shojae Khalilzadeh"
[631] "Hossein Kanaanizadegan"     "Ahmad Nourollahi"
[633] "Hossein Hosseini"           "Abolfazl Jalali"
[635] "Ilias Chair"                "Bilal El Khannous"
[637] "Badr Benoun"                "Yahya Jabrane"
[639] "not applicable Vitinha"     "not applicable Otavio"
[641] "Saad Al-Sheeb"              "not applicable Ro-Ro"
[643] "Abdulaziz Hatem"            "Ali Assadalla"
[645] "Hassan Al-Haydos"           "Musab Kheder"
[647] "Homam Ahmed"                "Ismaeel Mohammad"
[649] "Khalid Muneer"              "Salem Al-Hajri"
[651] "Yousef Hassan"              "Naif Al-Hadhrami"
[653] "Mostafa Meshaal"            "Mohammed Al-Rubaie"
[655] "Abdulellah Al-Malki"        "Hassan Al-Tambakti"
[657] "Abdulrahman Al-Aboud"       "Moussa N'Diaye"
[659] "Moustapha Name"             "Srdan Babic"
[661] "Filip Duricic"              "Yoon Jong-gyu"
[663] "Kim Jin-su"                 "Kim Min-jae"
[665] "Hwang In-beom"              "Paik Seung-ho"
[667] "Cho Gue-sung"               "Song Bum-keun"
[669] "Son Jun-ho"                 "Kim Moon-hwan"
[671] "Hwang Ui-jo"                "Na Sang-ho"
[673] "Lee Kang-in"                "Kwon Kyung-won"
[675] "Kwon Chang-hoon"            "Kim Tae-hwan"
[677] "Cho Yu-min"                 "Jeong Woo-yeong"
[679] "Song Min-kyu"               "not applicable Gavi"
[681] "not applicable Rodri"       "not applicable Pedri"
[683] "Bilel Ifa"                  "Hannibal Mejbri"
[685] "Taha Yassine Khenissi"      "Mohamed Ali Ben Romdhane"
[687] "Seifeddine Jaziri"          "Anis Ben Slimane"
[689] "Sebastian Sosa"             "Joe Morrell"
[691] "Jonny Williams"

Our set difference went down 165 observations! Lets keep trouble shooting.

There seems to be a few players with "not applicable" as their first name. Let's explore this issue.

In [252]:
worldcup_players %>%
    filter(grepl("not applicable", full_name)) %>%
        print(n=5)

worldcup_players %>%
    filter(grepl("not applicable", full_name)) %>%
        distinct(full_name) %>%
            nrow()

# A tibble: 88 x 2
  player_id full_name
  <chr>     <chr>
1 P-94551   not applicable Maicon
2 P-42918   not applicable Lucio
3 P-98607   not applicable Juan
4 P-78264   not applicable Elano
5 P-58388   not applicable Kaka
# i 83 more rows

[1] 85

In [253]:
readRDS(here("1.DataCleaning-R", "Data", "RDS", "FullRoster.rds")) %>%
    filter(given_name== "not applicable") %>%
        print(n=10)

# A tibble: 113 x 9
   tournament_id team_name team_id team_code player_id family_name   given_name
   <chr>         <chr>     <chr>   <chr>     <chr>     <chr>         <chr>
 1 WC-2010       Brazil    T-09    BRA       P-94551   "Maicon"      not applic~
 2 WC-2010       Brazil    T-09    BRA       P-42918   "L\u00facio"  not applic~
 3 WC-2010       Brazil    T-09    BRA       P-98607   "Juan"        not applic~
 4 WC-2010       Brazil    T-09    BRA       P-78264   "Elano"       not applic~
 5 WC-2010       Brazil    T-09    BRA       P-58388   "Kak\u00e1"   not applic~
 6 WC-2010       Brazil    T-09    BRA       P-13354   "Robinho"     not applic~
 7 WC-2010       Brazil    T-09    BRA       P-32968   "Luis\u00e3o" not applic~
 8 WC-2010       Brazil    T-09    BRA       P-30363   "Gilberto"    not applic~
 9 WC-2010       Brazil    T-09    BRA       P-74066   "Josu\u00e9"  not applic~
10 WC-2010       Brazil    T-09    BRA       P-86499   "Ramires"     not applic~
# i 103 more rows
# i 2 more variables: position_code <chr>, full_name <chr>

In [254]:
#Let's check some of these players on the Kaggle dataset
set.seed(123)

player_names %>% 
    select(name) %>%
        filter(grepl("Maicon|Elano|Rodri", name)) %>%
            slice_sample(n=10)

   name
1  Ramiro Ruiz Rodriguez
2  Rodrigo Melro
3  Fer Rodriguez
4  Jay Rodriguez
5  Rodrigo Caseres
6  Rodrigo Varanda
7  Diego Rodriguez
8  Rodrigo Alirio
9  Rodrigo
10 Javi Rodriguez

Some of the players seem to be only reffered to by one name in both datasets. Lets take out the not applicable and see improvements.

In [255]:
remove_not_applicable <- function(x) {
  gsub("not applicable\\s+", "", x)
}

worldcup_players <- worldcup_players %>%
  mutate(full_name = remove_not_applicable(full_name))

length(setdiff(worldcup_players$full_name, player_names$name))
length(worldcup_players$full_name)
setdiff(worldcup_players$full_name, player_names$name)

[1] 617

[1] 2379

  [1] "Lounes Gaouaoui"            "Madjid Bougherra"
  [3] "Nadir Belhadj"              "Antar Yahia"
  [5] "Yazid Mansouri"             "Rafik Saifi"
  [7] "Habib Bellaid"              "Abdelkader Laifaoui"
  [9] "Karim Ziani"                "Faouzi Chaouchi"
 [11] "Diego Pozo"                 "Clemente Rodriguez"
 [13] "Mario Bolatti"              "Gabriel Heinze"
 [15] "Juan Sebastian Veron"       "Ariel Garce"
 [17] "Martin Palermo"             "Maxi Rodriguez"
 [19] "Lucas Neill"                "Tim Cahill"
 [21] "Jason Culina"               "Michael Beauchamp"
 [23] "Brett Emerton"              "Joshua Kennedy"
 [25] "Harry Kewell"               "Scott Chipperfield"
 [27] "Vince Grella"               "Eugene Galekovic"
 [29] "Richard Garcia"             "David Carney"
 [31] "Dario Vidosic"              "Mark Bresciano"
 [33] "Elano"                      "Gilberto Silva"
 [35] "Luis Fabiano"               "Kleberson"
 [37] "Nilmar"                     "Doni"
 [39] "Grafite"                    "Nicolas Nkoulou"
 [41] "Rigobert Song"              "Geremi"
 [43] "Achille Emana"              "Eric Maxim Choupo-Moting"
 [45] "Souleymanou Hamidou"        "Mohammadou Idrissou"
 [47] "Guy N'dy Assembe"           "Ismael Fuentes"
 [49] "Waldo Ponce"                "Humberto Suazo"
 [51] "Jorge Valdivia"             "Miguel Pinto"
 [53] "Gonzalo Fierro"             "Rodrigo Millar"
 [55] "Esteban Paredes"            "Luis Marin"
 [57] "Jesper Gronkjaer"           "Jon Dahl Tomasson"
 [59] "David James"                "Robert Green"
 [61] "Stephen Warnock"            "Ledley King"
 [63] "Emile Heskey"               "Thierry Henry"
 [65] "Arne Friedrich"             "Hans-Jorg Butt"
 [67] "Daniel Agyei"               "Hans Sarpei"
 [69] "John Paintsil"              "Stephen Appiah"
 [71] "Prince Tagoe"               "Isaac Vorsah"
 [73] "Stephen Ahorlu"             "Lee Addy"
 [75] "Richard Kingson"            "Kostas Chalkias"
 [77] "Giourkas Seitaridis"        "Nikos Spyropoulos"
 [79] "Angelos Charisteas"         "Giorgos Karagounis"
 [81] "Dimitris Salpingidis"       "Vasilis Torosidis"
 [83] "Sotirios Kyrgiakos"         "Kostas Katsouranis"
 [85] "Sakis Prittas"              "Ricardo Canales"
 [87] "Osman Chavez"               "Johnny Palacios"
 [89] "Victor Bernardez"           "Hendry Thomas"
 [91] "Ramon Nunez"                "Carlos Pavon"
 [93] "Jerry Palacios"             "David Suazo"
 [95] "Georgie Welcome"            "Boniek Garcia"
 [97] "Walter Martinez"            "Mauricio Sabillon"
 [99] "Edgar Alvarez"              "Noel Valladares"
[101] "Danilo Turcios"             "Amado Guevara"
[103] "Donis Escober"              "Sergio Mendoza"
[105] "Fabio Cannavaro"            "Gennaro Gattuso"
[107] "Mauro Camoranesi"           "Gianluca Zambrotta"
[109] "Boubacar Barry"             "Cheick Tiote"
[111] "Aruna Dindane"              "Aristide Zogbo"
[113] "Abdul Kader Keita"          "Daniel Yeboah"
[115] "Seigo Narazaki"             "Yuki Abe"
[117] "Yuichi Komano"              "Marcus Tulio Tanaka"
[119] "Yasuhito Endo"              "Daisuke Matsui"
[121] "Shunsuke Nakamura"          "Keiji Tamada"
[123] "Kisho Yano"                 "Daiki Iwamasa"
[125] "Kengo Nakamura"             "Yasuyuki Konno"
[127] "Yoshito Okubo"              "Junichi Inamoto"
[129] "Yuji Nakazawa"              "Yoshikatsu Kawaguchi"
[131] "Oscar Perez"                "Francisco Javier Rodriguez"
[133] "Carlos Salcido"             "Rafael Marquez"
[135] "Ricardo Osorio"             "Gerardo Torrado"
[137] "Israel Castro"              "Guillermo Franco"
[139] "Cuauhtemoc Blanco"          "Paul Aguilar"
[141] "Javier Hernandez"           "Efrain Juarez"
[143] "Jonny Magallon"             "Jorge Torres Nilo"
[145] "Adolfo Bautista"            "Alberto Medina"
[147] "Luis Ernesto Michel"        "John Heitinga"
[149] "Giovanni van Bronckhorst"   "Andre Ooijer"
[151] "Mark Paston"                "Ben Sigmund"
[153] "Tony Lochhead"              "Ivan Vicelich"
[155] "Simon Elliott"              "Tim Brown"
[157] "Shane Smeltz"               "Chris Killen"
[159] "Leo Bertos"                 "Glen Moss"
[161] "Andy Barron"                "Michael McGlinchey"
[163] "Aaron Clapham"              "Dave Mulligan"
[165] "Andrew Boyens"              "Jeremy Christie"
[167] "Jeremy Brockie"             "James Bannatyne"
[169] "Nwankwo Kanu"               "Danny Shittu"
[171] "Yakubu"                     "Sani Kaita"
[173] "Austin Ejide"               "Chidi Odiah"
[175] "Dickson Etuhu"              "Elderson Echiejile"
[177] "Dele Aiyenugba"             "Myong-guk Ri"
[179] "Jong-hyok Cha"              "Jun-il Ri"
[181] "Nam-chol Pak"               "Kwang-chon Ri"
[183] "Kum-il Kim"                 "Chol-hyok An"
[185] "Yun-nam Ji"                 "Tae-se Jong"
[187] "Yong-jo Hong"               "In-guk Mun"
[189] "Kum-chol Choe"              "Chol-jin Pak"
[191] "Nam-Chol Pak"               "Yong-jun Kim"
[193] "Song-chol Nam"              "Yong-hak An"
[195] "Myong-gil Kim"              "Chol-myong Ri"
[197] "Myong-won Kim"              "Kwang-hyok Ri"
[199] "Kyong-il Kim"               "Il-gwan Jong"
[201] "Justo Villar"               "Dario Veron"
[203] "Claudio Morel"              "Denis Caniza"
[205] "Julio Cesar Caceres"        "Carlos Bonet"
[207] "Edgar Benitez"              "Jonathan Santana"
[209] "Diego Barreto"              "Enrique Vera"
[211] "Paulo da Silva"             "Victor Caceres"
[213] "Aureliano Torres"           "Nestor Ortigoza"
[215] "Aldo Bobadilla"             "Rodolfo Gamarra"
[217] "Miguel"                     "Deco"
[219] "Nemanja Vidic"              "Nenad Milijas"
[221] "Bojan Isailovic"            "Nikola Zigic"
[223] "Dragan Mrda"                "Andelko Duricic"
[225] "Zdeno Strba"                "Jan Kozak"
[227] "Kamil Kopunek"              "Martin Petras"
[229] "Marko Suler"                "Nejc Pecnik"
[231] "Zlatan Ljubijankic"         "Milivoje Novakovic"
[233] "Jasmin Handanovic"          "Zlatko Dedic"
[235] "Aleksander Seliga"          "Suad Filekovic"
[237] "Andrej Komac"               "Matej Mavric"
[239] "Moeneeb Josephs"            "Siboniso Gaxa"
[241] "Tsepo Masilela"             "Aaron Mokoena"
[243] "MacBeth Sibaya"             "Katlego Mphela"
[245] "Teko Modise"                "Reneilwe Letsholonyane"
[247] "Matthew Booth"              "Lucas Thwala"
[249] "Itumeleng Khune"            "Bernard Parker"
[251] "Siyabonga Nomvethe"         "Surprise Moriri"
[253] "Siyabonga Sangweni"         "Shu-Aib Walters"
[255] "Thanduyise Khuboni"         "Woon-jae Lee"
[257] "Beom-seok Oh"               "Hyung-il Kim"
[259] "Yong-hyung Cho"             "Nam-il Kim"
[261] "Jung-woo Kim"               "Jung-hwan Ahn"
[263] "Seung-yeoul Lee"            "Young-pyo Lee"
[265] "Jung-soo Lee"               "Ki-hun Yeom"
[267] "Dong-gook Lee"              "Young-kwang Kim"
[269] "Min-soo Kang"               "Ludovic Magnin"
[271] "Benjamin Huggel"            "Alexander Frei"
[273] "Blaise Nkufo"               "Marco Wolfli"
[275] "Stephane Grichting"         "Marco Padalino"
[277] "Hakan Yakin"                "Albert Bunjaku"
[279] "Carlos Bocanegra"           "Steve Cherundolo"
[281] "DaMarcus Beasley"           "Herculez Gomez"
[283] "Landon Donovan"             "Stuart Holden"
[285] "Jonathan Bornstein"         "Ricardo Clark"
[287] "Edson Buddle"               "Jay DeMerit"
[289] "Jose Francisco Torres"      "Robbie Findley"
[291] "Benny Feilhaber"            "Marcus Hahnemann"
[293] "Mauricio Victorino"         "Sebastian Eguren"
[295] "Diego Forlan"               "Sebastian Abreu"
[297] "Maxi Pereira"               "Andres Scotti"
[299] "Martin Silva"               "Cedric Si Mohamed"
[301] "Hillal Soudani"             "Mohamed Zemmamouche"
[303] "Liassine Cadamuro-Bentaiba" "Abdelmoumene Djabou"
[305] "Agustin Orion"              "Ricky Alvarez"
[307] "Matthew Spiranovic"         "Bailey Wright"
[309] "James Holland"              "Matt McKay"
[311] "Alex Wilkinson"             "Jasmin Fejzic"
[313] "Asmir Avdukic"              "Loic Feudjou"
[315] "Cedric Djeugoue"            "Eugenio Mena"
[317] "Cristopher Toselli"         "Jose Manuel Rojas"
[319] "Jose Pablo Fuenzalida"      "Johnny Herrera"
[321] "Alexander Mejia"            "Eder Alvarez Balanta"
[323] "Juan Camilo Zuniga"         "Faryd Mondragon"
[325] "Carlos Valdes"              "Jhonny Acosta"
[327] "Michael Umana"              "David Myrie"
[329] "Michael Barrantes"          "Waylon Francis"
[331] "Oscar Granados"             "Randall Brenes"
[333] "Patrick Pemberton"          "Roy Miller"
[335] "Diego Calvo"                "Marco Urena"
[337] "Jose Miguel Cubero"         "Daniel Cambronero"
[339] "Maximo Banguera"            "Jorge Guagua"
[341] "Frickson Erazo"             "Edison Mendez"
[343] "Joao Rojas"                 "Walter Ayovi"
[345] "Adrian Bone"                "Oswaldo Minda"
[347] "Michael Arroyo"             "Jaime Ayovi"
[349] "Oscar Bagui"                "Luis Saritama"
[351] "Fidel Martinez"             "Gabriel Achilier"
[353] "Alexander Dominguez"        "Stephen Adams"
[355] "Emmanuel Agyemang-Badu"     "Adam Larsen Kwarasey"
[357] "Rashid Sumaila"             "Fatau Dauda"
[359] "Abdul Majeed Waris"         "Harrison Afful"
[361] "Giorgos Tzavellas"          "Kostas Manolas"
[363] "Kostas Mitroglou"           "Jose Holebas"
[365] "Juan Pablo Montes"          "Juan Carlos Garcia"
[367] "Jerry Bengtson"             "Edder Delgado"
[369] "Rony Martinez"              "Luis Garrido"
[371] "Marvin Chavez"              "Rahman Ahmadi"
[373] "Khosro Heydari"             "Jalal Hosseini"
[375] "Amir Hossein Sadeghi"       "Javad Nekounam"
[377] "Reza Haghighi"              "Ghasem Haddadifar"
[379] "Hossein Mahini"             "Andranik Teymourian"
[381] "Pejman Montazeri"           "Ahmad Alenemeh"
[383] "Bakhtiar Rahmani"           "Hashem Beikzadeh"
[385] "Steven Beitashour"          "Mehrdad Pooladi"
[387] "Sylvain Gbohouo"            "Serey Die"
[389] "Sayouba Mande"              "Yoichiro Kakitani"
[391] "Masahiko Inoha"             "Manabu Saito"
[393] "Jose de Jesus Corona"       "Alfredo Talavera"
[395] "Miguel Angel Ponce"         "Isaac Brizuela"
[397] "Oribe Peralta"              "Jose Juan Vazquez"
[399] "Azubuike Egwuekwe"          "John Obi Mikel"
[401] "Kunle Odunlami"             "Michael Babatunde"
[403] "Chigozie Agbim"             "Aleksei Kozlov"
[405] "Georgi Shchennikov"         "Sergei Ignashevich"
[407] "Andrei Semyonov"            "Yuri Lodygin"
[409] "Vasili Berezutski"          "Yuri Zhirkov"
[411] "Viktor Fayzulin"            "Aleksei Ionov"
[413] "Andrey Yeshchenko"          "Dmitri Kombarov"
[415] "Chang-soo Kim"              "Suk-young Yun"
[417] "Tae-hwi Kwak"               "Dae-sung Ha"
[419] "Keun-ho Lee"                "Kook-young Han"
[421] "Jong-woo Park"              "Shin-wook Kim"
[423] "Joo-ho Park"                "Bum-young Lee"
[425] "Matt Besler"                "Brad Davis"
[427] "Kyle Beckerman"             "Chris Wondolowski"
[429] "Graham Zusi"                "Nick Rimando"
[431] "Rodrigo Munoz"              "Jose Gimenez"
[433] "James Meredith"             "Dimitri Petratos"
[435] "Oscar Murillo"              "Mateus Uribe"
[437] "Farid Diaz"                 "Jose Fernando Cuadrado"
[439] "Daniel Colindres"           "Johan Venegas"
[441] "David Guzman"               "Kenner Gutierrez"
[443] "Leonel Moreira"             "Jens Stryger Larsen"
[445] "Essam El Hadary"            "Omar Gaber"
[447] "Ahmed Hegazi"               "Ahmed Fathy"
[449] "Ayman Ashraf"               "Mohamed Abdel Shafy"
[451] "Mahmoud Hamdy"              "Sherif Ekramy"
[453] "Abdallah El Said"           "Saad Samir"
[455] "Hannes THor Halldorsson"    "Birkir Mar Saevarsson"
[457] "Bjorn Bergmann Sigurdarson" "Holmar Orn Eyjolfsson"
[459] "Hordur Bjorgvin Magnusson"  "Jon Dadi Bodvarsson"
[461] "Mehdi Torabi"               "Rouzbeh Cheshmi"
[463] "Mohammad Rashid Mazaheri"   "Mohammad Reza Khanzadeh"
[465] "Tomoaki Makino"             "Hugo Ayala"
[467] "Jesus Manuel Corona"        "Munir Mohamedi"
[469] "Mbark Boussoufa"            "Aziz Bouhaddouz"
[471] "Ahmed Reda Tagnaouti"       "Mehdi Carcela"
[473] "Ikechukwu Ezenwa"           "Brian Idowu"
[475] "Shehu Abdullahi"            "Simeon Nwankwo"
[477] "Daniel Akpeyi"              "Jaime Penedo"
[479] "Michael Amir Murillo"       "Harold Cummings"
[481] "Gabriel Gomez"              "Blas Perez"
[483] "Edgar Barcenas"             "Gabriel Torres"
[485] "Armando Cooper"             "Adolfo Machado"
[487] "Valentin Pimentel"          "Erick Davis"
[489] "Luis Ovalle"                "Luis Tejada"
[491] "Ricardo Avila"              "Felipe Baloy"
[493] "Aldo Corzo"                 "Raul Ruidiaz"
[495] "Christian Ramos"            "Jose Carvallo"
[497] "Nilson Loyola"              "Bartosz Bialkowski"
[499] "Cedric"                     "Daler Kuzyayev"
[501] "Yury Gazinsky"              "Fyodor Smolov"
[503] "Andrey Lunyov"              "Fyodor Kudryashov"
[505] "Aleksei Miranchuk"          "Aleksandr Yerokhin"
[507] "Mansoor Al-Harbi"           "Ali Al-Bulaihi"
[509] "Omar Hawsawi"               "Mohammed Al-Breik"
[511] "Mohammad Al-Sahlawi"        "Abdulmalek Al-Khaibri"
[513] "Housain Al-Mogahwi"         "Taisir Al-Jassim"
[515] "Muhannad Assiri"            "Yasser Al-Mosailem"
[517] "Motaz Hawsawi"              "Kara Mbodji"
[519] "Mame Biram Diouf"           "Khadim N'Diaye"
[521] "Ban-suk Oh"                 "Young-sun Yun"
[523] "Hyun-soo Jang"              "Yo-han Go"
[525] "Dani Carvajal"              "Farouk Ben Mustapha"
[527] "Rami Bedoui"                "Ali Maaloul"
[529] "Mohamed Amine Ben Amor"     "Ahmed Khalil"
[531] "Aymen Mathlouthi"           "Ghailene Chaalali"
[533] "Hamdi Nagguez"              "Giorgian De Arrascaeta"
[535] "Martin Campana"             "Cameron Devlin"
[537] "Jerome Ngom Mbekeli"        "Moumi Ngamaleu"
[539] "Georges-Kevin Nkoudou"      "Andre-Frank Zambo Anguissa"
[541] "Samuel Gouet"               "Nouhou Tolo"
[543] "Souaibou Marou"             "Liam Fraser"
[545] "Lucas Cavallini"            "Daniel Chacon"
[547] "Keysher Fuller"             "Gerson Torres"
[549] "Douglas Lopez"              "William Pacho"
[551] "Romario Ibarra"             "Michael Estrada"
[553] "Xavier Arreaga"             "Sebas Mendez"
[555] "Djorkaeff Reasco"           "Lawrence Ati-Zigi"
[557] "Abdul Fatawu Issahaku"      "Ibrahim Danlad"
[559] "Abdul Manaf Nurudeen"       "Baba Rahman"
[561] "Shojae Khalilzadeh"         "Hossein Kanaanizadegan"
[563] "Ahmad Nourollahi"           "Hossein Hosseini"
[565] "Abolfazl Jalali"            "Ilias Chair"
[567] "Bilal El Khannous"          "Badr Benoun"
[569] "Yahya Jabrane"              "Saad Al-Sheeb"
[571] "Ro-Ro"                      "Abdulaziz Hatem"
[573] "Ali Assadalla"              "Hassan Al-Haydos"
[575] "Musab Kheder"               "Homam Ahmed"
[577] "Ismaeel Mohammad"           "Khalid Muneer"
[579] "Salem Al-Hajri"             "Yousef Hassan"
[581] "Naif Al-Hadhrami"           "Mostafa Meshaal"
[583] "Mohammed Al-Rubaie"         "Abdulellah Al-Malki"
[585] "Hassan Al-Tambakti"         "Abdulrahman Al-Aboud"
[587] "Moussa N'Diaye"             "Moustapha Name"
[589] "Srdan Babic"                "Filip Duricic"
[591] "Yoon Jong-gyu"              "Kim Jin-su"
[593] "Kim Min-jae"                "Hwang In-beom"
[595] "Paik Seung-ho"              "Cho Gue-sung"
[597] "Song Bum-keun"              "Son Jun-ho"
[599] "Kim Moon-hwan"              "Hwang Ui-jo"
[601] "Na Sang-ho"                 "Lee Kang-in"
[603] "Kwon Kyung-won"             "Kwon Chang-hoon"
[605] "Kim Tae-hwan"               "Cho Yu-min"
[607] "Jeong Woo-yeong"            "Song Min-kyu"
[609] "Bilel Ifa"                  "Hannibal Mejbri"
[611] "Taha Yassine Khenissi"      "Mohamed Ali Ben Romdhane"
[613] "Seifeddine Jaziri"          "Anis Ben Slimane"
[615] "Sebastian Sosa"             "Joe Morrell"
[617] "Jonny Williams"

Great! 74 out of the 85 players with not applicable were solved with this issue. Lets asses the other 11. We can do this by checking all full names with no spaces in the sett differences list. If we have 11 then we know we got all of the not applicables we're missing.

In [256]:
unmatched_players <- setdiff(worldcup_players$full_name, player_names$name)

one_word_unmatched <- unmatched_players[!grepl("\\s", unmatched_players)]

length(one_word_unmatched)
one_word_unmatched

[1] 11

 [1] "Elano"     "Kleberson" "Nilmar"    "Doni"      "Grafite"   "Geremi"
 [7] "Yakubu"    "Miguel"    "Deco"      "Cedric"    "Ro-Ro"

In [257]:
player_data_clean <- player_data %>%
  mutate(clean_name = remove_not_applicable(remove_accents(name)))

pattern <- paste0("\\b(", paste(one_word_unmatched, collapse = "|"), ")\\b")

player_data_clean %>%
  filter(grepl(pattern, clean_name)) %>%
    filter(!(clean_name %in% worldcup_players$full_name)) %>%
      distinct(name, clean_name, last_season, international_caps) %>%
        filter(last_season>= 2010 & international_caps > 0)

   name                         clean_name            last_season
1  Miguel Lopes                 Miguel Lopes          2024
2  Miguel Lloyd                 Miguel Lloyd          2025
3  Luis Miguel Rodr<U+00ED>guez Luis Miguel Rodriguez 2024
4  C<U+00E9>dric Soares         Cedric Soares         2025
5  C<U+00E9>dric Bakambu        Cedric Bakambu        2025
6  C<U+00E9>dric Hountondji     Cedric Hountondji     2024
7  Cedric Teuchert              Cedric Teuchert       2025
8  Pedro Miguel                 Pedro Miguel          2025
9  Cedric Itten                 Cedric Itten          2025
10 Miguel Almir<U+00F3>n        Miguel Almiron        2025
11 Miguel Lu<U+00ED>s           Miguel Luis           2025
12 C<U+00E9>dric Kipr<U+00E9>   Cedric Kipre          2024
13 C<U+00E9>dric Zesiger        Cedric Zesiger        2025
14 Miguel N<U+00F3>brega        Miguel Nobrega        2025
15 Miguel Reisinho              Miguel Reisinho       2024
16 Miguel de la Fuente          Miguel de la Fuente   2024
17 Miguel Merentiel             Miguel Merentiel      2025
18 Miguel Navarro               Miguel Navarro        2025
19 Miguel Baeza                 Miguel Baeza          2025
20 Miguel Guti<U+00E9>rrez      Miguel Gutierrez      2025
21 Cedric Teguia                Cedric Teguia         2025
22 Miguel Reichmuth             Miguel Reichmuth      2025
23 Miguel <U+00C1>ngel Morro    Miguel Angel Morro    2024
24 Miguel Sandberg              Miguel Sandberg       2025
25 Miguel Rodr<U+00ED>guez      Miguel Rodriguez      2025
26 Miguel Silveira              Miguel Silveira       2024
27 Miguel Menino                Miguel Menino         2024
28 Miguel Monsalve              Miguel Monsalve       2025
29 Miguel G<U+00F3>mez          Miguel Gomez          2025
30 Miguel Ram<U+00ED>rez        Miguel Ramirez        2025
31 C<U+00E9>dric Nuozzi         Cedric Nuozzi         2025
32 Miguel Carvalho              Miguel Carvalho       2025
33 Miguel Chaiwa                Miguel Chaiwa         2025
34 Miguel Perez                 Miguel Perez          2025
35 Mardoch<U+00E9>e Miguel      Mardochee Miguel      2025
36 Miguel Di Pizio              Miguel Di Pizio       2025
37 Miguel <U+00C1>ngel Beltre   Miguel Angel Beltre   2025
38 Miguel Agamez                Miguel Agamez         2024
39 Miguel Marulanda             Miguel Marulanda      2025
   international_caps
1   4
2  47
3   1
4  34
5  67
6  29
7   8
8  99
9  13
10 75
11  6
12  1
13  6
14  2
15  1
16  4
17  1
18 23
19  1
20  2
21  5
22  3
23  2
24  8
25  5
26  1
27  2
28 17
29  3
30  2
31  2
32  2
33 16
34  1
35  6
36  3
37  6
38  9
39  2

After further research Im comfortable assigning the full names to the following players.

In [259]:
worldcup_players <- worldcup_players %>%
  mutate(
    full_name = case_when(
      full_name == "Elano" ~ "Elano Yegen",
      full_name == "Cedric" ~ "Cedric Soares",
      full_name == "Ro-Ro" ~ "Pedro Miguel",
      TRUE ~ full_name
    )
  )

The other few players with one word names we will leave as undefined for now.


I will Have CODEX AI go thorugh the full list of differences and through the full p[layers.csv dataset and find clear minimal gramatical mismatches. I willl then manually check a few to minimize likelihood of errors.

In [261]:
# Obvious name fixes found by comparing unmatched World Cup names to players.csv
# Only includes high-confidence spelling, punctuation, or known single-name expansions.
worldcup_players <- worldcup_players %>%
  mutate(
    full_name = case_when(
      full_name == "Abdulrahman Al-Aboud" ~ "Abdulrahman Al-Oboud",
      full_name == "Eric Maxim Choupo-Moting" ~ "Eric-Maxim Choupo-Moting",
      full_name == "Lawrence Ati-Zigi" ~ "Lawrence Ati Zigi",
      full_name == "Abdulaziz Hatem" ~ "Abdulaziz Hatim",
      full_name == "Abdulellah Al-Malki" ~ "Abdulelah Al-Malki",
      full_name == "Ahmed Hegazi" ~ "Ahmed Hegazy",
      full_name == "Aleksandr Yerokhin" ~ "Aleksandr Erokhin",
      full_name == "Aleksei Ionov" ~ "Aleksey Ionov",
      full_name == "Aleksei Kozlov" ~ "Aleksey Kozlov",
      full_name == "Aleksei Miranchuk" ~ "Aleksey Miranchuk",
      full_name == "Andrey Yeshchenko" ~ "Andrey Eshchenko",
      full_name == "Antar Yahia" ~ "Anthar Yahia",
      full_name == "Bilal El Khannous" ~ "Bilal El Khannouss",
      full_name == "Brian Idowu" ~ "Bryan Idowu",
      full_name == "Cheick Tiote" ~ "Cheik Tiote",
      full_name == "Daler Kuzyayev" ~ "Daler Kuzyaev",
      full_name == "Dimitris Salpingidis" ~ "Dimitrios Salpingidis",
      full_name == "Dmitri Kombarov" ~ "Dmitriy Kombarov",
      full_name == "Erick Davis" ~ "Eric Davis",
      full_name == "Filip Duricic" ~ "Filip Djuricic",
      full_name == "Georgi Shchennikov" ~ "Georgiy Shchennikov",
      full_name == "Giorgian De Arrascaeta" ~ "Giorgian de Arrascaeta",
      full_name == "Guy N'dy Assembe" ~ "Guy Ndy Assembe",
      full_name == "Hannes THor Halldorsson" ~ "Hannes Thor Halldorsson",
      full_name == "Hassan Al-Haydos" ~ "Hasan Al-Haydos",
      full_name == "Marco Urena" ~ "Marcos Urena",
      full_name == "Mateus Uribe" ~ "Matheus Uribe",
      full_name == "Michael Babatunde" ~ "Michel Babatunde",
      full_name == "Sergei Ignashevich" ~ "Sergey Ignashevich",
      full_name == "Sotirios Kyrgiakos" ~ "Sotiris Kyrgiakos",
      full_name == "Srdan Babic" ~ "Srdjan Babic",
      full_name == "Steve Cherundolo" ~ "Steven Cherundolo",
      full_name == "Vasili Berezutski" ~ "Vasiliy Berezutski",
      full_name == "Vasilis Torosidis" ~ "Vasilios Torosidis",
      full_name == "Viktor Fayzulin" ~ "Viktor Faizulin",
      full_name == "William Pacho" ~ "Willian Pacho",
      full_name == "Yuri Lodygin" ~ "Yuriy Lodygin",
      full_name == "Yuri Zhirkov" ~ "Yuriy Zhirkov",
      full_name == "Andrey Lunyov" ~ "Andrey Lunev",
      full_name == "Dani Carvajal" ~ "Daniel Carvajal",
      full_name == "Fyodor Kudryashov" ~ "Fedor Kudryashov",
      full_name == "Fyodor Smolov" ~ "Fedor Smolov",
      full_name == "Georges-Kevin Nkoudou" ~ "Georges-Kevin N'Koudou",
      full_name == "Giorgos Karagounis" ~ "Georgios Karagounis",
      full_name == "Giorgos Tzavellas" ~ "Georgios Tzavellas",
      full_name == "John Heitinga" ~ "Johnny Heitinga",
      full_name == "Joo-ho Park" ~ "Ju-ho Park",
      full_name == "Mbark Boussoufa" ~ "Moubarak Boussoufa",
      full_name == "Nikos Spyropoulos" ~ "Nikolaos Spyropoulos",
      full_name == "Robert Green" ~ "Rob Green",
      full_name == "Yakubu" ~ "Yakubu Aiyegbeni",
      TRUE ~ full_name
    )
  )

In [262]:
length(setdiff(worldcup_players$full_name, player_names$name))
length(worldcup_players$full_name)
setdiff(worldcup_players$full_name, player_names$name)

[1] 563

[1] 2379

  [1] "Lounes Gaouaoui"            "Madjid Bougherra"
  [3] "Nadir Belhadj"              "Yazid Mansouri"
  [5] "Rafik Saifi"                "Habib Bellaid"
  [7] "Abdelkader Laifaoui"        "Karim Ziani"
  [9] "Faouzi Chaouchi"            "Diego Pozo"
 [11] "Clemente Rodriguez"         "Mario Bolatti"
 [13] "Gabriel Heinze"             "Juan Sebastian Veron"
 [15] "Ariel Garce"                "Martin Palermo"
 [17] "Maxi Rodriguez"             "Lucas Neill"
 [19] "Tim Cahill"                 "Jason Culina"
 [21] "Michael Beauchamp"          "Brett Emerton"
 [23] "Joshua Kennedy"             "Harry Kewell"
 [25] "Scott Chipperfield"         "Vince Grella"
 [27] "Eugene Galekovic"           "Richard Garcia"
 [29] "David Carney"               "Dario Vidosic"
 [31] "Mark Bresciano"             "Gilberto Silva"
 [33] "Luis Fabiano"               "Kleberson"
 [35] "Nilmar"                     "Doni"
 [37] "Grafite"                    "Nicolas Nkoulou"
 [39] "Rigobert Song"              "Geremi"
 [41] "Achille Emana"              "Souleymanou Hamidou"
 [43] "Mohammadou Idrissou"        "Ismael Fuentes"
 [45] "Waldo Ponce"                "Humberto Suazo"
 [47] "Jorge Valdivia"             "Miguel Pinto"
 [49] "Gonzalo Fierro"             "Rodrigo Millar"
 [51] "Esteban Paredes"            "Luis Marin"
 [53] "Jesper Gronkjaer"           "Jon Dahl Tomasson"
 [55] "David James"                "Stephen Warnock"
 [57] "Ledley King"                "Emile Heskey"
 [59] "Thierry Henry"              "Arne Friedrich"
 [61] "Hans-Jorg Butt"             "Daniel Agyei"
 [63] "Hans Sarpei"                "John Paintsil"
 [65] "Stephen Appiah"             "Prince Tagoe"
 [67] "Isaac Vorsah"               "Stephen Ahorlu"
 [69] "Lee Addy"                   "Richard Kingson"
 [71] "Kostas Chalkias"            "Giourkas Seitaridis"
 [73] "Angelos Charisteas"         "Kostas Katsouranis"
 [75] "Sakis Prittas"              "Ricardo Canales"
 [77] "Osman Chavez"               "Johnny Palacios"
 [79] "Victor Bernardez"           "Hendry Thomas"
 [81] "Ramon Nunez"                "Carlos Pavon"
 [83] "Jerry Palacios"             "David Suazo"
 [85] "Georgie Welcome"            "Boniek Garcia"
 [87] "Walter Martinez"            "Mauricio Sabillon"
 [89] "Edgar Alvarez"              "Noel Valladares"
 [91] "Danilo Turcios"             "Amado Guevara"
 [93] "Donis Escober"              "Sergio Mendoza"
 [95] "Fabio Cannavaro"            "Gennaro Gattuso"
 [97] "Mauro Camoranesi"           "Gianluca Zambrotta"
 [99] "Boubacar Barry"             "Aruna Dindane"
[101] "Aristide Zogbo"             "Abdul Kader Keita"
[103] "Daniel Yeboah"              "Seigo Narazaki"
[105] "Yuki Abe"                   "Yuichi Komano"
[107] "Marcus Tulio Tanaka"        "Yasuhito Endo"
[109] "Daisuke Matsui"             "Shunsuke Nakamura"
[111] "Keiji Tamada"               "Kisho Yano"
[113] "Daiki Iwamasa"              "Kengo Nakamura"
[115] "Yasuyuki Konno"             "Yoshito Okubo"
[117] "Junichi Inamoto"            "Yuji Nakazawa"
[119] "Yoshikatsu Kawaguchi"       "Oscar Perez"
[121] "Francisco Javier Rodriguez" "Carlos Salcido"
[123] "Rafael Marquez"             "Ricardo Osorio"
[125] "Gerardo Torrado"            "Israel Castro"
[127] "Guillermo Franco"           "Cuauhtemoc Blanco"
[129] "Paul Aguilar"               "Javier Hernandez"
[131] "Efrain Juarez"              "Jonny Magallon"
[133] "Jorge Torres Nilo"          "Adolfo Bautista"
[135] "Alberto Medina"             "Luis Ernesto Michel"
[137] "Giovanni van Bronckhorst"   "Andre Ooijer"
[139] "Mark Paston"                "Ben Sigmund"
[141] "Tony Lochhead"              "Ivan Vicelich"
[143] "Simon Elliott"              "Tim Brown"
[145] "Shane Smeltz"               "Chris Killen"
[147] "Leo Bertos"                 "Glen Moss"
[149] "Andy Barron"                "Michael McGlinchey"
[151] "Aaron Clapham"              "Dave Mulligan"
[153] "Andrew Boyens"              "Jeremy Christie"
[155] "Jeremy Brockie"             "James Bannatyne"
[157] "Nwankwo Kanu"               "Danny Shittu"
[159] "Sani Kaita"                 "Austin Ejide"
[161] "Chidi Odiah"                "Dickson Etuhu"
[163] "Elderson Echiejile"         "Dele Aiyenugba"
[165] "Myong-guk Ri"               "Jong-hyok Cha"
[167] "Jun-il Ri"                  "Nam-chol Pak"
[169] "Kwang-chon Ri"              "Kum-il Kim"
[171] "Chol-hyok An"               "Yun-nam Ji"
[173] "Tae-se Jong"                "Yong-jo Hong"
[175] "In-guk Mun"                 "Kum-chol Choe"
[177] "Chol-jin Pak"               "Nam-Chol Pak"
[179] "Yong-jun Kim"               "Song-chol Nam"
[181] "Yong-hak An"                "Myong-gil Kim"
[183] "Chol-myong Ri"              "Myong-won Kim"
[185] "Kwang-hyok Ri"              "Kyong-il Kim"
[187] "Il-gwan Jong"               "Justo Villar"
[189] "Dario Veron"                "Claudio Morel"
[191] "Denis Caniza"               "Julio Cesar Caceres"
[193] "Carlos Bonet"               "Edgar Benitez"
[195] "Jonathan Santana"           "Diego Barreto"
[197] "Enrique Vera"               "Paulo da Silva"
[199] "Victor Caceres"             "Aureliano Torres"
[201] "Nestor Ortigoza"            "Aldo Bobadilla"
[203] "Rodolfo Gamarra"            "Miguel"
[205] "Deco"                       "Nemanja Vidic"
[207] "Nenad Milijas"              "Bojan Isailovic"
[209] "Nikola Zigic"               "Dragan Mrda"
[211] "Andelko Duricic"            "Zdeno Strba"
[213] "Jan Kozak"                  "Kamil Kopunek"
[215] "Martin Petras"              "Marko Suler"
[217] "Nejc Pecnik"                "Zlatan Ljubijankic"
[219] "Milivoje Novakovic"         "Jasmin Handanovic"
[221] "Zlatko Dedic"               "Aleksander Seliga"
[223] "Suad Filekovic"             "Andrej Komac"
[225] "Matej Mavric"               "Moeneeb Josephs"
[227] "Siboniso Gaxa"              "Tsepo Masilela"
[229] "Aaron Mokoena"              "MacBeth Sibaya"
[231] "Katlego Mphela"             "Teko Modise"
[233] "Reneilwe Letsholonyane"     "Matthew Booth"
[235] "Lucas Thwala"               "Itumeleng Khune"
[237] "Bernard Parker"             "Siyabonga Nomvethe"
[239] "Surprise Moriri"            "Siyabonga Sangweni"
[241] "Shu-Aib Walters"            "Thanduyise Khuboni"
[243] "Woon-jae Lee"               "Beom-seok Oh"
[245] "Hyung-il Kim"               "Yong-hyung Cho"
[247] "Nam-il Kim"                 "Jung-woo Kim"
[249] "Jung-hwan Ahn"              "Seung-yeoul Lee"
[251] "Young-pyo Lee"              "Jung-soo Lee"
[253] "Ki-hun Yeom"                "Dong-gook Lee"
[255] "Young-kwang Kim"            "Min-soo Kang"
[257] "Ludovic Magnin"             "Benjamin Huggel"
[259] "Alexander Frei"             "Blaise Nkufo"
[261] "Marco Wolfli"               "Stephane Grichting"
[263] "Marco Padalino"             "Hakan Yakin"
[265] "Albert Bunjaku"             "Carlos Bocanegra"
[267] "DaMarcus Beasley"           "Herculez Gomez"
[269] "Landon Donovan"             "Stuart Holden"
[271] "Jonathan Bornstein"         "Ricardo Clark"
[273] "Edson Buddle"               "Jay DeMerit"
[275] "Jose Francisco Torres"      "Robbie Findley"
[277] "Benny Feilhaber"            "Marcus Hahnemann"
[279] "Mauricio Victorino"         "Sebastian Eguren"
[281] "Diego Forlan"               "Sebastian Abreu"
[283] "Maxi Pereira"               "Andres Scotti"
[285] "Martin Silva"               "Cedric Si Mohamed"
[287] "Hillal Soudani"             "Mohamed Zemmamouche"
[289] "Liassine Cadamuro-Bentaiba" "Abdelmoumene Djabou"
[291] "Agustin Orion"              "Ricky Alvarez"
[293] "Matthew Spiranovic"         "Bailey Wright"
[295] "James Holland"              "Matt McKay"
[297] "Alex Wilkinson"             "Jasmin Fejzic"
[299] "Asmir Avdukic"              "Loic Feudjou"
[301] "Cedric Djeugoue"            "Eugenio Mena"
[303] "Cristopher Toselli"         "Jose Manuel Rojas"
[305] "Jose Pablo Fuenzalida"      "Johnny Herrera"
[307] "Alexander Mejia"            "Eder Alvarez Balanta"
[309] "Juan Camilo Zuniga"         "Faryd Mondragon"
[311] "Carlos Valdes"              "Jhonny Acosta"
[313] "Michael Umana"              "David Myrie"
[315] "Michael Barrantes"          "Waylon Francis"
[317] "Oscar Granados"             "Randall Brenes"
[319] "Patrick Pemberton"          "Roy Miller"
[321] "Diego Calvo"                "Jose Miguel Cubero"
[323] "Daniel Cambronero"          "Maximo Banguera"
[325] "Jorge Guagua"               "Frickson Erazo"
[327] "Edison Mendez"              "Joao Rojas"
[329] "Walter Ayovi"               "Adrian Bone"
[331] "Oswaldo Minda"              "Michael Arroyo"
[333] "Jaime Ayovi"                "Oscar Bagui"
[335] "Luis Saritama"              "Fidel Martinez"
[337] "Gabriel Achilier"           "Alexander Dominguez"
[339] "Stephen Adams"              "Emmanuel Agyemang-Badu"
[341] "Adam Larsen Kwarasey"       "Rashid Sumaila"
[343] "Fatau Dauda"                "Abdul Majeed Waris"
[345] "Harrison Afful"             "Kostas Manolas"
[347] "Kostas Mitroglou"           "Jose Holebas"
[349] "Juan Pablo Montes"          "Juan Carlos Garcia"
[351] "Jerry Bengtson"             "Edder Delgado"
[353] "Rony Martinez"              "Luis Garrido"
[355] "Marvin Chavez"              "Rahman Ahmadi"
[357] "Khosro Heydari"             "Jalal Hosseini"
[359] "Amir Hossein Sadeghi"       "Javad Nekounam"
[361] "Reza Haghighi"              "Ghasem Haddadifar"
[363] "Hossein Mahini"             "Andranik Teymourian"
[365] "Pejman Montazeri"           "Ahmad Alenemeh"
[367] "Bakhtiar Rahmani"           "Hashem Beikzadeh"
[369] "Steven Beitashour"          "Mehrdad Pooladi"
[371] "Sylvain Gbohouo"            "Serey Die"
[373] "Sayouba Mande"              "Yoichiro Kakitani"
[375] "Masahiko Inoha"             "Manabu Saito"
[377] "Jose de Jesus Corona"       "Alfredo Talavera"
[379] "Miguel Angel Ponce"         "Isaac Brizuela"
[381] "Oribe Peralta"              "Jose Juan Vazquez"
[383] "Azubuike Egwuekwe"          "John Obi Mikel"
[385] "Kunle Odunlami"             "Chigozie Agbim"
[387] "Andrei Semyonov"            "Chang-soo Kim"
[389] "Suk-young Yun"              "Tae-hwi Kwak"
[391] "Dae-sung Ha"                "Keun-ho Lee"
[393] "Kook-young Han"             "Jong-woo Park"
[395] "Shin-wook Kim"              "Bum-young Lee"
[397] "Matt Besler"                "Brad Davis"
[399] "Kyle Beckerman"             "Chris Wondolowski"
[401] "Graham Zusi"                "Nick Rimando"
[403] "Rodrigo Munoz"              "Jose Gimenez"
[405] "James Meredith"             "Dimitri Petratos"
[407] "Oscar Murillo"              "Farid Diaz"
[409] "Jose Fernando Cuadrado"     "Daniel Colindres"
[411] "Johan Venegas"              "David Guzman"
[413] "Kenner Gutierrez"           "Leonel Moreira"
[415] "Jens Stryger Larsen"        "Essam El Hadary"
[417] "Omar Gaber"                 "Ahmed Fathy"
[419] "Ayman Ashraf"               "Mohamed Abdel Shafy"
[421] "Mahmoud Hamdy"              "Sherif Ekramy"
[423] "Abdallah El Said"           "Saad Samir"
[425] "Birkir Mar Saevarsson"      "Bjorn Bergmann Sigurdarson"
[427] "Holmar Orn Eyjolfsson"      "Hordur Bjorgvin Magnusson"
[429] "Jon Dadi Bodvarsson"        "Mehdi Torabi"
[431] "Rouzbeh Cheshmi"            "Mohammad Rashid Mazaheri"
[433] "Mohammad Reza Khanzadeh"    "Tomoaki Makino"
[435] "Hugo Ayala"                 "Jesus Manuel Corona"
[437] "Munir Mohamedi"             "Aziz Bouhaddouz"
[439] "Ahmed Reda Tagnaouti"       "Mehdi Carcela"
[441] "Ikechukwu Ezenwa"           "Shehu Abdullahi"
[443] "Simeon Nwankwo"             "Daniel Akpeyi"
[445] "Jaime Penedo"               "Michael Amir Murillo"
[447] "Harold Cummings"            "Gabriel Gomez"
[449] "Blas Perez"                 "Edgar Barcenas"
[451] "Gabriel Torres"             "Armando Cooper"
[453] "Adolfo Machado"             "Valentin Pimentel"
[455] "Luis Ovalle"                "Luis Tejada"
[457] "Ricardo Avila"              "Felipe Baloy"
[459] "Aldo Corzo"                 "Raul Ruidiaz"
[461] "Christian Ramos"            "Jose Carvallo"
[463] "Nilson Loyola"              "Bartosz Bialkowski"
[465] "Yury Gazinsky"              "Mansoor Al-Harbi"
[467] "Ali Al-Bulaihi"             "Omar Hawsawi"
[469] "Mohammed Al-Breik"          "Mohammad Al-Sahlawi"
[471] "Abdulmalek Al-Khaibri"      "Housain Al-Mogahwi"
[473] "Taisir Al-Jassim"           "Muhannad Assiri"
[475] "Yasser Al-Mosailem"         "Motaz Hawsawi"
[477] "Kara Mbodji"                "Mame Biram Diouf"
[479] "Khadim N'Diaye"             "Ban-suk Oh"
[481] "Young-sun Yun"              "Hyun-soo Jang"
[483] "Yo-han Go"                  "Farouk Ben Mustapha"
[485] "Rami Bedoui"                "Ali Maaloul"
[487] "Mohamed Amine Ben Amor"     "Ahmed Khalil"
[489] "Aymen Mathlouthi"           "Ghailene Chaalali"
[491] "Hamdi Nagguez"              "Martin Campana"
[493] "Cameron Devlin"             "Jerome Ngom Mbekeli"
[495] "Moumi Ngamaleu"             "Andre-Frank Zambo Anguissa"
[497] "Samuel Gouet"               "Nouhou Tolo"
[499] "Souaibou Marou"             "Liam Fraser"
[501] "Lucas Cavallini"            "Daniel Chacon"
[503] "Keysher Fuller"             "Gerson Torres"
[505] "Douglas Lopez"              "Romario Ibarra"
[507] "Michael Estrada"            "Xavier Arreaga"
[509] "Sebas Mendez"               "Djorkaeff Reasco"
[511] "Abdul Fatawu Issahaku"      "Ibrahim Danlad"
[513] "Abdul Manaf Nurudeen"       "Baba Rahman"
[515] "Shojae Khalilzadeh"         "Hossein Kanaanizadegan"
[517] "Ahmad Nourollahi"           "Hossein Hosseini"
[519] "Abolfazl Jalali"            "Ilias Chair"
[521] "Badr Benoun"                "Yahya Jabrane"
[523] "Saad Al-Sheeb"              "Ali Assadalla"
[525] "Musab Kheder"               "Homam Ahmed"
[527] "Ismaeel Mohammad"           "Khalid Muneer"
[529] "Salem Al-Hajri"             "Yousef Hassan"
[531] "Naif Al-Hadhrami"           "Mostafa Meshaal"
[533] "Mohammed Al-Rubaie"         "Hassan Al-Tambakti"
[535] "Moussa N'Diaye"             "Moustapha Name"
[537] "Yoon Jong-gyu"              "Kim Jin-su"
[539] "Kim Min-jae"                "Hwang In-beom"
[541] "Paik Seung-ho"              "Cho Gue-sung"
[543] "Song Bum-keun"              "Son Jun-ho"
[545] "Kim Moon-hwan"              "Hwang Ui-jo"
[547] "Na Sang-ho"                 "Lee Kang-in"
[549] "Kwon Kyung-won"             "Kwon Chang-hoon"
[551] "Kim Tae-hwan"               "Cho Yu-min"
[553] "Jeong Woo-yeong"            "Song Min-kyu"
[555] "Bilel Ifa"                  "Hannibal Mejbri"
[557] "Taha Yassine Khenissi"      "Mohamed Ali Ben Romdhane"
[559] "Seifeddine Jaziri"          "Anis Ben Slimane"
[561] "Sebastian Sosa"             "Joe Morrell"
[563] "Jonny Williams"

I want to assses the relevance of this unmatched players to our dataset and start considering the possibility of exc;luding some of these players.

In [274]:
nonmatched <- setdiff(worldcup_players$full_name, player_names$name)
fullworldcup_players <- readRDS(here("1.DataCleaning-R", "Data", "RDS", "FullRoster.rds"))

fullworldcup_players %>% 
    filter(full_name %in% nonmatched) %>%
        group_by(team_name, tournament_id) %>%
            summarize(players= sum(n())) %>%
                arrange(desc(players))

`summarise()` has grouped output by 'team_name'. You can override using the
`.groups` argument.

    team_name     tournament_id players
1   North Korea   WC-2010       23
2   New Zealand   WC-2010       18
3   South Korea   WC-2022       18
4   South Africa  WC-2010       17
5   Iran          WC-2014       15
6   South Korea   WC-2010       14
7   Australia     WC-2010       13
8   Japan         WC-2010       13
9   United States WC-2010       12
10  Honduras      WC-2010       11
11  Paraguay      WC-2010       11
12  Saudi Arabia  WC-2018       11
13  Mexico        WC-2010       10
14  Qatar         WC-2022       10
15  Costa Rica    WC-2014        9
16  Egypt         WC-2018        9
17  Ghana         WC-2010        9
18  Panama        WC-2018        9
19  South Korea   WC-2014        9
20  Australia     WC-2014        8
21  Chile         WC-2010        8
22  Tunisia       WC-2022        8
23  Ecuador       WC-2014        7
24  Ghana         WC-2014        7
25  Honduras      WC-2014        7
26  Iran          WC-2022        7
27  Nigeria       WC-2010        7
28  Switzerland   WC-2010        7
29  Tunisia       WC-2018        7
30  United States WC-2014        7
... ...           ...           ...
50  Saudi Arabia  WC-2022       4
51  Argentina     WC-2010       3
52  Australia     WC-2018       3
53  Costa Rica    WC-2022       3
54  Greece        WC-2014       3
55  Japan         WC-2014       3
56  Mexico        WC-2018       3
57  Peru          WC-2018       3
58  Senegal       WC-2018       3
59  Australia     WC-2022       2
60  Canada        WC-2022       2
61  Ivory Coast   WC-2014       2
62  Russia        WC-2018       2
63  Senegal       WC-2022       2
64  Uruguay       WC-2010       2
65  Wales         WC-2022       2
66  Brazil        WC-2010       1
67  Cameroon      WC-2014       1
68  Denmark       WC-2010       1
69  Denmark       WC-2018       1
70  Denmark       WC-2022       1
71  France        WC-2010       1
72  Germany       WC-2010       1
73  Japan         WC-2018       1
74  Mexico        WC-2022       1
75  Netherlands   WC-2010       1
76  Russia        WC-2014       1
77  Slovenia      WC-2010       1
78  Uruguay       WC-2014       1
79  Uruguay       WC-2018       1

Looking at this table we can see two clear trends. Firstl;y, some countries have almost all their players missing, there's a big chance that some of this countries leagues are simply not in our dataste and hence most of their national team players arent available. The other trend is that the oldest the tournamnet the most missing players. Since there is a good chance many of this players we just dont have data for I've decided to take all temas with 8 or more missing players out of our training data.

In [277]:
fullworldcup_players %>% 
  filter(full_name %in% nonmatched) %>%
    group_by(team_name, tournament_id) %>%
        summarize(players = n(), .groups = "drop") %>%
            filter(players >= 8) %>%
                summarize(total_players = sum(players))

563-265

  total_players
1 265

[1] 298

Now we only have 298 missing players, this is reasonable at around 10% of total players. It's inevitable to work with some incomplete data and assuming most of the missing plkayers are lower profile players we can assume that there effect on team performances would be lower so the model shouldn't be affected too strongly.

In [282]:
matched_players <- worldcup_players %>%
  rename(player_id_fj = player_id) %>%
  distinct(full_name, .keep_all = TRUE) %>%
  inner_join(
    player_names %>%
      rename(
        player_id_kag = player_id,
        full_name = name
      ) %>%
      distinct(full_name, .keep_all = TRUE),
    by = "full_name"
  ) %>%
  select(full_name, player_id_fj, player_id_kag)

In [284]:
str(matched_players)
head(matched_players)
dim(matched_players)
any(duplicated(matched_players$player_id_fj))
any(duplicated(matched_players$player_id_kag))

tibble [1,811 x 3] (S3: tbl_df/tbl/data.frame)
 $ full_name    : chr [1:1811] "Anthar Yahia" "Rafik Halliche" "Ryad Boudebouz" "Mehdi Lacen" ...
 $ player_id_fj : chr [1:1811] "P-77742" "P-19453" "P-70903" "P-23484" ...
 $ player_id_kag: int [1:1811] 5586 67815 77826 35539 76406 20903 19385 74768 8060 12351 ...

  full_name          player_id_fj player_id_kag
1 Anthar Yahia       P-77742       5586
2 Rafik Halliche     P-19453      67815
3 Ryad Boudebouz     P-70903      77826
4 Mehdi Lacen        P-23484      35539
5 Abdelkader Ghezzal P-22008      76406
6 Rafik Djebbour     P-10693      20903

[1] 1811    3

[1] FALSE

[1] FALSE

In [287]:
saveRDS(matched_players, here("1.DataCleaning-R", "Data", "RDS", "Matching.rds"))